export type CaseStudy = {
  slug: string
  title: string
  specialization: string
  patientAge: number
  patientGender: 'Male' | 'Female' | 'Other'
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  chiefComplaint: string
  history: string
  examination: string
  ayurvedicAssessment: string
  diagnosis: string
  treatmentPlan: string
  outcome: string
  discussion: string
  tags: string[]
}

export const CASES: CaseStudy[] = [
  {
    slug: 'amavata-rheumatoid-arthritis',
    title: 'Amavata — Rheumatoid Arthritis Case',
    specialization: 'Kayachikitsa',
    patientAge: 38, patientGender: 'Female',
    difficulty: 'intermediate',
    chiefComplaint: 'Polyarticular joint pain and morning stiffness for 18 months. Worse in the morning, improves with movement but never fully resolves. Symmetrical involvement of hands, wrists, knees.',
    history: 'Symptoms started gradually. Initially attributed to "ageing" but progressed. Patient is a school teacher; difficulty writing on blackboard. Tried OTC ibuprofen with partial relief. RA factor positive on testing. Anti-CCP positive. ESR 64, CRP 22. Started on methotrexate 7.5mg/week 4 months ago — partial improvement, still significant morning stiffness >2 hours. Wants to add Ayurveda. No comorbidities. Periods irregular last 6 months.',
    examination: 'Bilateral MCP + PIP joints swollen, warm, tender. Wrists tender, reduced ROM. Knees crepitate, mild effusion. No deformities yet. Hands show "puffy" appearance. Tongue: heavy white coating (ama present). Pulse: thin, irregular, vata-pitta. BMI 26. BP 120/80. Mild pallor.',
    ayurvedicAssessment: 'Vikriti: Vata-pitta with ama. Dosha: vata-pradhana with ama in sandhis. Nidana: irregular meal timings + chronic professional stress + sedentary lifestyle + sleep disturbance (vata-vardhaka). Samprapti: Manda agni → ama → vyana vayu carries ama to sandhi → ama-vata combination → sandhi shotha + shoola + stabdhata. Roga marga: madhyama (sandhi involvement). Bala: madhyama. Sadhyata: kricchsadhya (sub-chronic, multi-joint, on DMARDs).',
    diagnosis: 'Amavata (Ayurvedic) corresponding to seropositive Rheumatoid Arthritis (modern). Stage: established, early erosive. Currently controlled partially with methotrexate.',
    treatmentPlan: 'Phase 1 — Langhana + Deepana-Pachana (3 weeks): Trikatu churnam 1g before meals × 2 weeks. Hingvashtaka churnam in food. Light easily digestible diet: warm kichadi, vegetable soups, ginger-cumin tea. Stop: cold water, dairy, refrigerated food, fermented foods, raw salads. Continue methotrexate as is. Phase 2 — Vata-Pacification (6 weeks): Rasna saptaka kashayam 30ml × bid before meals. Simhanada guggulu 250mg × bid post-meals. Erandapaka 10ml at night for vata-anuloma. Castor oil 5ml twice weekly for bowel regulation. Continue dietary restrictions. Phase 3 — Targeted Therapy (3 weeks): Daily abhyanga with mahanarayana taila + ksheera-bala taila. Local fomentation of affected joints with rasna kashaya. Joint-specific niruha basti 8-day yoga basti protocol (consider hospital setting). Phase 4 — Maintenance (lifelong): Continued kashaya at reduced dose. Yogabasti 1 month every 6 months. Ashwagandha + bala rasayana for dhatu strength. Yoga + pranayama daily. Goal: methotrexate dose reduction over 6-12 months with co-management.',
    outcome: 'Week 4: Morning stiffness reduced from >2 hours to 45 min. Less puffy joints. Tongue coating reducing. Week 12: Significant improvement. Methotrexate dose reduced from 7.5mg to 5mg/week in consultation with rheumatologist. ESR dropped to 38, CRP to 9. Patient back to teaching without significant hand fatigue. Week 24: Stable. Continues maintenance protocol. Periods regular again. Quality of life dramatically improved.',
    discussion: 'Key learning points: 1. Amavata is a chronic, lifelong condition (kricchsadhya at best). Aim is functional restoration + dose reduction of DMARDs, not "cure". 2. Always remove ama first. Snehapana in active ama-vata worsens disease — this is a common error. 3. Diet is 50% of treatment. Strict avoidance of vata-aggravating + ama-forming foods is non-negotiable. 4. Integration with rheumatology is essential. Sudden withdrawal of DMARDs to use Ayurveda alone causes flares. Best outcomes come from gradual dose reduction with monitoring. 5. Marker monitoring (ESR, CRP, periodic anti-CCP) tracks objectively. 6. Patient education: this is a multi-year journey. Setting realistic expectations prevents disappointment.',
    tags: ['amavata', 'rheumatoid arthritis', 'autoimmune', 'kayachikitsa'],
  },
  {
    slug: 'prameha-type-2-diabetes',
    title: 'Prameha — Newly Diagnosed Type 2 Diabetes',
    specialization: 'Kayachikitsa',
    patientAge: 47, patientGender: 'Male',
    difficulty: 'beginner',
    chiefComplaint: 'Routine health check revealed FBS 168, PPBS 256, HbA1c 8.4%. Otherwise asymptomatic except mild fatigue.',
    history: 'Sedentary office worker (IT). BMI 28. Family history: father T2DM, mother HTN. Diet: heavy lunch out, late dinner, sweet tea 4x/day. Exercise: nil. Sleep: 6 hours, irregular. No symptoms except mild lethargy. Lipids: TG 230, HDL 38. BP 134/86. No complications yet.',
    examination: 'Obesity (BMI 28). Mild central obesity. Skin: acanthosis nigricans on neck (insulin resistance marker). Tongue: thick white coating + slight yellowness at root. Pulse: slippery, slow — kapha-pitta. No diabetic complications on screening. Cardiac, neuro, fundus clear.',
    ayurvedicAssessment: 'Vikriti: Kapha-pitta with significant ama formation. Stage: kaphaja prameha — early type 2 DM. Nidana: classical "asyaasukha" (sedentary luxury) + madhura-snigdha-guru diet + chronic stress + sleep irregularity. Samprapti: Manda agni + sedentary lifestyle → ama + meda accumulation → meda-mamsa-vata dushti → loss of sweet substance through urine → frequent urination + obesity + lethargy. Bala: madhyama-uttama (good functional baseline). Sadhyata: sukha-sadhya at this stage with strict compliance.',
    diagnosis: 'Kaphaja prameha (early stage) = early type 2 DM with metabolic syndrome features (acanthosis nigricans, dyslipidemia, central obesity).',
    treatmentPlan: 'CRITICAL: This is a stage where intensive lifestyle intervention can reverse to pre-diabetes. Phase 1 — Lifestyle reset (8 weeks): Strict dietary protocol: 800-1200 kcal/day. Eliminate: white rice, white sugar, refined wheat, all sweets, fried foods, dairy in current amounts. Allowed: barley, kodo millet, sashtika rice in small amounts, all vegetables, lentils, methi seeds, bitter gourd, jamun, gymnema. 16:8 intermittent fasting (eat 10 AM - 6 PM only). Brisk walking 45 min/day + 2x/week resistance training. Sleep 10:30 PM consistently. Phase 2 — Ayurveda formulations: Vasanta kusumakar rasa 125mg bid (cautious — supervised). Vijayasara kashaya 30ml bid before meals. Methi seed powder 5g bid. Gymnema sylvestre 500mg bid. Triphala churnam 5g at night. Phase 3 — Co-management: Endocrinologist referral. Started on metformin 500mg bd. Quarterly HbA1c monitoring. Phase 4 — Maintenance (lifetime): Continued lifestyle. Reduced metformin dose over time as HbA1c targets achieved. Annual full lipid + renal + retinal screening.',
    outcome: 'Week 8: BMI 25.5. FBS 110, PPBS 145, HbA1c 6.8%. Energy improved. Skin acanthosis lighter. Week 24: BMI 24. FBS 96, PPBS 132, HbA1c 6.1%. Metformin reduced to 250mg bd. Lipids normalised. Patient committed to lifestyle long-term. Week 52: Stable at 6.0% HbA1c. Patient describes as "the best 12 months of my health in 20 years".',
    discussion: 'Key learning points: 1. Early-stage T2DM (HbA1c < 9, no complications) is sukha-sadhya with strict compliance. Pre-diabetes reversal possible. 2. Lifestyle is 70-80% of treatment. Medication-first approach without lifestyle change is poor practice. 3. Vasanta kusumakar contains parada bhasma; use only with experienced supervision + monitoring. 4. Integration with endocrinology essential. Patients fear modern drugs but skipping metformin in newly-diagnosed T2DM with HbA1c >7.5 is irresponsible. 5. Acanthosis nigricans is a useful early IR marker that resolves with insulin sensitisation. 6. Patient autonomy: the protocol works only if patient commits. Pre-commitment ritual + 8-week milestone helps adherence.',
    tags: ['prameha', 'diabetes', 't2dm', 'lifestyle', 'kayachikitsa'],
  },
  {
    slug: 'gridhrasi-sciatica',
    title: 'Gridhrasi — Sciatica Case',
    specialization: 'Panchakarma',
    patientAge: 42, patientGender: 'Male',
    difficulty: 'intermediate',
    chiefComplaint: 'Severe right-sided lower back pain radiating down the back of the leg to the foot for 6 weeks. Pain worse on sitting, better lying flat.',
    history: 'Long-distance truck driver. 14 years on the road, 12 hours daily. Episode started while loading cargo (lifting injury). MRI: L4-L5 mild disc bulge, L5-S1 moderate disc bulge with right-sided foraminal compression. Tried analgesics + physiotherapy 4 weeks with partial relief. Pain still 7/10 most days. Cannot drive comfortably; livelihood at risk. Wants Ayurveda as alternative to potential surgery.',
    examination: 'SLR right positive at 30°. Reflexes: ankle reflex diminished right. Sensory: paresthesia along S1 dermatome. Motor: mild weakness right plantarflexion (4/5). Spine flexion limited. Right paraspinal muscle spasm. No red flags (bowel/bladder, saddle anaesthesia). Tongue: thin, mild white coating, vata-dominant. Pulse: thin, fast — vata.',
    ayurvedicAssessment: 'Vikriti: Vata-pradhana with mild ama from sedentary occupation. Stage: established gridhrasi (sciatica). Nidana: prolonged sitting + lifting injury + irregular meals + sleep deprivation = classical vata aggravating lifestyle. Samprapti: Vata vrudhi → apana vayu involvement → ama-vata combination at kati-pradesha (lower back) → kataka-mamsa-snayu involvement → pain along gridhra (vulture-like) distribution. Bala: madhyama. Sadhyata: sadhya with appropriate treatment if patient compliant.',
    diagnosis: 'Vata-kaphaja gridhrasi (Ayurvedic) = lumbar disc-induced sciatica (modern, L5-S1 radiculopathy).',
    treatmentPlan: 'CRITICAL: Rule out cauda equina + red flags first. No surgery indication. Phase 1 — Acute Pain Control (1 week): Bed rest with proper mattress (firm). Local hot fomentation 3x/day. Castor oil internally 10ml at night to relieve vata + bowel regulation. Trayodashanga guggulu 250mg tid. Avoid: cold water, AC, ice packs. Phase 2 — Snehapana (5 days): Mahanarayana taila + ksheera-bala taila — increasing dose 30ml → 100ml over 5 days. Samyak signs at 100ml: snigdha skin, soft bowel, mild glow. Phase 3 — Vati Basti (single high-volume basti): Single basti of 600ml with: oil base + erandamoola + bala + dashamoola decoction. Vati basti is classical for severe sciatica. Inpatient setting. Phase 4 — Panchakarma course (15 days): Daily abhyanga with mahanarayana taila + steam. Daily kati basti at L5-S1 with mahanarayana taila. Yoga basti protocol (3 niruha + 5 anuvasana over 8 days). Phase 5 — Rasayana + Rehabilitation (lifelong): Ekangaveera rasa 125mg bd × 3 months. Bala-ksheera-pachana kashayam 30ml bd. Gentle yoga: cat-cow, child pose, hamstring stretches. Strict ergonomic protocol: truck seat lumbar support, 2-hour breaks for walking, weight lifting techniques. Job role adjustment if possible (avoid prolonged sitting).',
    outcome: 'Week 1: Pain reduced from 7/10 to 5/10. SLR at 45°. Week 4: Pain 3/10 occasionally. SLR at 60°. Patient driving short distances. Week 12: Pain-free most days. SLR at 70°. Returned to full work. Week 26: Stable. Periodic mild flare with prolonged sitting, managed with rasayana + brief pain medication. Patient enrolled in driver health programme.',
    discussion: 'Key learning points: 1. Sciatica is classical sadhya for Ayurveda if no red flags. Vati basti + kati basti are signature Kerala therapies with strong outcomes. 2. Snehapana is essential before basti — without proper oleation, basti effect is suboptimal. 3. Identify and address occupational factors. Without ergonomic correction, recurrence is guaranteed. 4. Surgery referral indications: progressive neurological deficit, cauda equina, severe pain unresponsive to 6 weeks of conservative therapy. Do not delay surgery if indicated. 5. Long-term: this is a chronic condition with episodic flares. Set expectations. 6. Yoga + pranayama recovery: not in acute pain; introduce gentle stretches week 4 onwards.',
    tags: ['gridhrasi', 'sciatica', 'panchakarma', 'basti', 'vatavyadhi'],
  },
  {
    slug: 'pandu-anemia',
    title: 'Pandu — Iron Deficiency Anemia in Young Female',
    specialization: 'Kayachikitsa',
    patientAge: 24, patientGender: 'Female',
    difficulty: 'beginner',
    chiefComplaint: 'Pallor + chronic fatigue + dizziness on standing for 6 months. Mild dyspnoea on exertion.',
    history: 'Postgraduate student. Vegetarian. Heavy menstrual periods (7 days, soaks pad in 2-3 hours). Tried iron tablets 3 months — GI intolerance, stopped. Hb 7.8 g/dL, MCV 72 (microcytic), Ferritin 8 ng/ml. No other comorbidities.',
    examination: 'Pale conjunctiva + nail beds. Pulse rapid 102. BP 100/64. Mild splenomegaly on deep palpation. Hair fall noted. Koilonychia mild. Tongue: pale, thin coat. Vata-pitta vikriti.',
    ayurvedicAssessment: 'Vikriti: Vata-pitta-pradhana with severe rasa-rakta dhatu kshaya. Stage: established pandu (anemia). Nidana: vegetarian diet without iron-rich foods + heavy menstrual losses + chronic stress + GI intolerance to iron supplements. Samprapti: Rakta dhatu kshaya → varna kshaya (pallor) → bala kshaya (fatigue) → kha-vaigunya in srotas → cardiac signs (rapid pulse). Bala: avara. Sadhyata: sadhya with combined approach.',
    diagnosis: 'Vataja-pittaja pandu (microcytic, iron-deficiency anemia) due to menstrual losses + dietary insufficiency.',
    treatmentPlan: 'Phase 1 — Address heavy bleeding (gynecology consult): Tranexamic acid during menses + Ayurveda artava-sthapaka herbs (chandanasava 30ml bid during menses). Phase 2 — Ayurveda hematinic protocol: Lohasava 30ml bid post-meals. Mandura bhasma 250mg bd with madhu + ghrita. Punarnavadi mandura 250mg bd. Drakshasava for iron absorption support. Phase 3 — Diet (essential): Dates + raisins + jaggery daily. Cooked spinach + methi leaves with lemon (vit C). Sesame seeds + til ladoo. Pomegranate juice fresh. Avoid: tea/coffee with meals (tannins block iron). Phase 4 — Co-management: Monthly Hb check. Endoscopy if no improvement at 8 weeks (rule out GI losses). Phase 5 — Maintenance: Once Hb > 12, continue mandura + iron-rich diet × 6 months to replenish stores. Recheck ferritin.',
    outcome: 'Week 4: Hb 9.2, energy improved. Week 8: Hb 11.0, MCV 78. Week 16: Hb 12.6, ferritin 28. Periods now manageable (5 days). Discontinued tranexamic acid; continued Ayurveda 6 more months for store replenishment. Discharged at Hb 13.4.',
    discussion: 'Key learning points: 1. Address underlying cause: iron-deficiency anemia in females always rule out menstrual cause + GI cause. 2. Ayurveda iron formulations (mandura bhasma) often better tolerated than synthetic ferrous sulphate — common reason patients prefer this route. 3. Diet + dravya combination outperforms drug-only approach. 4. Vit C + non-heme iron simultaneously aids absorption. 5. Continue treatment 3-6 months AFTER Hb normalises — store replenishment is the failure point most clinicians miss.',
    tags: ['pandu', 'anemia', 'iron-deficiency', 'kayachikitsa'],
  },
  {
    slug: 'artava-vyapad-pcos',
    title: 'Artava Vyapad — Polycystic Ovary Syndrome',
    specialization: 'Prasuti Tantra',
    patientAge: 27, patientGender: 'Female',
    difficulty: 'advanced',
    chiefComplaint: 'Irregular periods (cycles 45-90 days) for 5 years. Weight gain + facial hair + acne. Wants to conceive.',
    history: 'Married 2 years. TTC for 18 months. BMI 30. Diagnosed PCOS at 22 — was on OCP for 3 years which "fixed" cycles superficially. Stopped OCP last year for conception. USG: bilateral polycystic ovaries (>20 follicles each), endometrial thickness 6mm. TSH normal, prolactin normal, LH/FSH ratio 2.5, testosterone 0.8 ng/ml (elevated for female). Insulin resistance: fasting insulin 22.',
    examination: 'BMI 30 (obese). Acanthosis nigricans neck + axilla (severe IR). Hirsutism (mFGS 12). Acne face + chest. Pelvic exam: normal. Tongue: thick coating + scalloped (kapha + manda agni). Pulse: slow, slippery — kapha-pradhana.',
    ayurvedicAssessment: 'Vikriti: Kapha-pradhana with meda dushti + apana vata involvement + artava dushti. Stage: established artava vyapad. Nidana: irregular diet + sedentary + late nights + chronic stress + history of OCP suppression. Samprapti: Kapha-meda accumulation → apana vata channels obstruction → artava-vaha srotorodha → anovulation + ovarian cysts + insulin resistance + androgenic features. Bala: madhyama. Sadhyata: kricchsadhya for conception; sukha-sadhya for cycle regulation.',
    diagnosis: 'Vatakaphaja artava-kshaya / vyapad (Ayurveda) = polycystic ovary syndrome with anovulatory infertility (modern).',
    treatmentPlan: 'Phase 1 — Lifestyle reset (3 months, MOST IMPORTANT): Diet: low-carb (under 100g/day), high-fiber, high-protein. Eliminate: refined sugar, white rice, fried foods, dairy in current amounts. Allowed: vegetables, lean protein, low-GI fruits. Exercise: 1 hour daily — mix cardio + resistance + yoga. Sleep: 10:30 PM consistently. Stress: meditation + pranayama. Phase 2 — Ayurveda formulations: Shatavari ghrita 5g bid (artava-vardhaka). Ashwagandha 500mg bid (insulin sensitiser, stress). Triphala 5g at night (mild laxative + antioxidant). Kanchanara guggulu 500mg tid (kapha-meda reducer). Phala ghrita 5ml bid (uterine tonic). Phase 3 — Co-management (4 months): Endocrinology consult. Metformin 500mg bd for IR (proven for PCOS conception). If still not ovulating at month 6: clomiphene cycles 1-3. Letrozole as alternative. Phase 4 — Cycle regulation (ongoing): Rajahpravartini vati 250mg bd × 5 days before expected periods if delayed beyond 35 days. Ultrasound monitoring during conception attempts. Phase 5 — Conception support: Once ovulating: timed intercourse or IUI based on tubal status. Continue ashwagandha + shatavari until conception confirmed.',
    outcome: 'Month 3: BMI 27 (lost 6kg). Cycles 35 days. Hirsutism slightly improved. Month 6: BMI 25. Cycles 28-32 days. Spontaneous ovulation noted on day 14 of one cycle. Month 9: Conceived spontaneously. Healthy pregnancy. Continued shatavari + iron + folate. Healthy term delivery, baby girl.',
    discussion: 'Key learning points: 1. PCOS is THE poster child for lifestyle medicine. 60-80% of PCOS reversal happens with weight loss + exercise alone. 2. Metformin + ashwagandha both improve insulin sensitivity through complementary mechanisms. Combination is often superior to either alone. 3. Ayurveda timing matters: Rajahpravartini vati only if cycle is delayed beyond 35 days; not for shortening regular cycles. 4. Co-management with reproductive endocrinology essential for conception cases. Don\'t delay clomiphene/letrozole beyond 6 months of Ayurveda-only approach if patient is 30+. 5. Hirsutism + acne improve slowly (12-18 months). Set expectations. 6. Post-conception: continue conservative Ayurveda regimen, NOT herbs known to harm pregnancy.',
    tags: ['artava-vyapad', 'pcos', 'infertility', 'prasuti-tantra', 'hormonal'],
  },
  {
    slug: 'tamak-shwasa-asthma',
    title: 'Tamak Shwasa — Bronchial Asthma',
    specialization: 'Kayachikitsa',
    patientAge: 31, patientGender: 'Female',
    difficulty: 'intermediate',
    chiefComplaint: 'Recurrent wheezing + cough + chest tightness for 2 years. Worse early morning + with cold exposure. Tried inhalers — wants Ayurveda to reduce dependence.',
    history: 'Atopic family. Childhood eczema. Allergic rhinitis. Asthma diagnosed 2 years ago. Currently on budesonide-formoterol inhaler bd + albuterol SOS. Uses 2-3 SOS puffs daily. ER visit once last winter. Spirometry: FEV1 78% predicted, post-bronchodilator improvement 18%. IgE elevated.',
    examination: 'Mild dyspnoea on exertion. Chest: mild wheeze bilaterally. Cardiac normal. BMI 22. Tongue: thick white coating + post-nasal mucus pooling visible. Pulse: slippery, full — kapha-pradhana. Pranavaha + udakavaha srotas involvement.',
    ayurvedicAssessment: 'Vikriti: Kapha-vata pradhana with allergic prakopa. Stage: established tamak shwasa with chronic kapha + intermittent vata vega. Nidana: atopic constitution + cold exposure + dust allergy + dairy intake + irregular meal timing. Samprapti: kapha vrudhi in pranavaha + udakavaha srotas → ushas-kaal-vega (early morning aggravation) → bronchospasm + mucus + dyspnoea. Bala: madhyama. Sadhyata: yapya (manageable, not curable; modern asthma similarly).',
    diagnosis: 'Tamak shwasa (kapha-vata) = bronchial asthma with allergic component (modern).',
    treatmentPlan: 'Phase 1 — Acute stabilisation: Continue inhaler ICS-LABA. Don\'t stop modern medication. Identify + avoid triggers (dust, pets, cold air, specific allergens). Phase 2 — Ayurveda layered approach: Sitopaladi churnam 3g + madhu bd (kapha-shamana, srotoshodhana). Vasarishta 30ml bid (broncho-relaxant, mucolytic). Pippali vardhamana protocol: start 1 pippali, increase to 10 over 10 days, taper back. Bharangyadi kashayam 30ml bid. Phase 3 — Shodhana (when stable, off acute exacerbation): Vamana karma — classical first-line for kaphaja shwasa. 10-day hospital protocol: snehapana 5 days + vamana 1 day + sansarjana 4 days. Reduces inhaler need by 50-70% in studies. Phase 4 — Rasayana + Rehabilitation: Chyavanaprasha 5g bd. Pippali rasayana monthly. Yoga: bhastrika + kapalabhati daily (under instruction). Cold avoidance + warm nasya (anu taila 2 drops each nostril daily). Annual Vamana or yoga vasti (8-day basti) as maintenance.',
    outcome: 'Week 4: Wheeze episodes reduced from daily to 2-3x/week. SOS inhaler use down. Week 12: Post-vamana — SOS inhaler use minimal (0-1/week). ICS dose reduced under pulmonologist consult. Year 1: stable, single-puff ICS-LABA daily, no SOS use, no ER visits. Year 2: same.',
    discussion: 'Key learning points: 1. Asthma is yapya — manageable, not curable. Honest patient education prevents disappointment + dangerous medication abandonment. 2. Vamana for kaphaja shwasa has substantial evidence base. Most patients reduce ICS dose 30-50% post-vamana. 3. NEVER stop ICS abruptly. Reduce only under pulmonologist guidance. 4. Pippali vardhamana is signature Ayurveda for respiratory. Watch for pitta aggravation (start in winter, not summer). 5. Trigger avoidance is 30% of treatment. Without it, no medication works. 6. Yoga + pranayama have measurable spirometry improvement in trials. Make this non-negotiable.',
    tags: ['tamak-shwasa', 'asthma', 'kayachikitsa', 'pranavaha'],
  },
  {
    slug: 'vicharchika-eczema',
    title: 'Vicharchika — Atopic Eczema in Adult',
    specialization: 'Kayachikitsa',
    patientAge: 35, patientGender: 'Female',
    difficulty: 'beginner',
    chiefComplaint: 'Recurrent itchy dry skin patches on flexures + hands for 8 years. Worse in winter. Tried multiple topical steroids — relief, then rebound.',
    history: 'Atopic constitution (childhood eczema, allergic rhinitis). Avoids dairy intuitively. Stressful job + late nights. No food allergies confirmed.',
    examination: 'Lichenified plaques on antecubital fossa + popliteal fossa + hand dorsum. Excoriations. Dryness all over. No infection. Tongue: thin, mild white. Pulse: thin, fast — vata-pitta.',
    ayurvedicAssessment: 'Vikriti: Vata-pitta-pradhana with rakta dushti. Stage: chronic kshudra kushtha (vicharchika). Nidana: prakriti + dry climate + stress + late nights + topical steroid overuse. Samprapti: vata vrudhi → rakta-mamsa dushti → twak shoshana + kandu (itch) → scratching → lichenification cycle. Bala: madhyama. Sadhyata: kricchsadhya (chronic but manageable).',
    diagnosis: 'Vataja vicharchika (kapha-rakta dushti) = chronic atopic dermatitis (modern).',
    treatmentPlan: 'Phase 1 — Local + systemic: Manjishtadi kashayam 30ml bd. Mahatikta ghrita 5g bd for raktashodhana. External: shatadhauta ghrita as moisturiser bd. Coconut oil + camphor mix at night. Avoid: soap on lesions (use besan + milk). Phase 2 — Trigger management: Strict avoidance of hot water on lesions. Cotton clothing only. Humidifier in dry season. Stress management. Phase 3 — Shodhana (4 weeks in): Mild virechana with Avipattikar churnam 5g at night × 5 days. Phase 4 — Rasayana: Amalaki rasayana 5g bd. Continue mahatikta ghrita weekly.',
    outcome: 'Week 4: Lesions less inflamed. Week 8: Healed in most areas. Year 1: 1-2 mild flares (handled with rasayana boost), no steroid use.',
    discussion: 'Key learning: 1. Most adult eczema is vata-pitta with skin dryness pattern. 2. Stop topical steroids gradually (taper, not stop). 3. Moisturisation is 50% of treatment. 4. Shodhana before rasayana for clean tissue plane.',
    tags: ['vicharchika', 'eczema', 'kayachikitsa', 'twak-roga'],
  },
  {
    slug: 'ardita-facial-palsy',
    title: 'Ardita — Bell\'s Palsy Recovery',
    specialization: 'Panchakarma',
    patientAge: 39, patientGender: 'Male',
    difficulty: 'advanced',
    chiefComplaint: 'Right-sided facial weakness for 3 weeks. Started suddenly after cold exposure during night travel.',
    history: 'Trucker. Cold AC + window exposure prior. No HTN, DM. Trial of prednisolone + acyclovir at presentation (modern Bell\'s palsy protocol). Partial improvement but still significant residual at week 3. Wants Ayurveda for full recovery.',
    examination: 'Right House-Brackmann Grade IV. Cannot close right eye fully. Drooping right corner mouth. Loss of nasolabial fold. No motor deficit elsewhere. Tongue: thin, slight white. Pulse: thin, fast — vata.',
    ayurvedicAssessment: 'Vikriti: vata-pradhana with srotorodha at urdhva pradesha (face). Stage: established vatavyadhi — ardita. Nidana: sudden cold exposure + vata aggravating lifestyle. Samprapti: vata vega → siramukha shaitilya (slack mouth) → ekanga vata. Sadhyata: kricchsadhya if treated early; partial recovery common if delayed.',
    diagnosis: 'Right-sided ardita (Bell\'s palsy) post-viral with vata-aggravating exposure.',
    treatmentPlan: 'Phase 1 — Sneha + sweda: Daily abhyanga with mahanarayana taila + ksheera-bala taila on face + neck. Local steam to right face. Castor oil 10ml at night. Phase 2 — Nasya karma (signature for ardita): Anu taila nasya 6 drops each nostril daily × 14 days. Then ksheerabala nasya × 21 days. This is THE most important treatment for ardita. Phase 3 — Targeted therapy: Ekangaveera rasa 125mg bd. Daily face exercises (facial yoga). Speech therapy referral. Acupuncture if available (complementary evidence). Phase 4 — Rasayana: Brahmi + mandukaparni daily for nerve recovery. Continued nasya for 3 months. Avoid cold exposure.',
    outcome: 'Week 6 (3 weeks of treatment): HB Grade III. Week 12: Grade II. Year 1: Grade I (functional recovery). Some asymmetry visible on close inspection but functional.',
    discussion: 'Key learning: 1. Nasya is signature for ardita — Ayurveda\'s most powerful tool here. 2. Earlier treatment = better outcome. Start within 2 weeks. 3. Combined with steroid + facial exercises gives best results. 4. Recovery is slow (3-12 months). Patience essential.',
    tags: ['ardita', 'facial-palsy', 'bells-palsy', 'panchakarma', 'nasya'],
  },
  {
    slug: 'khalitya-hair-fall',
    title: 'Khalitya — Diffuse Hair Fall in Young Female',
    specialization: 'Shalakya',
    patientAge: 28, patientGender: 'Female',
    difficulty: 'beginner',
    chiefComplaint: 'Excessive hair fall (handfuls) for 8 months. Thinning visible at temples.',
    history: 'Vegetarian. Recent stress (job change, marriage). Iron deficiency anemia noted (Hb 10.6, ferritin 12). Thyroid normal. Vitamin D low. No autoimmune workup.',
    examination: 'Diffuse scalp hair thinning, fronto-parietal more than parietal. Hair pull test positive. Nails brittle. Pulse: thin, slightly fast — vata-pitta.',
    ayurvedicAssessment: 'Vikriti: pitta-vata-pradhana with rasa-rakta-asthi dhatu kshaya. Stage: established khalitya. Nidana: chronic stress + nutritional deficits + irregular sleep. Samprapti: rasa-rakta dushti → kesha-bhumi nourishment failure → kesha patana. Bala: madhyama. Sadhyata: sukha-sadhya at this stage.',
    diagnosis: 'Telogen effluvium triggered by stress + iron deficiency.',
    treatmentPlan: 'Phase 1 — Fix nutritional gaps: Iron + folate supplementation. Vitamin D 60,000 IU/week × 8 weeks. Protein intake increased. Phase 2 — Ayurveda: Bhringraja taila scalp oil massage bd (10 minutes). Bhringaraja churnam 3g internal bd. Aamla churnam 5g at night with warm water. Phase 3 — Local: Nilibhringadi taila weekly head bath. Avoid daily shampoo (use once weekly only). No tight hairstyles. Phase 4 — Lifestyle: Sleep before 11 PM. Stress reduction (yoga + meditation). Adequate protein + iron-rich diet.',
    outcome: 'Week 8: Pull test negative. Week 16: New hair growth visible at temples. Week 24: Substantial regrowth. Counts back to normal.',
    discussion: 'Key learning: 1. Fix underlying causes first (iron, vit D, stress). Without these, dravyas alone won\'t work. 2. Bhringaraja oil is the classical signature for khalitya. 3. Most telogen effluvium recovers spontaneously in 6-12 months once cause addressed.',
    tags: ['khalitya', 'hair-fall', 'shalakya', 'kesha-roga'],
  },
  {
    slug: 'katigraha-low-back-pain',
    title: 'Katigraha — Mechanical Low Back Pain',
    specialization: 'Shalya',
    patientAge: 50, patientGender: 'Male',
    difficulty: 'intermediate',
    chiefComplaint: 'Chronic low back pain × 3 years. Worse on prolonged standing. No radiation. No red flags.',
    history: 'Office worker. Sedentary 9-10 hours daily. BMI 28. Tried physiotherapy + occasional NSAIDs. MRI: degenerative spine, mild L4-L5 disc dehydration, no compression. No neurology.',
    examination: 'Lumbar spine: mild stiffness, paraspinal tenderness. Range of motion: flexion 70°, extension 15°. SLR negative bilateral. Neuro normal. Tongue: pale, mild coat. Pulse: thin — vata.',
    ayurvedicAssessment: 'Vikriti: vata-pradhana at kati pradesha. Stage: chronic vata vyadhi. Nidana: sedentary occupation + poor posture + irregular meals. Sadhyata: yapya (manageable, recurrent).',
    diagnosis: 'Katigraha (chronic mechanical low back pain) without radiculopathy.',
    treatmentPlan: 'Phase 1 — Symptom relief: Local hot fomentation bd. Castor oil at night. Trayodashanga guggulu 250mg tid. Phase 2 — Kati basti (signature): Daily kati basti at L4-L5 with mahanarayana taila × 10 days. Phase 3 — Maintenance: Daily abhyanga + steam. Ekangaveera rasa 125mg bd. Yoga: cat-cow, child pose, sphinx, bridge daily. Ergonomic correction at work.',
    outcome: 'Week 4: Pain reduced significantly. Week 12: Episodic mild pain only. Patient enrolled in office ergonomics + yoga programme.',
    discussion: 'Key learning: 1. Mechanical LBP without red flags is sadhya. 2. Kati basti is signature treatment with strong evidence. 3. Ergonomic + exercise is 60% of treatment. Without it, recurrence guaranteed.',
    tags: ['katigraha', 'low-back-pain', 'shalya', 'panchakarma'],
  },
]

export const CASE_SLUGS = CASES.map((c) => c.slug)
