// 100 classical Ayurvedic formulations sourced from Sahasrayogam, Ayurveda
// Formulary of India (AFI), and the standard Kerala pharmacopoeia. Maps to
// the existing AyurvedaFormulation model. Upsert by deterministic id so
// re-runs are idempotent. Malayalam names preserved as Unicode.

import type { PrismaClient } from '@prisma/client'

type Seed = {
  id:            string
  slug:          string
  name:          string                 // English
  sanskritName?: string | null
  malayalamName?: string | null
  classicalText: string                  // Sahasrayogam | AFI Part I | Ashtanga Hridayam | ...
  category:      string                  // existing model categories
  ingredients:   string[]
  primaryUses:   string[]
  doshaImpact?:  string | null
  typicalDose?:  string | null
  anupanaCommon?: string | null
  contraindications?: string | null
  manufacturers: string[]
  description:   string
}

const MFG_KERALA = ['Oushadhi', 'Kottakkal AVS', 'Vaidyaratnam']
const MFG_KOTTAKKAL = ['Kottakkal AVS', 'Vaidyaratnam', 'SNA Oushadhasala']
const MFG_OUSHADHI = ['Oushadhi', 'Kottakkal AVS', 'Pankajakasthuri']
const MFG_RASA = ['Kottakkal AVS', 'Vaidyaratnam', 'Kerala Ayurveda']
const DOSHA = (s: 'v' | 'p' | 'k' | 'vp' | 'vk' | 'pk' | 'tri'): string =>
  s === 'v' ? 'vata-pacifying' : s === 'p' ? 'pitta-pacifying' : s === 'k' ? 'kapha-pacifying'
  : s === 'vp' ? 'vata-pitta-pacifying' : s === 'vk' ? 'vata-kapha-pacifying' : s === 'pk' ? 'pitta-kapha-pacifying' : 'tridosha-balancing'
const DISC = '\n\nClassical formulation — consult a qualified Ayurveda doctor for personalised prescription, dose adjustment, and condition-specific suitability.'

const F: Seed[] = [
  // ─── KASHAYAM (decoctions) — 15 ───────────────────────────────────────
  { id: 'f2-dasamoolakashayam', slug: 'dasamoolakashayam-v2', name: 'Dasamoolakashayam', sanskritName: 'दशमूल क्वाथ', malayalamName: 'ദശമൂല കഷായം', classicalText: 'Ashtanga Hridayam', category: 'kashaya', ingredients: ['Bilva root','Agnimantha root','Syonaka root','Patala root','Gambhari root','Brihati','Kantakari','Gokshura','Shalaparni','Prishnaparni'], primaryUses: ['Vata disorders','Postpartum recovery','Fever (Jwara)','Respiratory weakness','Postoperative recovery'], doshaImpact: DOSHA('v'), typicalDose: '15 ml twice daily before food, mixed with equal warm water', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'The mother of all Vata-pacifying decoctions — the ten classical roots in equal proportion. Foundational support after delivery, after surgery, in chronic fatigue, and as a base for many compound Kashayams.' + DISC },
  { id: 'f2-dhanwantaram-kashayam', slug: 'dhanwantaram-kashayam', name: 'Dhanwantaram Kashayam', sanskritName: 'धन्वंतर क्वाथ', malayalamName: 'ധന്വന്തരം കഷായം', classicalText: 'Sahasrayogam', category: 'kashaya', ingredients: ['Bala root','Ashwagandha','Devadaru','Rasna','Eranda','Punarnava','Yastimadhu','Dashamoola'], primaryUses: ['Neuromuscular disorders','Sciatica','Postpartum care','Lumbar spondylosis','General Vata correction'], doshaImpact: DOSHA('v'), typicalDose: '15 ml twice daily before food', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Premier Vata-Kapha balancing Kashayam in the Kerala tradition. Strengthens nerves, joints, muscles. Standard postpartum formula.' + DISC },
  { id: 'f2-guggulutiktakam-kashayam', slug: 'guggulutiktakam-kashayam', name: 'Guggulutiktakam Kashayam', sanskritName: 'गुग्गुलुतिक्तक क्वाथ', malayalamName: 'ഗുഗ്ഗുലുതിക്തകം കഷായം', classicalText: 'Ashtanga Hridayam', category: 'kashaya', ingredients: ['Guggulu','Guduchi','Nimba','Vasa','Patola','Triphala','Trikatu','Yastimadhu'], primaryUses: ['Skin disorders','Rheumatoid arthritis','Lipid disorders','Chronic inflammation'], doshaImpact: DOSHA('pk'), typicalDose: '15 ml twice daily before food', anupanaCommon: 'warm water', contraindications: 'Acute Pitta excess; pregnancy', manufacturers: MFG_KERALA, description: 'Bitter-Guggulu compound — classical first-line for chronic inflammatory + skin disease. Pitta-Kapha pacifier.' + DISC },
  { id: 'f2-indukantham-kashayam', slug: 'indukantham-kashayam', name: 'Indukantham Kashayam', sanskritName: 'इन्दुकान्तं क्वाथ', malayalamName: 'ഇന്ദുകാന്തം കഷായം', classicalText: 'Sahasrayogam', category: 'kashaya', ingredients: ['Bilva','Agnimantha','Pippali','Pushkaramoola','Chitraka','Dashamoola','Yastimadhu'], primaryUses: ['Chronic fever','Loss of appetite','Convalescent care','Postpartum digestion','Childhood Agni weakness'], doshaImpact: DOSHA('v'), typicalDose: '15 ml twice daily before food', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Renowned post-illness digestive + Agni restorative — particularly used after fever and in children.' + DISC },
  { id: 'f2-rasnairandadi-kashayam', slug: 'rasnairandadi-kashayam', name: 'Rasnairandadi Kashayam', sanskritName: 'रास्नैरण्डादि क्वाथ', malayalamName: 'രാസ്നൈരണ്ഡാദി കഷായം', classicalText: 'Sahasrayogam', category: 'kashaya', ingredients: ['Rasna','Eranda root','Devadaru','Dashamoola','Punarnava','Yastimadhu'], primaryUses: ['Aamavata (rheumatoid arthritis)','Sciatica','Lumbar disc','Knee osteoarthritis'], doshaImpact: DOSHA('v'), typicalDose: '15 ml twice daily before food', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Specific to Aamavata — clears Ama from joints + reduces Vata. Classical first-line for rheumatoid disease.' + DISC },
  { id: 'f2-sahacharadi-kashayam', slug: 'sahacharadi-kashayam', name: 'Sahacharadi Kashayam', sanskritName: 'सहचरादि क्वाथ', malayalamName: 'സഹചരാദി കഷായം', classicalText: 'Sahasrayogam', category: 'kashaya', ingredients: ['Sahachara','Bala','Ashwagandha','Dashamoola','Eranda','Punarnava'], primaryUses: ['Sciatica','Lumbar back pain','Peripheral neuropathy','Hemiplegia recovery'], doshaImpact: DOSHA('v'), typicalDose: '15 ml twice daily before food', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Strong nerve-tonic Kashayam — paired with Sahacharadi Tailam externally for neurological + lower-limb disorders.' + DISC },
  { id: 'f2-gandharvahastadi-kashayam', slug: 'gandharvahastadi-kashayam', name: 'Gandharvahastadi Kashayam', sanskritName: 'गन्धर्वहस्तादि क्वाथ', malayalamName: 'ഗന്ധർവ്വഹസ്താദി കഷായം', classicalText: 'Sahasrayogam', category: 'kashaya', ingredients: ['Eranda','Sunthi','Hingu','Vacha','Triphala'], primaryUses: ['Constipation','Sciatica','Lumbar Vata','Pre-Panchakarma Snehana'], doshaImpact: DOSHA('v'), typicalDose: '15 ml twice daily before food (1-2 tsp castor oil after for purgation)', anupanaCommon: 'castor oil + warm water', contraindications: 'Diarrhoea, ulcerative colitis', manufacturers: MFG_KERALA, description: 'Mild Snehana + Anulomana Kashayam — clears Vata in Pakwashaya. Standard preparation before Virechana Panchakarma.' + DISC },
  { id: 'f2-kokilaksham-kashayam', slug: 'kokilaksham-kashayam', name: 'Kokilaksham Kashayam', sanskritName: 'कोकिलाक्षं क्वाथ', malayalamName: 'കോകിലാക്ഷം കഷായം', classicalText: 'Sahasrayogam', category: 'kashaya', ingredients: ['Kokilaksha','Punarnava','Gokshura','Varuna','Pashanabheda'], primaryUses: ['Urinary calculi','Dysuria','Benign prostatic hyperplasia','Lower-tract urinary infection'], doshaImpact: DOSHA('pk'), typicalDose: '15 ml twice daily before food', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Premier urinary-tract Kashayam — diuretic + calculus-dissolving. Particularly for Pittaja + Kaphaja Mutrashmari.' + DISC },
  { id: 'f2-varanadi-kashayam', slug: 'varanadi-kashayam', name: 'Varanadi Kashayam', sanskritName: 'वारणादि क्वाथ', malayalamName: 'വാരണാദി കഷായം', classicalText: 'Sahasrayogam', category: 'kashaya', ingredients: ['Varana','Triphala','Trikatu','Musta','Krishnajiraka','Apamarga'], primaryUses: ['Obesity / Sthaulya','Hypothyroidism','Lipid disorders','Fatty liver','Lymphatic congestion'], doshaImpact: DOSHA('k'), typicalDose: '15 ml twice daily before food', anupanaCommon: 'warm water with honey', contraindications: 'Pregnancy', manufacturers: MFG_KERALA, description: 'Classical Lekhana Kashayam — scrapes Medo-dushti from the body. Foundational for obesity + hypothyroid management.' + DISC },
  { id: 'f2-punarnavadi-kashayam', slug: 'punarnavadi-kashayam', name: 'Punarnavadi Kashayam', sanskritName: 'पुनर्नवादि क्वाथ', malayalamName: 'പുനർനവാദി കഷായം', classicalText: 'Sahasrayogam', category: 'kashaya', ingredients: ['Punarnava','Nimba','Patola','Guduchi','Daruharidra','Triphala'], primaryUses: ['Liver disorders','Generalised oedema','Ascites','Nephrotic-pattern','Anaemia'], doshaImpact: DOSHA('pk'), typicalDose: '15 ml twice daily before food', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Hepatoprotective + diuretic Kashayam. Cornerstone of Yakrit + Plihodara (liver/spleen) therapy.' + DISC },
  { id: 'f2-aragwadhadi-kashayam', slug: 'aragwadhadi-kashayam', name: 'Aragwadhadi Kashayam', sanskritName: 'आरग्वधादि क्वाथ', malayalamName: 'ആരഗ്വധാദി കഷായം', classicalText: 'Sahasrayogam', category: 'kashaya', ingredients: ['Aragwadha','Indrayava','Nimba','Patola','Triphala','Trayamana'], primaryUses: ['Chronic skin disease','Psoriasis','Allergic dermatitis','Mild constipation','Kushta'], doshaImpact: DOSHA('pk'), typicalDose: '15 ml twice daily before food', anupanaCommon: 'warm water', contraindications: 'Severe diarrhoea', manufacturers: MFG_KERALA, description: 'Classical Pitta-Rakta cleanser — bitter Kashayam used in all chronic Kushta. Mildly laxative.' + DISC },
  { id: 'f2-nimbamritadi-kashayam', slug: 'nimbamritadi-kashayam', name: 'Nimbamritadi Kashayam', sanskritName: 'निम्बामृतादि क्वाथ', malayalamName: 'നിമ്ബാമൃതാദി കഷായം', classicalText: 'Sahasrayogam', category: 'kashaya', ingredients: ['Nimba','Guduchi (Amrita)','Vasa','Patola','Triphala'], primaryUses: ['Chronic fever','Liver disorders','Diabetes','Skin disease'], doshaImpact: DOSHA('p'), typicalDose: '15 ml twice daily before food', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Bitter Pitta-pacifying Kashayam — classical first-line for chronic Pittaja Jwara + Yakrit disorders.' + DISC },
  { id: 'f2-patolamooladi-kashayam', slug: 'patolamooladi-kashayam', name: 'Patolamooladi Kashayam', sanskritName: 'पटोलमूलादि क्वाथ', malayalamName: 'പടോലമൂലാദി കഷായം', classicalText: 'Sahasrayogam', category: 'kashaya', ingredients: ['Patola root','Triphala','Nimba','Vasa','Trayamana'], primaryUses: ['Chronic skin disease','Eczema','Itchy rash','Liver Pitta excess'], doshaImpact: DOSHA('p'), typicalDose: '15 ml twice daily before food', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Bitter Kashayam acting on skin via Pitta-Rakta correction. Often paired with Mahatiktaka Ghrita.' + DISC },
  { id: 'f2-amritottaram-kashayam', slug: 'amritottaram-kashayam', name: 'Amritottaram Kashayam', sanskritName: 'अमृतोत्तरं क्वाथ', malayalamName: 'അമൃതോത്തരം കഷായം', classicalText: 'Sahasrayogam', category: 'kashaya', ingredients: ['Guduchi (Amrita)','Triphala','Eranda','Sunthi'], primaryUses: ['Chronic fever','Aamavata','Mild constipation','Postpartum Vata'], doshaImpact: DOSHA('vp'), typicalDose: '15 ml twice daily before food', anupanaCommon: 'warm water with castor oil', contraindications: null, manufacturers: MFG_KERALA, description: 'Mild Snehana-Anulomana with Guduchi as primary — for low-grade chronic fevers + Aamavata.' + DISC },
  { id: 'f2-chiruvilwadi-kashayam', slug: 'chiruvilwadi-kashayam', name: 'Chiruvilwadi Kashayam', sanskritName: 'चिरुविल्वादि क्वाथ', malayalamName: 'ചിറുവില്വാദി കഷായം', classicalText: 'Sahasrayogam', category: 'kashaya', ingredients: ['Chiruvilwa root','Triphala','Trikatu','Yavakshara'], primaryUses: ['Haemorrhoids (Arsha)','Fistula','Chronic constipation','Anorectal disorders'], doshaImpact: DOSHA('v'), typicalDose: '15 ml twice daily before food', anupanaCommon: 'warm water', contraindications: 'Bleeding diatheses', manufacturers: MFG_KERALA, description: 'Classical Arsha Kashayam — shrinks haemorrhoidal plexus + corrects underlying Vata constipation.' + DISC },

  // ─── ARISHTAM & ASAVAM (fermented) — 15 ───────────────────────────────
  { id: 'f2-dasamoolarishtam', slug: 'dasamoolarishtam-v2', name: 'Dasamoolarishtam', sanskritName: 'दशमूलारिष्ट', malayalamName: 'ദശമൂലാരിഷ്ടം', classicalText: 'Sharangadhara Samhita', category: 'arishtam', ingredients: ['Dashamoola','Chitraka','Pushkaramoola','Dhataki flower','Madhuka','Guda'], primaryUses: ['Postpartum recovery','Generalised weakness','Anaemia','Cough','Vata-borne fevers'], doshaImpact: DOSHA('v'), typicalDose: '15-30 ml twice daily after food with equal water', anupanaCommon: 'equal warm water', contraindications: 'Children under 12; pregnancy first trimester', manufacturers: MFG_KERALA, description: 'Iconic fermented Vata-corrective — the standard tonic for new mothers across Kerala households.' + DISC },
  { id: 'f2-abhayarishtam', slug: 'abhayarishtam', name: 'Abhayarishtam', sanskritName: 'अभयारिष्ट', malayalamName: 'അഭയാരിഷ്ടം', classicalText: 'Bhaishajya Ratnavali', category: 'arishtam', ingredients: ['Haritaki (Abhaya)','Vidanga','Madhuka','Munakka','Dhataki flower','Guda'], primaryUses: ['Chronic constipation','Haemorrhoids','Anorectal disorders','IBS-C'], doshaImpact: DOSHA('v'), typicalDose: '15-30 ml twice daily after food', anupanaCommon: 'equal warm water', contraindications: 'Severe diarrhoea', manufacturers: MFG_KERALA, description: 'Classical Anulomana Arishtam — gentle daily corrective for chronic constipation with Vata pattern.' + DISC },
  { id: 'f2-ashokarishta', slug: 'ashokarishta', name: 'Ashokarishta', sanskritName: 'अशोकारिष्ट', malayalamName: 'അശോകാരിഷ്ടം', classicalText: 'Bhaishajya Ratnavali', category: 'arishtam', ingredients: ['Ashoka bark','Dhataki flower','Triphala','Pippali','Krishnajiraka','Vasaka','Musta','Guda'], primaryUses: ['Menorrhagia','Dysmenorrhoea','Leucorrhoea','PCOS-related bleeding','Postpartum bleeding'], doshaImpact: DOSHA('p'), typicalDose: '15-30 ml twice daily after food', anupanaCommon: 'equal warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Premier gynaecological Arishtam — Pitta-pacifying uterine tonic. First-line for Asrigdara.' + DISC },
  { id: 'f2-draksharishta', slug: 'draksharishta', name: 'Draksharishta', sanskritName: 'द्राक्षारिष्ट', malayalamName: 'ദ്രാക്ഷാരിഷ്ടം', classicalText: 'Sharangadhara Samhita', category: 'arishtam', ingredients: ['Draksha (raisin)','Dashamoola','Pippali','Triphala','Dhataki flower','Guda'], primaryUses: ['Generalised debility','Chronic cough','Hyperacidity','Postpartum care','Loss of appetite'], doshaImpact: DOSHA('vp'), typicalDose: '15-30 ml twice daily after food', anupanaCommon: 'equal warm water', contraindications: 'Diabetes mellitus (uncontrolled)', manufacturers: MFG_KERALA, description: 'Sweet, mildly cooling Arishtam — classical Brimhana + Rasayana. Restorative for convalescence.' + DISC },
  { id: 'f2-jirakadyarishtam', slug: 'jirakadyarishtam', name: 'Jirakadyarishtam', sanskritName: 'जीरकाद्यारिष्ट', malayalamName: 'ജീരകാദ്യാരിഷ്ടം', classicalText: 'Sahasrayogam', category: 'arishtam', ingredients: ['Jiraka','Trikatu','Dashamoola','Lavanga','Ela','Dhataki flower'], primaryUses: ['Postpartum digestion','Lactating mother tonic','Loss of appetite','Indigestion'], doshaImpact: DOSHA('v'), typicalDose: '15 ml twice daily after food', anupanaCommon: 'equal warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Carminative + digestive Arishtam developed for new mothers — restores Agni after Sutika period.' + DISC },
  { id: 'f2-kutajarishtam', slug: 'kutajarishtam', name: 'Kutajarishtam', sanskritName: 'कुटजारिष्ट', malayalamName: 'കുടജാരിഷ്ടം', classicalText: 'Bhaishajya Ratnavali', category: 'arishtam', ingredients: ['Kutaja bark','Mridvika','Madhuka','Dhataki flower','Guda'], primaryUses: ['Amoebiasis','Chronic diarrhoea','IBS-D','Bleeding piles','Grahani'], doshaImpact: DOSHA('p'), typicalDose: '15-30 ml twice daily after food', anupanaCommon: 'equal warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Classical anti-diarrhoeal Arishtam. Direct anti-amoebic action documented in modern studies.' + DISC },
  { id: 'f2-lohasavam', slug: 'lohasavam', name: 'Lohasavam', sanskritName: 'लोहासव', malayalamName: 'ലോഹാസവം', classicalText: 'Bhaishajya Ratnavali', category: 'asava', ingredients: ['Lauha bhasma','Triphala','Trikatu','Musta','Dhataki flower'], primaryUses: ['Iron-deficiency anaemia','Chronic fatigue','Hepatosplenomegaly','Pandu'], doshaImpact: DOSHA('pk'), typicalDose: '15 ml twice daily after food', anupanaCommon: 'equal warm water', contraindications: 'Pregnancy without supervision', manufacturers: MFG_RASA, description: 'Classical haematinic Asavam containing purified iron. Iron-fortified — should be taken under physician supervision.' + DISC },
  { id: 'f2-kumaryasavam', slug: 'kumaryasavam', name: 'Kumaryasavam', sanskritName: 'कुमार्यासव', malayalamName: 'കുമാര്യാസവം', classicalText: 'Bhaishajya Ratnavali', category: 'asava', ingredients: ['Aloe vera (Kumari)','Iron Bhasma','Triphala','Trikatu','Musta','Yastimadhu'], primaryUses: ['Menstrual disorders','Anaemia','Liver enlargement','Chronic dyspepsia'], doshaImpact: DOSHA('pk'), typicalDose: '15 ml twice daily after food', anupanaCommon: 'equal warm water', contraindications: 'Acute haemorrhage', manufacturers: MFG_RASA, description: 'Aloe + iron-base Asavam acting on Pitta liver + uterine bed. Particularly for fibrotic uterine pattern.' + DISC },
  { id: 'f2-saraswatharishtam', slug: 'saraswatharishtam', name: 'Saraswatharishtam', sanskritName: 'सारस्वतारिष्ट', malayalamName: 'സരസ്വതാരിഷ്ടം', classicalText: 'Bhaishajya Ratnavali', category: 'arishtam', ingredients: ['Brahmi','Shankhapushpi','Vacha','Triphala','Pippali','Suvarna bhasma','Dhataki flower'], primaryUses: ['Anxiety','Insomnia','Memory weakness','Speech difficulty','Mental dullness'], doshaImpact: DOSHA('v'), typicalDose: '15 ml twice daily after food', anupanaCommon: 'equal warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Premier Medhya (cognitive) Arishtam — anxiolytic + nootropic. Often paired with Brahmi Ghrita.' + DISC },
  { id: 'f2-pippalyasavam', slug: 'pippalyasavam', name: 'Pippalyasavam', sanskritName: 'पिप्पल्यासव', malayalamName: 'പിപ്പല്യാസവം', classicalText: 'Bhaishajya Ratnavali', category: 'asava', ingredients: ['Pippali','Pippalimoola','Chavya','Chitraka','Trikatu','Dhataki flower'], primaryUses: ['Chronic cough','Bronchitis','Asthma support','Loss of appetite'], doshaImpact: DOSHA('k'), typicalDose: '15 ml twice daily after food', anupanaCommon: 'equal warm water', contraindications: 'Acute Pitta excess; ulcer', manufacturers: MFG_KERALA, description: 'Strong Kapha-Vata pacifying Asavam — long-pepper based, for chronic respiratory weakness.' + DISC },
  { id: 'f2-chandanasavam', slug: 'chandanasavam', name: 'Chandanasavam', sanskritName: 'चन्दनासव', malayalamName: 'ചന്ദനാസവം', classicalText: 'Sahasrayogam', category: 'asava', ingredients: ['Chandana','Mocharasa','Lodhra','Triphala','Yastimadhu','Dhataki flower'], primaryUses: ['Urinary burning','Cystitis','Excessive thirst','Bleeding disorders','Hyperacidity'], doshaImpact: DOSHA('p'), typicalDose: '15 ml twice daily after food', anupanaCommon: 'equal water', contraindications: null, manufacturers: MFG_KERALA, description: 'Cooling Asavam specific to Pitta-Rakta in the urinary tract. Excellent for cystitis + dysuria.' + DISC },
  { id: 'f2-balarishta', slug: 'balarishta', name: 'Balarishta', sanskritName: 'बलारिष्ट', malayalamName: 'ബലാരിഷ്ടം', classicalText: 'Sharangadhara Samhita', category: 'arishtam', ingredients: ['Bala root','Ashwagandha','Rasna','Dashamoola','Eranda','Dhataki flower'], primaryUses: ['Vata disorders','Postpartum tonic','Muscle wasting','Convalescence','Sciatica'], doshaImpact: DOSHA('v'), typicalDose: '15-30 ml twice daily after food', anupanaCommon: 'equal warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Strong Vata-pacifying Arishtam — anabolic + nerve tonic. Standard postoperative + post-illness recovery support.' + DISC },
  { id: 'f2-punarnavasavam', slug: 'punarnavasavam', name: 'Punarnavasavam', sanskritName: 'पुनर्नवासव', malayalamName: 'പുനർനവാസവം', classicalText: 'Bhaishajya Ratnavali', category: 'asava', ingredients: ['Punarnava','Triphala','Trikatu','Daruharidra','Kutaki','Dhataki flower'], primaryUses: ['Ascites','Liver enlargement','Generalised oedema','Anaemia with hepatic component'], doshaImpact: DOSHA('pk'), typicalDose: '15-30 ml twice daily after food', anupanaCommon: 'equal warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Hepatoprotective Asavam — direct action on fluid retention via Yakrit + Mutravaha-srotas.' + DISC },
  { id: 'f2-ushirasavam', slug: 'ushirasavam', name: 'Ushirasavam', sanskritName: 'उशीरासव', malayalamName: 'ഉശിരാസവം', classicalText: 'Bhaishajya Ratnavali', category: 'asava', ingredients: ['Ushira (Vetiver)','Padmaka','Khadira','Triphala','Manjishtha','Dhataki flower'], primaryUses: ['Bleeding disorders','Heavy menses','Urinary burning','Chronic fever','Pitta haemorrhage'], doshaImpact: DOSHA('p'), typicalDose: '15-30 ml twice daily after food', anupanaCommon: 'equal water', contraindications: null, manufacturers: MFG_KERALA, description: 'Cooling Pitta-Rakta Asavam — first-line for haemorrhagic Pittaja disorders.' + DISC },
  { id: 'f2-aravindasavam', slug: 'aravindasavam', name: 'Aravindasavam', sanskritName: 'अरविन्दासव', malayalamName: 'അരവിന്ദാസവം', classicalText: 'Sahasrayogam', category: 'asava', ingredients: ['Aravinda (lotus)','Brahmi','Vacha','Triphala','Yastimadhu','Dhataki flower'], primaryUses: ['Paediatric tonic','Growth in undernourished children','Cognitive development','Recurrent infections in children'], doshaImpact: DOSHA('tri'), typicalDose: '2-10 ml twice daily after food (paediatric dose by physician)', anupanaCommon: 'equal warm water or honey', contraindications: null, manufacturers: MFG_KERALA, description: 'Classical paediatric tonic — Medhya + nourishing. Especially for thin children with poor appetite.' + DISC },

  // ─── CHURNAM (powders) — 15 ───────────────────────────────────────────
  { id: 'f2-triphala-churnam', slug: 'triphala-churnam', name: 'Triphala Churnam', sanskritName: 'त्रिफला चूर्ण', malayalamName: 'ത്രിഫല ചൂർണ്ണം', classicalText: 'Charaka Samhita', category: 'choornam', ingredients: ['Haritaki','Bibhitaki','Amalaki'], primaryUses: ['Daily Anulomana','Eye disorders','Mild Lekhana','Anti-aging Rasayana'], doshaImpact: DOSHA('tri'), typicalDose: '1 tsp at bedtime with warm water', anupanaCommon: 'warm water or honey', contraindications: 'Diarrhoea', manufacturers: MFG_KERALA, description: 'The three fruits — single most-used Ayurvedic preparation worldwide. Daily Tridoshic detoxification.' + DISC },
  { id: 'f2-hinguvachadi-churnam', slug: 'hinguvachadi-churnam', name: 'Hinguvachadi Churnam', sanskritName: 'हिङ्ग्वाचादि चूर्ण', malayalamName: 'ഹിങ്ഗ്വാചാദി ചൂർണ്ണം', classicalText: 'Sahasrayogam', category: 'choornam', ingredients: ['Hingu','Vacha','Saindhava','Trikatu','Trijata','Ajamoda'], primaryUses: ['Indigestion','Abdominal colic','Flatulence','Loss of appetite','IBS'], doshaImpact: DOSHA('v'), typicalDose: '3-5 g twice daily before food', anupanaCommon: 'warm water with ghee', contraindications: 'Hyperacidity, ulcer', manufacturers: MFG_KERALA, description: 'Classical carminative-digestive — quick acting on bloating, gas, colic. Pre-meal use is standard.' + DISC },
  { id: 'f2-avipathi-churnam', slug: 'avipathi-churnam', name: 'Avipathi Churnam', sanskritName: 'अविपत्ति चूर्ण', malayalamName: 'അവിപത്തി ചൂർണ്ണം', classicalText: 'Sahasrayogam', category: 'choornam', ingredients: ['Trivrit','Triphala','Vidanga','Trikatu','Lavanga','Ela','Sita'], primaryUses: ['Hyperacidity','GERD','Migraine with hyperacidity','Constipation with Pitta'], doshaImpact: DOSHA('p'), typicalDose: '5-10 g once daily at bedtime', anupanaCommon: 'warm water', contraindications: 'Severe diarrhoea', manufacturers: MFG_KERALA, description: 'Mild laxative + Pitta-corrective — premier first-line for Amlapitta. Often part of Virechana preparation.' + DISC },
  { id: 'f2-ashtachurnam', slug: 'ashtachurnam', name: 'Ashtachurnam', sanskritName: 'अष्टचूर्ण', malayalamName: 'അഷ്ടചൂർണ്ണം', classicalText: 'Sahasrayogam', category: 'choornam', ingredients: ['Sunthi','Pippali','Marich','Vidanga','Jiraka','Hingu','Ajamoda','Saindhava'], primaryUses: ['Chronic indigestion','Bloating','Abdominal pain','Worm infestation'], doshaImpact: DOSHA('v'), typicalDose: '3-5 g twice daily before food', anupanaCommon: 'warm water', contraindications: 'Hyperacidity, ulcer', manufacturers: MFG_KERALA, description: 'Eight-ingredient digestive Churnam — broader-spectrum than Hinguvachadi. Adult chronic dyspepsia.' + DISC },
  { id: 'f2-trikatu-churnam', slug: 'trikatu-churnam', name: 'Trikatu Churnam', sanskritName: 'त्रिकटु चूर्ण', malayalamName: 'ത്രികടു ചൂർണ്ണം', classicalText: 'Charaka Samhita', category: 'choornam', ingredients: ['Sunthi','Pippali','Marich'], primaryUses: ['Indigestion','Kapha disorders','Obesity','Chronic cough','Bioavailability enhancer'], doshaImpact: DOSHA('k'), typicalDose: '1-3 g twice daily before food with honey', anupanaCommon: 'honey or warm water', contraindications: 'Hyperacidity, ulcer, pregnancy', manufacturers: MFG_KERALA, description: 'Three pungents — universal Agnideepana + Pachana. Foundational Kapha + Medo-corrective.' + DISC },
  { id: 'f2-pushyanuga-churnam', slug: 'pushyanuga-churnam', name: 'Pushyanuga Churnam', sanskritName: 'पुष्यानुग चूर्ण', malayalamName: 'പുഷ്യാനുഗ ചൂർണ്ണം', classicalText: 'Charaka Samhita', category: 'choornam', ingredients: ['Mocha rasa','Ashoka','Pasanabheda','Lodhra','Daruharidra','Bilva','Triphala'], primaryUses: ['Menorrhagia','Leucorrhoea','Uterine bleeding','Postpartum bleeding'], doshaImpact: DOSHA('p'), typicalDose: '3-5 g twice daily with rice water', anupanaCommon: 'rice gruel or honey', contraindications: null, manufacturers: MFG_KERALA, description: 'Classical haemostatic Churnam for excessive menstrual + uterine bleeding. 25+ ingredients in original.' + DISC },
  { id: 'f2-vilwadi-churnam', slug: 'vilwadi-churnam', name: 'Vilwadi Churnam', sanskritName: 'विल्वादि चूर्ण', malayalamName: 'വില്വാദി ചൂർണ്ണം', classicalText: 'Sahasrayogam', category: 'choornam', ingredients: ['Bilva','Triphala','Pippali','Lavanga','Karkatashringi'], primaryUses: ['Chronic diarrhoea','IBS-D','Grahani','Mucus in stools'], doshaImpact: DOSHA('v'), typicalDose: '3-5 g twice daily before food', anupanaCommon: 'rice water or honey', contraindications: null, manufacturers: MFG_KERALA, description: 'Bilva-based anti-diarrhoeal Churnam — slow + steady restoration of Grahani Agni.' + DISC },
  { id: 'f2-indukantham-churnam', slug: 'indukantham-churnam', name: 'Indukantham Churnam', sanskritName: 'इन्दुकान्तं चूर्ण', malayalamName: 'ഇന്ദുകാന്തം ചൂർണ്ണം', classicalText: 'Sahasrayogam', category: 'choornam', ingredients: ['Dashamoola','Pippali','Pushkaramoola','Chitraka','Yastimadhu'], primaryUses: ['Chronic fever','Postpartum digestion','Convalescent recovery'], doshaImpact: DOSHA('v'), typicalDose: '3-5 g twice daily before food', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Powder form of the Indukantham series — convenient daily Agni restorative.' + DISC },
  { id: 'f2-dasamoola-churnam', slug: 'dasamoola-churnam', name: 'Dasamoola Churnam', sanskritName: 'दशमूल चूर्ण', malayalamName: 'ദശമൂല ചൂർണ്ണം', classicalText: 'Charaka Samhita', category: 'choornam', ingredients: ['Bilva','Agnimantha','Syonaka','Patala','Gambhari','Brihati','Kantakari','Gokshura','Shalaparni','Prishnaparni'], primaryUses: ['General Vata','Postpartum tonic','Convalescent recovery','Respiratory weakness'], doshaImpact: DOSHA('v'), typicalDose: '3-5 g twice daily before food', anupanaCommon: 'warm water with honey', contraindications: null, manufacturers: MFG_KERALA, description: 'Ten-roots Churnam — powdered base for many compound formulations. General Vata corrective.' + DISC },
  { id: 'f2-musta-churnam', slug: 'musta-churnam', name: 'Musta Churnam', sanskritName: 'मुस्त चूर्ण', malayalamName: 'മുസ്താ ചൂർണ്ണം', classicalText: 'Charaka Samhita', category: 'choornam', ingredients: ['Musta (Cyperus rotundus)'], primaryUses: ['IBS','Diarrhoea','Loss of appetite','Acne','Menstrual disorders'], doshaImpact: DOSHA('pk'), typicalDose: '2-3 g twice daily before food', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Single-herb Churnam — Pitta-Kapha digestive + emmenagogue. Foundational Ayurvedic raw material.' + DISC },
  { id: 'f2-grihadhoomadi-churnam', slug: 'grihadhoomadi-churnam', name: 'Grihadhoomadi Churnam', sanskritName: 'गृहधूमादि चूर्ण', malayalamName: 'ഗൃഹധൂമാദി ചൂർണ്ണം', classicalText: 'Sahasrayogam', category: 'choornam', ingredients: ['Grihadhoma','Triphala','Trikatu','Daruharidra','Karpuram','Rasakarpura'], primaryUses: ['Topical Lepa for skin disease','Eczema','Itching','Allergic dermatitis'], doshaImpact: DOSHA('pk'), typicalDose: 'Topical paste with appropriate Anupana', anupanaCommon: 'coconut milk or rice water for paste', contraindications: 'Open wounds', manufacturers: MFG_KERALA, description: 'Classical topical Lepa for chronic skin disease — paste-form external application.' + DISC },
  { id: 'f2-panchakola-churnam', slug: 'panchakola-churnam', name: 'Panchakola Churnam', sanskritName: 'पञ्चकोल चूर्ण', malayalamName: 'പഞ്ചകോല ചൂർണ്ണം', classicalText: 'Charaka Samhita', category: 'choornam', ingredients: ['Pippali','Pippalimoola','Chavya','Chitraka','Sunthi'], primaryUses: ['Chronic indigestion','Abdominal colic','Anorexia','Lekhana'], doshaImpact: DOSHA('vk'), typicalDose: '2-3 g twice daily before food with honey or warm water', anupanaCommon: 'honey or warm water', contraindications: 'Hyperacidity, ulcer', manufacturers: MFG_KERALA, description: 'Five-pungents Churnam — stronger than Trikatu. For severe Agni Mandya + Aam.' + DISC },
  { id: 'f2-rasnerandadi-churnam', slug: 'rasnerandadi-churnam', name: 'Rasnerandadi Churnam', sanskritName: 'रास्नैरण्डादि चूर्ण', malayalamName: 'രാസ്നൈരണ്ഡാദി ചൂർണ്ണം', classicalText: 'Sahasrayogam', category: 'choornam', ingredients: ['Rasna','Eranda root','Devadaru','Trikatu'], primaryUses: ['Aamavata','Sciatica','Knee pain','Lumbar disc'], doshaImpact: DOSHA('v'), typicalDose: '3-5 g twice daily before food', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Powder form of Rasnairandadi — convenient daily anti-Aamavata.' + DISC },
  { id: 'f2-vaiswanara-churnam', slug: 'vaiswanara-churnam', name: 'Vaiswanara Churnam', sanskritName: 'वैश्वानर चूर्ण', malayalamName: 'വൈശ്വാനര ചൂർണ്ണം', classicalText: 'Sahasrayogam', category: 'choornam', ingredients: ['Trikatu','Haritaki','Saindhava','Yavakshara','Ajamoda','Hingu'], primaryUses: ['Severe indigestion','Abdominal pain','Aamavata','Vata-Kapha Agni Mandya'], doshaImpact: DOSHA('vk'), typicalDose: '2-3 g twice daily before food', anupanaCommon: 'warm water or buttermilk', contraindications: 'Hyperacidity, ulcer, pregnancy', manufacturers: MFG_KERALA, description: 'Strong digestive Churnam — Agni-Mandya + Aam. Quick acting.' + DISC },
  { id: 'f2-sitopaladi-churnam', slug: 'sitopaladi-churnam', name: 'Sitopaladi Churnam', sanskritName: 'सितोपलादि चूर्ण', malayalamName: 'സിതോപലാദി ചൂർണ്ണം', classicalText: 'Sharangadhara Samhita', category: 'choornam', ingredients: ['Sitopala (sugar candy)','Vamsalochana','Pippali','Ela','Twak'], primaryUses: ['Cough','Bronchitis','Asthma','Loss of appetite','Children\'s cough'], doshaImpact: DOSHA('vk'), typicalDose: '3-5 g twice daily with honey or ghee', anupanaCommon: 'honey or ghee', contraindications: 'Severe diabetes', manufacturers: MFG_KERALA, description: 'Iconic Kerala cough remedy — sweet, soothing, Kapha-Vata pacifying. Safe for children.' + DISC },

  // ─── GHRITAM (medicated ghee) — 10 ────────────────────────────────────
  { id: 'f2-guggulutiktaka-ghritam', slug: 'guggulutiktaka-ghritam', name: 'Guggulutiktaka Ghritam', sanskritName: 'गुग्गुलुतिक्तक घृत', malayalamName: 'ഗുഗ്ഗുലുതിക്തക ഘൃതം', classicalText: 'Ashtanga Hridayam', category: 'ghritam', ingredients: ['Guggulu','Triphala','Trikatu','Nimba','Vasa','Patola','Yastimadhu','Cow ghee'], primaryUses: ['Chronic skin disease','Psoriasis','Internal Snehana before Virechana','Rheumatoid arthritis'], doshaImpact: DOSHA('pk'), typicalDose: '5-10 g once daily early morning on empty stomach', anupanaCommon: 'warm water after 1 hour', contraindications: 'Pregnancy; acute Pitta excess', manufacturers: MFG_KERALA, description: 'Premier Ghrita for chronic skin + Pitta-Rakta disorders. Internal Snehana of choice for Virechana Panchakarma.' + DISC },
  { id: 'f2-indukantham-ghritam', slug: 'indukantham-ghritam', name: 'Indukantham Ghritam', sanskritName: 'इन्दुकान्तं घृत', malayalamName: 'ഇന്ദുകാന്തം ഘൃതം', classicalText: 'Sahasrayogam', category: 'ghritam', ingredients: ['Dashamoola','Pippali','Pushkaramoola','Chitraka','Yastimadhu','Cow ghee'], primaryUses: ['Chronic fever','Loss of appetite','Convalescent care','Postpartum tonic','Children'], doshaImpact: DOSHA('v'), typicalDose: '5-10 g once daily before food', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Iconic post-illness restorative Ghrita — gentle Agni rebuild + Vata pacification.' + DISC },
  { id: 'f2-mahatiktaka-ghritam', slug: 'mahatiktaka-ghritam', name: 'Mahatiktaka Ghritam', sanskritName: 'महातिक्तक घृत', malayalamName: 'മഹാതിക്തക ഘൃതം', classicalText: 'Charaka Samhita', category: 'ghritam', ingredients: ['Many bitter herbs (Tikta dravyas)','Triphala','Nimba','Vasa','Patola','Cow ghee'], primaryUses: ['Severe skin disease','Psoriasis','Chronic eczema','Pitta-Rakta dushti','Diabetes complications'], doshaImpact: DOSHA('p'), typicalDose: '5-10 g once daily early morning', anupanaCommon: 'warm water after 1 hour', contraindications: 'Pregnancy', manufacturers: MFG_KERALA, description: 'Most bitter of all classical Ghritams — for severe Pitta-Rakta dushti. Pre-Virechana Snehana.' + DISC },
  { id: 'f2-dadimadi-ghritam', slug: 'dadimadi-ghritam', name: 'Dadimadi Ghritam', sanskritName: 'दाडिमादि घृत', malayalamName: 'ദാഡിമാദി ഘൃതം', classicalText: 'Sahasrayogam', category: 'ghritam', ingredients: ['Dadima (pomegranate)','Dhanyaka','Yastimadhu','Vatsanabha','Cow ghee'], primaryUses: ['Anaemia','Bleeding disorders','Postpartum hemorrhage','Excessive bleeding in menses'], doshaImpact: DOSHA('p'), typicalDose: '5-10 g once daily before food', anupanaCommon: 'warm milk', contraindications: null, manufacturers: MFG_KERALA, description: 'Cooling Pitta-Rakta Ghrita — for haemorrhagic + anaemic conditions.' + DISC },
  { id: 'f2-kalyanaka-ghritam', slug: 'kalyanaka-ghritam', name: 'Kalyanaka Ghritam', sanskritName: 'कल्याणक घृत', malayalamName: 'കല്യാണക ഘൃതം', classicalText: 'Charaka Samhita', category: 'ghritam', ingredients: ['Brahmi','Shankhapushpi','Vacha','Many cognitive herbs','Cow ghee'], primaryUses: ['Mental disorders','Epilepsy','Memory weakness','Cognitive decline','Mania'], doshaImpact: DOSHA('v'), typicalDose: '5-10 g once daily before food', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Classical Medhya Ghrita — for serious mental disorders + epilepsy.' + DISC },
  { id: 'f2-brahmi-ghritam', slug: 'brahmi-ghritam', name: 'Brahmi Ghritam', sanskritName: 'ब्राह्मी घृत', malayalamName: 'ബ്രാഹ്മി ഘൃതം', classicalText: 'Charaka Samhita', category: 'ghritam', ingredients: ['Brahmi','Vacha','Sankhupushpi','Yastimadhu','Cow ghee'], primaryUses: ['Insomnia','Anxiety','Memory weakness','Children\'s Medhya Rasayana','ADHD'], doshaImpact: DOSHA('v'), typicalDose: '1 tsp at bedtime', anupanaCommon: 'warm milk', contraindications: null, manufacturers: MFG_KERALA, description: 'Premier cognitive Ghrita — bedtime Medhya for insomnia + anxiety. Safe for children.' + DISC },
  { id: 'f2-shatavari-ghritam', slug: 'shatavari-ghritam', name: 'Shatavari Ghritam', sanskritName: 'शतावरी घृत', malayalamName: 'ശതാവരി ഘൃതം', classicalText: 'Sahasrayogam', category: 'ghritam', ingredients: ['Shatavari','Yastimadhu','Bala','Vidari','Cow ghee'], primaryUses: ['Female reproductive Rasayana','Postpartum care','Hyperacidity','Lactation support'], doshaImpact: DOSHA('vp'), typicalDose: '5-10 g once daily before food', anupanaCommon: 'warm milk', contraindications: null, manufacturers: MFG_KERALA, description: 'Female reproductive Ghrita — cooling, building, lactagogue.' + DISC },
  { id: 'f2-panchagavya-ghritam', slug: 'panchagavya-ghritam', name: 'Panchagavya Ghritam', sanskritName: 'पञ्चगव्य घृत', malayalamName: 'പഞ്ചഗവ്യ ഘൃതം', classicalText: 'Charaka Samhita', category: 'ghritam', ingredients: ['Cow milk','Cow curd','Cow ghee','Cow urine (purified)','Cow dung extract (Gomaya rasa)'], primaryUses: ['Liver disorders','Jaundice','Mental disorders','Epilepsy','Chronic fever'], doshaImpact: DOSHA('vp'), typicalDose: '5-10 g once daily before food', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Five-cow-product Ghrita — classical hepatic + cognitive support. Used under physician supervision.' + DISC },
  { id: 'f2-phala-ghritam', slug: 'phala-ghritam', name: 'Phala Ghritam', sanskritName: 'फल घृत', malayalamName: 'ഫല ഘൃതം', classicalText: 'Charaka Samhita', category: 'ghritam', ingredients: ['Aragwadha','Triphala','Yastimadhu','Vidari','Bala','Cow ghee'], primaryUses: ['Infertility (Vandhyatva)','Pre-conception preparation','Postpartum tonic','Female reproductive support'], doshaImpact: DOSHA('vp'), typicalDose: '5-10 g once daily early morning, for 3 cycles', anupanaCommon: 'warm milk', contraindications: 'Pregnancy (use under supervision)', manufacturers: MFG_KERALA, description: 'Classical fertility Ghrita — Beeja-Kshetra correction. Both partners can take.' + DISC },
  { id: 'f2-dhanwantaram-ghritam', slug: 'dhanwantaram-ghritam', name: 'Dhanwantaram Ghritam', sanskritName: 'धन्वंतर घृत', malayalamName: 'ധന്വന്തരം ഘൃതം', classicalText: 'Sahasrayogam', category: 'ghritam', ingredients: ['Bala','Dashamoola','Ashwagandha','Sahachara','Cow ghee'], primaryUses: ['Vata disorders','Postpartum care','Neuromuscular weakness','Pre-Panchakarma Snehapana'], doshaImpact: DOSHA('v'), typicalDose: '5-10 g once daily before food', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Iconic Vata-corrective Ghrita — postpartum + neuromuscular. Often pre-Panchakarma Snehana.' + DISC },

  // ─── TAILAM (medicated oils) — 15 ─────────────────────────────────────
  { id: 'f2-dhanwantaram-tailam', slug: 'dhanwantaram-tailam', name: 'Dhanwantaram Tailam', sanskritName: 'धन्वंतर तैल', malayalamName: 'ധന്വന്തരം തൈലം', classicalText: 'Sahasrayogam', category: 'taila', ingredients: ['Bala','Ashwagandha','Dashamoola','Sahacharadi base','Sesame oil'], primaryUses: ['Abhyanga for Vata disorders','Postpartum massage','Lumbar pain','Neurological recovery'], doshaImpact: DOSHA('v'), typicalDose: 'External Abhyanga 25-50 ml', anupanaCommon: 'external only', contraindications: 'Open wounds, acute Pitta inflammation', manufacturers: MFG_KERALA, description: 'Premier Kerala Vata-pacifying massage oil — Abhyanga gold standard.' + DISC },
  { id: 'f2-ksheerabala-tailam', slug: 'ksheerabala-tailam', name: 'Ksheerabala Tailam', sanskritName: 'क्षीरबला तैल', malayalamName: 'ക്ഷീരബല തൈലം', classicalText: 'Sahasrayogam', category: 'taila', ingredients: ['Bala','Cow milk','Sesame oil'], primaryUses: ['Vata-Pitta disorders','Insomnia','Headache','Migraine','Pre-Shirodhara'], doshaImpact: DOSHA('vp'), typicalDose: 'External application', anupanaCommon: 'external only', contraindications: null, manufacturers: MFG_KERALA, description: 'Cooling Vata-Pitta corrective oil — first-line Shirodhara oil + head massage.' + DISC },
  { id: 'f2-kottamchukkadi-tailam', slug: 'kottamchukkadi-tailam', name: 'Kottamchukkadi Tailam', sanskritName: 'कोष्ठशुक्कादि तैल', malayalamName: 'കോട്ടംചുക്കാദി തൈലം', classicalText: 'Sahasrayogam', category: 'taila', ingredients: ['Kushtha','Shunthi','Devadaru','Vacha','Karpura','Sesame oil'], primaryUses: ['Aamavata','Joint pain with swelling','Sciatica','Frozen shoulder'], doshaImpact: DOSHA('vk'), typicalDose: 'External, twice daily', anupanaCommon: 'external only', contraindications: 'Open wounds, Pitta inflammation', manufacturers: MFG_KERALA, description: 'Warm + pungent Aamavata oil — clears Ama from joints externally.' + DISC },
  { id: 'f2-pinda-tailam', slug: 'pinda-tailam', name: 'Pinda Tailam', sanskritName: 'पिण्ड तैल', malayalamName: 'പിണ്ഡ തൈലം', classicalText: 'Sahasrayogam', category: 'taila', ingredients: ['Sariva','Manjishtha','Lac','Vatsanabha (purified)','Sesame oil'], primaryUses: ['Gout','Burning joint pain','Pitta arthritis','Skin discoloration'], doshaImpact: DOSHA('p'), typicalDose: 'External application', anupanaCommon: 'external only', contraindications: 'Open wounds', manufacturers: MFG_KERALA, description: 'Cooling Pitta-pacifying oil — first-line for gouty arthritis + Pittaja Sandhi-shoola.' + DISC },
  { id: 'f2-eladi-tailam', slug: 'eladi-tailam', name: 'Eladi Tailam', sanskritName: 'एलादि तैल', malayalamName: 'ഏലാദി തൈലം', classicalText: 'Ashtanga Hridayam', category: 'taila', ingredients: ['Ela','Twak','Patra','Manjishtha','Many cooling herbs','Sesame oil'], primaryUses: ['Eczema','Allergic dermatitis','Skin discoloration','Itchy rash','Cosmetic skin care'], doshaImpact: DOSHA('p'), typicalDose: 'External application', anupanaCommon: 'external only', contraindications: 'Open wounds', manufacturers: MFG_KERALA, description: 'Classical cooling oil for chronic eczema + skin disease. Pitta-Rakta corrective.' + DISC },
  { id: 'f2-murivenna', slug: 'murivenna', name: 'Murivenna', sanskritName: 'मूरिवेन्ना', malayalamName: 'മുരിവെണ്ണ', classicalText: 'Sahasrayogam', category: 'taila', ingredients: ['Onion','Garlic','Many specific Kerala herbs','Sesame oil'], primaryUses: ['Sprains','Fractures (post-cast)','Soft-tissue injury','Sports injury'], doshaImpact: DOSHA('v'), typicalDose: 'External application, gentle massage', anupanaCommon: 'external only', contraindications: 'Open wounds', manufacturers: MFG_KERALA, description: 'Iconic Kerala first-aid oil for sprains, ligament tears, fractures. Promotes union + healing.' + DISC },
  { id: 'f2-sahacharadi-tailam', slug: 'sahacharadi-tailam', name: 'Sahacharadi Tailam', sanskritName: 'सहचरादि तैल', malayalamName: 'സഹചരാദി തൈലം', classicalText: 'Sahasrayogam', category: 'taila', ingredients: ['Sahachara','Dashamoola','Sesame oil'], primaryUses: ['Sciatica','Lumbar disc','Peripheral neuropathy','Lower-limb Vata'], doshaImpact: DOSHA('v'), typicalDose: 'External Abhyanga 25-50 ml', anupanaCommon: 'external only', contraindications: null, manufacturers: MFG_KERALA, description: 'Lower-limb Vata oil — premier for sciatica + lumbar disc disease.' + DISC },
  { id: 'f2-gandha-tailam', slug: 'gandha-tailam', name: 'Gandha Tailam', sanskritName: 'गन्ध तैल', malayalamName: 'ഗന്ധ തൈലം', classicalText: 'Sahasrayogam', category: 'taila', ingredients: ['Bala','Ashwagandha','Many fragrant Vata herbs','Sesame oil'], primaryUses: ['Fractures (post-cast)','Osteoporosis support','Bone strengthening','Asthi-Kshaya'], doshaImpact: DOSHA('v'), typicalDose: '10-15 ml internally + external application', anupanaCommon: 'warm milk', contraindications: null, manufacturers: MFG_KERALA, description: 'Both internal + external Vata-Asthi-corrective. Iconic post-fracture oil in Kerala.' + DISC },
  { id: 'f2-asanabilwadi-tailam', slug: 'asanabilwadi-tailam', name: 'Asanabilwadi Tailam', sanskritName: 'असनबिल्वादि तैल', malayalamName: 'അസനബില്വാദി തൈലം', classicalText: 'Sahasrayogam', category: 'taila', ingredients: ['Asana','Bilva','Bala','Sesame oil'], primaryUses: ['ENT disorders','Otitis','Hearing weakness','Sinusitis'], doshaImpact: DOSHA('v'), typicalDose: 'Karna Purana (ear instillation) 2-4 drops', anupanaCommon: 'external only', contraindications: 'Acute infections', manufacturers: MFG_KERALA, description: 'Classical Karna Purana oil — restores hearing + ear health.' + DISC },
  { id: 'f2-balaswagandhadi-tailam', slug: 'balaswagandhadi-tailam', name: 'Balaswagandhadi Tailam', sanskritName: 'बलाश्वगन्धादि तैल', malayalamName: 'ബലാശ്വഗന്ധാദി തൈലം', classicalText: 'Sahasrayogam', category: 'taila', ingredients: ['Bala','Ashwagandha','Dashamoola','Sesame oil'], primaryUses: ['Muscle wasting','Childhood debility','Polio sequelae','Adult muscle weakness'], doshaImpact: DOSHA('v'), typicalDose: 'External Abhyanga', anupanaCommon: 'external only', contraindications: null, manufacturers: MFG_KERALA, description: 'Anabolic Vata-pacifying oil — for muscle wasting + childhood debility.' + DISC },
  { id: 'f2-lakshadi-tailam', slug: 'lakshadi-tailam', name: 'Lakshadi Tailam', sanskritName: 'लाक्षादि तैल', malayalamName: 'ലാക്ഷാദി തൈലം', classicalText: 'Sahasrayogam', category: 'taila', ingredients: ['Laksha (lac)','Manjishtha','Bala','Sesame oil'], primaryUses: ['Children\'s Abhyanga','Bone strengthening','Growth support','Children\'s skin disorders'], doshaImpact: DOSHA('vp'), typicalDose: 'External Abhyanga for children', anupanaCommon: 'external only', contraindications: null, manufacturers: MFG_KERALA, description: 'Premier paediatric Abhyanga oil — supports growth + bone development.' + DISC },
  { id: 'f2-neelibhringadi-tailam', slug: 'neelibhringadi-tailam', name: 'Neelibhringadi Tailam', sanskritName: 'नीलीभृंगादि तैल', malayalamName: 'നീലിഭൃംഗാദി തൈലം', classicalText: 'Sahasrayogam', category: 'taila', ingredients: ['Neeli','Bhringaraja','Amalaki','Coconut oil base'], primaryUses: ['Hair fall','Premature greying','Dandruff','Scalp Pitta'], doshaImpact: DOSHA('p'), typicalDose: 'Shiroabhyanga 3+ times weekly', anupanaCommon: 'external only', contraindications: null, manufacturers: MFG_KERALA, description: 'Iconic Kerala hair oil — first-line for Khalitya + Palitya.' + DISC },
  { id: 'f2-chemparathyadi-tailam', slug: 'chemparathyadi-tailam', name: 'Chemparathyadi Tailam', sanskritName: 'चेम्पारथ्यादि तैल', malayalamName: 'ചെമ്പരത്യാദി തൈലം', classicalText: 'Sahasrayogam', category: 'taila', ingredients: ['Chemparathy (hibiscus)','Bhringaraja','Coconut oil'], primaryUses: ['Hair fall','Premature greying','Cooling scalp Pitta'], doshaImpact: DOSHA('p'), typicalDose: 'Shiroabhyanga', anupanaCommon: 'external only', contraindications: null, manufacturers: MFG_KERALA, description: 'Hibiscus-based cooling hair oil — secondary to Neelibhringadi.' + DISC },
  { id: 'f2-triphaladi-tailam', slug: 'triphaladi-tailam', name: 'Triphaladi Tailam', sanskritName: 'त्रिफलादि तैल', malayalamName: 'ത്രിഫലാദി തൈലം', classicalText: 'Sahasrayogam', category: 'taila', ingredients: ['Triphala','Yastimadhu','Coconut oil'], primaryUses: ['Conjunctivitis','Eye irritation','Eye fatigue'], doshaImpact: DOSHA('p'), typicalDose: '1 drop in each eye twice daily (under physician supervision)', anupanaCommon: 'external only', contraindications: 'Acute eye infection', manufacturers: MFG_KERALA, description: 'Ophthalmic oil for chronic eye disorders. Use only under Vaidya supervision.' + DISC },
  { id: 'f2-nalpamaradi-tailam', slug: 'nalpamaradi-tailam', name: 'Nalpamaradi Tailam', sanskritName: 'नालपामरादि तैल', malayalamName: 'നാല്പാമരാദി തൈലം', classicalText: 'Sahasrayogam', category: 'taila', ingredients: ['Four classical bark herbs (Nalpamaram)','Manjishtha','Coconut oil'], primaryUses: ['Skin discoloration','Acne','Cosmetic skin care','Hyperpigmentation'], doshaImpact: DOSHA('pk'), typicalDose: 'External application', anupanaCommon: 'external only', contraindications: 'Open wounds', manufacturers: MFG_KERALA, description: 'Cosmetic Kerala oil — corrects pigmentation + acne marks. Cooling Pitta-Kapha.' + DISC },

  // ─── LEHAM / RASAYANAM (confections) — 15 ─────────────────────────────
  { id: 'f2-chyawanprash', slug: 'chyawanprash', name: 'Chyawanprash', sanskritName: 'च्यवनप्राश', malayalamName: 'ച്യവനപ്രാശം', classicalText: 'Charaka Samhita', category: 'lehyam', ingredients: ['Amalaki (50+)','Dashamoola','Ashwagandha','Pippali','Cow ghee','Honey','Sugar'], primaryUses: ['General Rasayana','Immunity','Anti-aging','Respiratory tonic','Bone strengthening'], doshaImpact: DOSHA('tri'), typicalDose: '1 tsp twice daily, morning + evening', anupanaCommon: 'warm milk', contraindications: 'Diabetes (unsupervised)', manufacturers: MFG_KERALA, description: 'World\'s most-used Rasayana. Anti-aging + immunomodulator. Children to elderly.' + DISC },
  { id: 'f2-dashamoola-rasayanam', slug: 'dashamoola-rasayanam', name: 'Dashamoola Rasayanam', sanskritName: 'दशमूल रसायन', malayalamName: 'ദശമൂല രസായനം', classicalText: 'Sahasrayogam', category: 'lehyam', ingredients: ['Dashamoola','Ashwagandha','Pippali','Cow ghee','Sugar'], primaryUses: ['Postpartum care','Vata Rasayana','Respiratory support','Convalescent recovery'], doshaImpact: DOSHA('v'), typicalDose: '1 tsp twice daily', anupanaCommon: 'warm milk', contraindications: null, manufacturers: MFG_KERALA, description: 'Vata-corrective Rasayana base. Standard postpartum tonic in Kerala.' + DISC },
  { id: 'f2-agasthya-rasayanam', slug: 'agasthya-rasayanam', name: 'Agasthya Rasayanam', sanskritName: 'अगस्त्य रसायन', malayalamName: 'അഗസ്ത്യ രസായനം', classicalText: 'Sahasrayogam', category: 'lehyam', ingredients: ['Agasthya leaf','Pippali','Many Kapha-pacifying herbs','Ghee','Sugar'], primaryUses: ['Chronic asthma','Bronchitis','Recurrent cold','Children\'s respiratory tonic'], doshaImpact: DOSHA('vk'), typicalDose: '1 tsp twice daily', anupanaCommon: 'warm milk or honey', contraindications: null, manufacturers: MFG_KERALA, description: 'Premier respiratory Rasayana — paediatric + adult chronic respiratory disease.' + DISC },
  { id: 'f2-indukantham-leham', slug: 'indukantham-leham', name: 'Indukantham Leham', sanskritName: 'इन्दुकान्तं लेह्य', malayalamName: 'ഇന്ദുകാന്തം ലേഹം', classicalText: 'Sahasrayogam', category: 'lehyam', ingredients: ['Dashamoola','Pippali','Chitraka','Yastimadhu','Cow ghee','Sugar'], primaryUses: ['Convalescent recovery','Postpartum care','Children\'s Agni','Chronic Vata fever'], doshaImpact: DOSHA('v'), typicalDose: '1 tsp twice daily', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Leham form of the Indukantham series — palatable convalescent tonic.' + DISC },
  { id: 'f2-kooshmanda-rasayanam', slug: 'kooshmanda-rasayanam', name: 'Kooshmanda Rasayanam', sanskritName: 'कूष्माण्ड रसायन', malayalamName: 'കൂശ്മാണ്ഡ രസായനം', classicalText: 'Sahasrayogam', category: 'lehyam', ingredients: ['Kushmanda (ash gourd)','Yastimadhu','Pippali','Sugar','Ghee'], primaryUses: ['Chronic cough','Tuberculosis support','Haemoptysis','Bleeding disorders','Pitta wasting'], doshaImpact: DOSHA('vp'), typicalDose: '1-2 tsp twice daily', anupanaCommon: 'warm milk', contraindications: null, manufacturers: MFG_KERALA, description: 'Cooling Vata-Pitta Rasayana for chronic respiratory wasting + bleeding.' + DISC },
  { id: 'f2-vilwadi-leham', slug: 'vilwadi-leham', name: 'Vilwadi Leham', sanskritName: 'विल्वादि लेह्य', malayalamName: 'വില്വാദി ലേഹം', classicalText: 'Sahasrayogam', category: 'lehyam', ingredients: ['Bilva','Triphala','Pippali','Lavanga','Ghee','Sugar'], primaryUses: ['Chronic diarrhoea','IBS-D','Grahani','Postpartum bowel care'], doshaImpact: DOSHA('v'), typicalDose: '1 tsp twice daily', anupanaCommon: 'rice water', contraindications: null, manufacturers: MFG_KERALA, description: 'Palatable form of Vilwadi for chronic diarrhoea — child-friendly.' + DISC },
  { id: 'f2-narasimha-rasayanam', slug: 'narasimha-rasayanam', name: 'Narasimha Rasayanam', sanskritName: 'नारसिंह रसायन', malayalamName: 'നാരസിംഹ രസായനം', classicalText: 'Sahasrayogam', category: 'lehyam', ingredients: ['Narasimha herbs','Triphala','Many Rasayana herbs','Ghee','Sugar'], primaryUses: ['General Rasayana','Anti-aging','Mental + physical strength','Sexual vigour'], doshaImpact: DOSHA('tri'), typicalDose: '1 tsp twice daily', anupanaCommon: 'warm milk', contraindications: null, manufacturers: MFG_KERALA, description: 'Comprehensive Rasayana — adult anti-aging + general restorative.' + DISC },
  { id: 'f2-brahma-rasayanam', slug: 'brahma-rasayanam', name: 'Brahma Rasayanam', sanskritName: 'ब्रह्म रसायन', malayalamName: 'ബ്രഹ്മ രസായനം', classicalText: 'Charaka Samhita', category: 'lehyam', ingredients: ['Amalaki','Haritaki','Many Rasayana herbs','Ghee','Honey'], primaryUses: ['Anti-aging','Mental clarity','General immunity','Longevity Rasayana'], doshaImpact: DOSHA('tri'), typicalDose: '1 tsp twice daily', anupanaCommon: 'warm milk', contraindications: null, manufacturers: MFG_KERALA, description: 'Charaka\'s premier longevity Rasayana — combined Medhya + body-tonic.' + DISC },
  { id: 'f2-madhusnuhi-rasayanam', slug: 'madhusnuhi-rasayanam', name: 'Madhusnuhi Rasayanam', sanskritName: 'मधुस्नुही रसायन', malayalamName: 'മധുസ്നുഹി രസായനം', classicalText: 'Sahasrayogam', category: 'lehyam', ingredients: ['Madhusnuhi (sarsaparilla)','Triphala','Manjishtha','Ghee','Sugar'], primaryUses: ['Syphilis support','Chronic skin disease','Joint-skin Rasayana','Detox'], doshaImpact: DOSHA('p'), typicalDose: '1-2 tsp twice daily', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Specialty Rasayana for chronic Pitta-Rakta + arthritis combinations.' + DISC },
  { id: 'f2-sukumara-leham', slug: 'sukumara-leham', name: 'Sukumara Leham', sanskritName: 'सुकुमार लेह्य', malayalamName: 'സുകുമാര ലേഹം', classicalText: 'Sahasrayogam', category: 'lehyam', ingredients: ['Dashamoola','Eranda','Trikatu','Yastimadhu','Ghee','Sugar'], primaryUses: ['Postpartum care','Female reproductive Rasayana','Menstrual disorders','Vata gynaecology'], doshaImpact: DOSHA('v'), typicalDose: '1 tsp twice daily', anupanaCommon: 'warm milk', contraindications: 'Pregnancy first trimester', manufacturers: MFG_KERALA, description: 'Gentle Vata gynaecological Leham — Sutika + post-Panchakarma tonic.' + DISC },
  { id: 'f2-kantakari-leham', slug: 'kantakari-leham', name: 'Kantakari Leham', sanskritName: 'कण्टकारी लेह्य', malayalamName: 'കണ്ടകാരി ലേഹം', classicalText: 'Sahasrayogam', category: 'lehyam', ingredients: ['Kantakari','Bharangi','Pippali','Yastimadhu','Ghee','Sugar'], primaryUses: ['Bronchial asthma','Chronic cough','Children\'s respiratory tonic'], doshaImpact: DOSHA('vk'), typicalDose: '1 tsp twice daily', anupanaCommon: 'warm water or honey', contraindications: null, manufacturers: MFG_KERALA, description: 'Specific anti-Shwasa Leham — first-line for chronic bronchial asthma.' + DISC },
  { id: 'f2-thaleesapathradi-leham', slug: 'thaleesapathradi-leham', name: 'Thaleesapathradi Leham', sanskritName: 'तालीशपत्रादि लेह्य', malayalamName: 'താലീശപത്രാദി ലേഹം', classicalText: 'Sahasrayogam', category: 'lehyam', ingredients: ['Thaleesapathra','Sitopaladi base','Yastimadhu','Ghee','Sugar'], primaryUses: ['Chronic cough','Bronchitis','Voice hoarseness','Children\'s cough'], doshaImpact: DOSHA('vk'), typicalDose: '1 tsp twice daily', anupanaCommon: 'honey', contraindications: null, manufacturers: MFG_KERALA, description: 'Soothing respiratory Leham — palatable Sitopaladi alternative.' + DISC },
  { id: 'f2-chiruvilwadi-leham', slug: 'chiruvilwadi-leham', name: 'Chiruvilwadi Leham', sanskritName: 'चिरुविल्वादि लेह्य', malayalamName: 'ചിറുവില്വാദി ലേഹം', classicalText: 'Sahasrayogam', category: 'lehyam', ingredients: ['Chiruvilwa','Triphala','Trikatu','Ghee','Sugar'], primaryUses: ['Haemorrhoids','Anal fissure','Chronic constipation'], doshaImpact: DOSHA('v'), typicalDose: '1 tsp twice daily', anupanaCommon: 'warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Leham form of Chiruvilwadi — palatable Arsha care.' + DISC },
  { id: 'f2-vasakot-leham', slug: 'vasakot-leham', name: 'Vasakot Leham', sanskritName: 'वासकोट लेह्य', malayalamName: 'വാസകോട്ട് ലേഹം', classicalText: 'Sahasrayogam', category: 'lehyam', ingredients: ['Vasa (Adhatoda)','Pippali','Yastimadhu','Ghee','Sugar'], primaryUses: ['Cough','Bronchitis','Haemoptysis','Childhood respiratory'], doshaImpact: DOSHA('vp'), typicalDose: '1 tsp twice daily', anupanaCommon: 'honey', contraindications: 'Pregnancy', manufacturers: MFG_KERALA, description: 'Vasa-based respiratory Leham — specific for Pittaja Kasa + Raktapitta cough.' + DISC },
  { id: 'f2-dasamoolarasnadi-leham', slug: 'dasamoolarasnadi-leham', name: 'Dasamoolarasnadi Leham', sanskritName: 'दशमूलरास्नादि लेह्य', malayalamName: 'ദശമൂലരാസ്നാദി ലേഹം', classicalText: 'Sahasrayogam', category: 'lehyam', ingredients: ['Dashamoola','Rasna','Eranda','Ghee','Sugar'], primaryUses: ['Aamavata','Postpartum joint pain','Sciatica','Lumbar disc'], doshaImpact: DOSHA('v'), typicalDose: '1 tsp twice daily', anupanaCommon: 'warm milk', contraindications: null, manufacturers: MFG_KERALA, description: 'Palatable Vata + Aamavata Leham — chronic joint disease.' + DISC },

  // ─── GULIKA / VATI (pills) — 10 ───────────────────────────────────────
  { id: 'f2-vilwadi-gulika', slug: 'vilwadi-gulika', name: 'Vilwadi Gulika', sanskritName: 'विल्वादि गुटिका', malayalamName: 'വില്വാദി ഗുളിക', classicalText: 'Sahasrayogam', category: 'vati', ingredients: ['Bilva','Trikatu','Triphala','Hingu','Lavanga'], primaryUses: ['Fever','Indigestion','Vata-Kapha conditions','Snake-bite first aid (classical use)'], doshaImpact: DOSHA('vk'), typicalDose: '1-2 pills twice daily', anupanaCommon: 'warm water or honey', contraindications: null, manufacturers: MFG_KERALA, description: 'Universal Kerala first-aid Gulika — fever + Agni-mandya + general emergency.' + DISC },
  { id: 'f2-dhanwantaram-gulika', slug: 'dhanwantaram-gulika', name: 'Dhanwantaram Gulika', sanskritName: 'धन्वंतर गुटिका', malayalamName: 'ധന്വന്തരം ഗുളിക', classicalText: 'Sahasrayogam', category: 'vati', ingredients: ['Bala','Ashwagandha','Dashamoola','Many Vata herbs'], primaryUses: ['Postpartum Vata','Convalescent recovery','Sleep disturbance in Vata','Children\'s Vata'], doshaImpact: DOSHA('v'), typicalDose: '1 pill twice daily', anupanaCommon: 'warm milk', contraindications: null, manufacturers: MFG_KERALA, description: 'Vata-corrective Gulika — convenient daily Vata pacifier.' + DISC },
  { id: 'f2-manasamitram-gulika', slug: 'manasamitram-gulika', name: 'Manasamitram Gulika', sanskritName: 'मनसमित्रं गुटिका', malayalamName: 'മനസമിത്രം ഗുളിക', classicalText: 'Sahasrayogam', category: 'vati', ingredients: ['Brahmi','Jatamansi','Shankhapushpi','Pippali','Suvarna bhasma'], primaryUses: ['Severe anxiety','Insomnia','Mania','Epilepsy support','Schizophrenia adjunct'], doshaImpact: DOSHA('v'), typicalDose: '1 pill twice daily', anupanaCommon: 'warm milk or warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Premier Manasika Vati — for serious psychiatric conditions under specialist supervision.' + DISC },
  { id: 'f2-ksheerabala-101-capsule', slug: 'ksheerabala-101-capsule', name: 'Ksheerabala 101 Capsule', sanskritName: 'क्षीरबला १०१ कैप्सूल', malayalamName: 'ക്ഷീരബല 101 ക്യാപ്സ്യൂൾ', classicalText: 'Sahasrayogam', category: 'vati', ingredients: ['Ksheerabala Tailam (101 Avarthi)','Capsule shell'], primaryUses: ['Insomnia','Anxiety','Headache','Migraine','Memory weakness'], doshaImpact: DOSHA('v'), typicalDose: '1 capsule twice daily', anupanaCommon: 'warm milk', contraindications: null, manufacturers: MFG_KERALA, description: 'Encapsulated 101-Avarthi Ksheerabala Tailam — convenient daily Medhya.' + DISC },
  { id: 'f2-varanadi-kashaya-gulika', slug: 'varanadi-kashaya-gulika', name: 'Varanadi Kashaya Gulika', sanskritName: 'वारणादि क्वाथ गुटिका', malayalamName: 'വാരണാദി കഷായ ഗുളിക', classicalText: 'Sahasrayogam', category: 'vati', ingredients: ['Varana','Triphala','Trikatu','Musta'], primaryUses: ['Obesity','Hypothyroidism','Lipid disorders','Lymphatic congestion'], doshaImpact: DOSHA('k'), typicalDose: '1-2 pills twice daily before food', anupanaCommon: 'warm water', contraindications: 'Pregnancy', manufacturers: MFG_KERALA, description: 'Convenient Lekhana Gulika — daily Medo-corrective.' + DISC },
  { id: 'f2-dooshivishari-gulika', slug: 'dooshivishari-gulika', name: 'Dooshivishari Gulika', sanskritName: 'दूषिविषारी गुटिका', malayalamName: 'ദൂഷിവിഷാരി ഗുളിക', classicalText: 'Sahasrayogam', category: 'vati', ingredients: ['Many anti-toxin herbs','Daruharidra','Karpura','Yastimadhu'], primaryUses: ['Chronic allergies','Recurrent infections','Skin allergies','Drug allergies'], doshaImpact: DOSHA('tri'), typicalDose: '1-2 pills twice daily', anupanaCommon: 'warm water with honey', contraindications: null, manufacturers: MFG_KERALA, description: 'Classical anti-Dooshivisha — corrects accumulated low-grade toxicity + chronic allergy.' + DISC },
  { id: 'f2-sooktyn-tablets', slug: 'sooktyn-tablets', name: 'Sooktyn Tablets', sanskritName: '—', malayalamName: 'സൂക്ടിൻ ടാബ്ലെറ്റ്', classicalText: 'Kottakkal AVS Proprietary', category: 'vati', ingredients: ['Avipathi','Sutshekara','Many Pitta-pacifying herbs'], primaryUses: ['Hyperacidity','GERD','Peptic ulcer'], doshaImpact: DOSHA('p'), typicalDose: '1-2 tablets twice daily before food', anupanaCommon: 'warm water', contraindications: null, manufacturers: ['Kottakkal AVS'], description: 'Classical-formulation proprietary Pitta-corrective — convenient daily hyperacidity care.' + DISC },
  { id: 'f2-saptasaram-gulika', slug: 'saptasaram-gulika', name: 'Saptasaram Gulika', sanskritName: 'सप्तसारं गुटिका', malayalamName: 'സപ്തസാരം ഗുളിക', classicalText: 'Sahasrayogam', category: 'vati', ingredients: ['Seven essence herbs','Triphala','Trikatu'], primaryUses: ['Constipation','Indigestion','Mild laxative','IBS-C'], doshaImpact: DOSHA('v'), typicalDose: '1-2 pills at bedtime', anupanaCommon: 'warm water', contraindications: 'Severe diarrhoea', manufacturers: MFG_KERALA, description: 'Gentle daily Anulomana Gulika — milder than Triphala-only.' + DISC },
  { id: 'f2-yogarajaguggulu', slug: 'yogaraja-guggulu', name: 'Yogarajaguggulu', sanskritName: 'योगराज गुग्गुलु', malayalamName: 'യോഗരാജ ഗുഗ്ഗുലു', classicalText: 'Sharangadhara Samhita', category: 'guggulu', ingredients: ['Guggulu','Triphala','Trikatu','Pippalimoola','Chitraka','Vidanga'], primaryUses: ['Aamavata','Rheumatoid arthritis','Osteoarthritis','Chronic Vata','Sciatica'], doshaImpact: DOSHA('vk'), typicalDose: '500 mg-1 g twice daily', anupanaCommon: 'warm water after food', contraindications: 'Pregnancy; bleeding disorders (interacts with warfarin)', manufacturers: MFG_KERALA, description: 'Premier Vata-Kapha Guggulu — first-line for chronic joint disease. NOTE: documented interaction with anticoagulants.' + DISC },
  { id: 'f2-kaishoraguggulu', slug: 'kaishora-guggulu', name: 'Kaishoraguggulu', sanskritName: 'कैशोर गुग्गुलु', malayalamName: 'കൈശോര ഗുഗ്ഗുലു', classicalText: 'Sharangadhara Samhita', category: 'guggulu', ingredients: ['Guggulu','Triphala','Trikatu','Vidanga','Guduchi'], primaryUses: ['Gout','Pitta arthritis','Skin disease with joint involvement','Chronic Pitta-Vata'], doshaImpact: DOSHA('vp'), typicalDose: '500 mg-1 g twice daily', anupanaCommon: 'warm water after food', contraindications: 'Pregnancy; bleeding disorders', manufacturers: MFG_KERALA, description: 'Pitta-pacifying Guggulu — first-line for gout + Pitta-driven joint disease.' + DISC },

  // ─── SPECIAL PREPARATIONS — 5 ─────────────────────────────────────────
  { id: 'f2-ksheerabala-101-avarthi', slug: 'ksheerabala-101-avarthi', name: 'Ksheerabala 101 Avarthi', sanskritName: 'क्षीरबला १०१ आवर्ती', malayalamName: 'ക്ഷീരബല 101 ആവർത്തി', classicalText: 'Sahasrayogam', category: 'taila', ingredients: ['Bala','Cow milk','Sesame oil (101 distillations)'], primaryUses: ['Severe Vata-Pitta','Chronic insomnia','Severe headache','Multiple sclerosis support','Cognitive disorders'], doshaImpact: DOSHA('vp'), typicalDose: '5-10 drops internally + external', anupanaCommon: 'warm milk', contraindications: null, manufacturers: MFG_KERALA, description: '101-time distilled Ksheerabala Tailam — highest potency form. Used for severe chronic Vata-Pitta disorders.' + DISC },
  { id: 'f2-sahacharadi-101-avarthi', slug: 'sahacharadi-101-avarthi', name: 'Sahacharadi 101 Avarthi', sanskritName: 'सहचरादि १०१ आवर्ती', malayalamName: 'സഹചരാദി 101 ആവർത്തി', classicalText: 'Sahasrayogam', category: 'taila', ingredients: ['Sahachara','Bala','Dashamoola','Sesame oil (101 distillations)'], primaryUses: ['Severe sciatica','Lumbar disc','Chronic lower-limb neuropathy','Hemiplegia recovery'], doshaImpact: DOSHA('v'), typicalDose: '5-10 drops internally + external', anupanaCommon: 'warm milk', contraindications: null, manufacturers: MFG_KERALA, description: '101-distilled Sahacharadi Tailam — premium-grade for severe neurological Vata.' + DISC },
  { id: 'f2-balarishtam', slug: 'balarishtam', name: 'Balarishtam', sanskritName: 'बलारिष्ट', malayalamName: 'ബലാരിഷ്ടം', classicalText: 'Sharangadhara Samhita', category: 'arishtam', ingredients: ['Bala','Ashwagandha','Dashamoola','Eranda','Dhataki flower','Guda'], primaryUses: ['Severe Vata disorders','Muscle wasting','Postpartum recovery','Sciatica'], doshaImpact: DOSHA('v'), typicalDose: '15-30 ml twice daily after food', anupanaCommon: 'equal warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Pure-Bala Arishtam — strongest of the Bala-family fermentations.' + DISC },
  { id: 'f2-vasarishtam', slug: 'vasarishtam', name: 'Vasarishtam', sanskritName: 'वासारिष्ट', malayalamName: 'വാസാരിഷ്ടം', classicalText: 'Bhaishajya Ratnavali', category: 'arishtam', ingredients: ['Vasa (Adhatoda)','Triphala','Trikatu','Dhataki flower','Guda'], primaryUses: ['Asthma','Chronic bronchitis','Haemoptysis','Pitta cough'], doshaImpact: DOSHA('vp'), typicalDose: '15-30 ml twice daily after food', anupanaCommon: 'equal warm water', contraindications: 'Pregnancy', manufacturers: MFG_KERALA, description: 'Premier Tamaka Shwasa Arishtam — daily disease-modifying support for bronchial asthma.' + DISC },
  { id: 'f2-amritharishtam', slug: 'amritharishtam', name: 'Amritharishtam', sanskritName: 'अमृतारिष्ट', malayalamName: 'അമൃതാരിഷ്ടം', classicalText: 'Bhaishajya Ratnavali', category: 'arishtam', ingredients: ['Guduchi (Amrita)','Dashamoola','Triphala','Pippali','Dhataki flower','Guda'], primaryUses: ['Chronic fever','Aamavata','Liver disorders','Immune-modulator','Recurrent infections'], doshaImpact: DOSHA('tri'), typicalDose: '15-30 ml twice daily after food', anupanaCommon: 'equal warm water', contraindications: null, manufacturers: MFG_KERALA, description: 'Tridoshic immune-modulating Arishtam — classical anti-fever + Aamavata.' + DISC },
]

export async function seedFormularyV2(prisma: PrismaClient): Promise<{ count: number }> {
  for (const f of F) {
    const { id, ...data } = f
    await prisma.ayurvedaFormulation.upsert({
      where:  { id },
      update: data,
      create: { id, ...data },
    })
  }
  return { count: F.length }
}
