import { PrismaClient, Prisma } from '@prisma/client'

const prisma = new PrismaClient()

// ─── DOCTORS — 20 across all 14 districts ────────────────────────────────
const DOCTORS: Array<Prisma.DoctorCreateInput & { id: string }> = [
  { id: 'seed-doctor-1',  name: 'Dr. Anjali Menon',          specialization: 'Panchakarma',         district: 'Ernakulam',           ccimVerified: true,  qualification: 'BAMS, MD (Ayurveda)',  experienceYears: 18, languages: ['Malayalam','English','Hindi'],         photoUrl: null, availableDays: ['Mon','Tue','Wed','Thu','Fri'], availableForOnline: true,  consultationFee: 800,  profile: 'Specialist in classical Panchakarma and chronic disease management.', bio: 'BAMS from Govt Ayurveda College Trivandrum, MD Panchakarma from Vaidyaratnam P.S. Varier. 18 years of clinical practice across Kerala and Gulf, treating thousands of patients with classical Panchakarma protocols. Chief consultant at Kerala Ayurveda Wellness Centre, Kochi.', contact: '+91-94470-00001', address: 'MG Road, Kochi' },
  { id: 'seed-doctor-2',  name: 'Dr. Rajesh Pillai',         specialization: 'Kayachikitsa',        district: 'Thiruvananthapuram',  ccimVerified: true,  qualification: 'BAMS, MD (Kayachikitsa)', experienceYears: 22, languages: ['Malayalam','English','Tamil'],         photoUrl: null, availableDays: ['Mon','Wed','Fri','Sat'],        availableForOnline: true,  consultationFee: 1000, profile: 'Senior Kayachikitsa physician — diabetes, hypertension, autoimmune disorders.', bio: 'Government Ayurveda Hospital, Trivandrum. 22 years treating chronic lifestyle disorders integrating classical Ayurveda with modern diagnostics. Member, Kerala State Ayurveda Council.',     contact: '+91-94470-00002', address: 'PMG Junction, Trivandrum' },
  { id: 'seed-doctor-3',  name: 'Dr. Priya Krishnan',        specialization: 'Prasuti Tantra',      district: 'Kottayam',            ccimVerified: true,  qualification: 'BAMS, MS (Prasuti)',     experienceYears: 14, languages: ['Malayalam','English'],                  photoUrl: null, availableDays: ['Tue','Thu','Sat'],              availableForOnline: true,  consultationFee: 700,  profile: 'Women\'s health, infertility, postnatal Sutika care.', bio: 'BAMS, MS Prasuti Tantra. 14 years specializing in women\'s reproductive health, infertility treatment using classical Rasayana, and postnatal care (Sutika Paricharya). Female patients only.',                contact: '+91-94470-00003', address: 'KK Road, Kottayam' },
  { id: 'seed-doctor-4',  name: 'Dr. Vinod Nair',            specialization: 'Shalya Tantra',       district: 'Kozhikode',           ccimVerified: true,  qualification: 'BAMS, MS (Shalya)',      experienceYears: 16, languages: ['Malayalam','English','Hindi','Arabic'], photoUrl: null, availableDays: ['Mon','Tue','Wed','Thu'],        availableForOnline: false, consultationFee: 900,  profile: 'Ksharasutra for fistula, hemorrhoids, classical surgical Ayurveda.', bio: 'MS Shalya Tantra. Practicing classical Ksharasutra (medicated thread) therapy for ano-rectal disorders since 2010. Treated 5000+ patients including international visitors.',                                  contact: '+91-94470-00004', address: 'Mavoor Road, Kozhikode' },
  { id: 'seed-doctor-5',  name: 'Dr. Lekshmi Devi',          specialization: 'Kaumarbhritya',       district: 'Thrissur',            ccimVerified: true,  qualification: 'BAMS, MD (Kaumarbhritya)',experienceYears: 12, languages: ['Malayalam','English'],                  photoUrl: null, availableDays: ['Mon','Wed','Fri'],              availableForOnline: true,  consultationFee: 600,  profile: 'Ayurvedic pediatrics — Suvarnaprashana, child immunity, growth.', bio: 'Pediatrician with 12 years experience. Suvarnaprashana camps every Pushya nakshatra. Specialist in childhood asthma, ADHD, and developmental delays.',                                                          contact: '+91-94470-00005', address: 'Kuruppam Road, Thrissur' },
  { id: 'seed-doctor-6',  name: 'Dr. Suresh Kumar',          specialization: 'Manasika',            district: 'Palakkad',            ccimVerified: true,  qualification: 'BAMS, MD (Manas Roga)',  experienceYears: 20, languages: ['Malayalam','English','Tamil'],         photoUrl: null, availableDays: ['Tue','Thu','Sat'],              availableForOnline: true,  consultationFee: 800,  profile: 'Mental health, anxiety, depression — classical Medhya Rasayana approach.', bio: 'MD Manas Roga. 20 years treating anxiety, depression, OCD, insomnia using Shirodhara, Brahmi, Mandukaparni and counseling. Strict patient confidentiality.',                                              contact: '+91-94470-00006', address: 'Sultanpet, Palakkad' },
  { id: 'seed-doctor-7',  name: 'Dr. Meera Sasidharan',      specialization: 'Dravyaguna',          district: 'Alappuzha',           ccimVerified: true,  qualification: 'BAMS, MD (Dravyaguna)',  experienceYears: 9,  languages: ['Malayalam','English'],                  photoUrl: null, availableDays: ['Mon','Wed','Fri','Sat'],        availableForOnline: true,  consultationFee: 500,  profile: 'Pharmacognosy, herb identification, classical formulation expert.', bio: 'PhD candidate, Kerala University. Authored 12 papers on Western Ghats ethnobotany. Consults on rare herb usage and formulation customization.',                                                              contact: '+91-94470-00007', address: 'Beach Road, Alappuzha' },
  { id: 'seed-doctor-8',  name: 'Dr. Arun Varghese',         specialization: 'Roganidana',          district: 'Idukki',              ccimVerified: true,  qualification: 'BAMS, MD (Roganidana)',  experienceYears: 11, languages: ['Malayalam','English'],                  photoUrl: null, availableDays: ['Mon','Tue','Wed','Thu','Fri'], availableForOnline: true,  consultationFee: 600,  profile: 'Diagnosis, Nadi Pariksha, prakriti analysis.', bio: 'Master of Nadi Pariksha trained under Vaidyamadham Cheria Narayanan Namboothiri. Detailed prakriti and vikriti analysis as foundation for any treatment plan.',                                                  contact: '+91-94470-00008', address: 'Munnar-Adimali Road, Idukki' },
  { id: 'seed-doctor-9',  name: 'Dr. Reshma Kunjan',         specialization: 'Shalakya',            district: 'Kollam',              ccimVerified: true,  qualification: 'BAMS, MS (Shalakya)',    experienceYears: 13, languages: ['Malayalam','English','Hindi'],          photoUrl: null, availableDays: ['Tue','Thu','Sat'],              availableForOnline: true,  consultationFee: 700,  profile: 'Eye, ENT, dental — Tarpana, Anjana, Karnapurana.', bio: 'MS Shalakya. Specialist in eye disorders (Tarpana, Anjana), chronic sinusitis (Nasya), and ENT. Treats migraine, refractive errors progression, and dry eye.',                                                  contact: '+91-94470-00009', address: 'Kadappakada, Kollam' },
  { id: 'seed-doctor-10', name: 'Dr. Manoj Pillai',          specialization: 'Rasashastra',         district: 'Kannur',              ccimVerified: true,  qualification: 'BAMS, MD (Rasashastra)', experienceYears: 17, languages: ['Malayalam','English'],                  photoUrl: null, availableDays: ['Mon','Wed','Fri'],              availableForOnline: false, consultationFee: 900,  profile: 'Bhasma preparation, Rasaushadhi, classical mineral medicines.', bio: 'MD Rasashastra. Personally prepares classical Bhasmas and Rasa preparations under traditional pharmacopoeia. 17 years experience.',                                                                          contact: '+91-94470-00010', address: 'Thalassery Road, Kannur' },
  { id: 'seed-doctor-11', name: 'Dr. Bindu Mathew',          specialization: 'Panchakarma',         district: 'Pathanamthitta',      ccimVerified: true,  qualification: 'BAMS, MD (Panchakarma)', experienceYears: 8,  languages: ['Malayalam','English'],                  photoUrl: null, availableDays: ['Mon','Tue','Thu','Fri'],        availableForOnline: true,  consultationFee: 500,  profile: 'Lifestyle disorders, weight management, detoxification.', bio: 'Panchakarma specialist focused on metabolic and lifestyle disorders. Trained at Vaidyaratnam Oushadhasala.',                                                                                                  contact: '+91-94470-00011', address: 'Pathanamthitta Town' },
  { id: 'seed-doctor-12', name: 'Dr. Jayasree Pillai',       specialization: 'Kayachikitsa',        district: 'Wayanad',             ccimVerified: true,  qualification: 'BAMS',                   experienceYears: 25, languages: ['Malayalam','English','Tamil','Kannada'],photoUrl: null, availableDays: ['Mon','Wed','Fri','Sat'],        availableForOnline: true,  consultationFee: 1200, profile: 'Senior tribal medicine consultant, ethnobotanical specialist.', bio: 'BAMS, working with tribal Kerala medicine traditions. 25 years bridging classical Ayurveda and Western Ghats indigenous practices.',                                                                              contact: '+91-94470-00012', address: 'Kalpetta, Wayanad' },
  { id: 'seed-doctor-13', name: 'Dr. Hari Nambiar',          specialization: 'Kayachikitsa',        district: 'Kasaragod',           ccimVerified: true,  qualification: 'BAMS, MD',               experienceYears: 15, languages: ['Malayalam','English','Kannada','Tulu'],photoUrl: null, availableDays: ['Tue','Wed','Thu','Sat'],         availableForOnline: true,  consultationFee: 700,  profile: 'Skin disorders, psoriasis, eczema, vitiligo.', bio: 'MD Kayachikitsa. Specialized practice in chronic skin disorders using Raktamokshana, classical lepa, and dietary corrections.',                                                                                  contact: '+91-94470-00013', address: 'Kasaragod Town' },
  { id: 'seed-doctor-14', name: 'Dr. Sreelatha Namboothiri', specialization: 'Prasuti Tantra',      district: 'Malappuram',          ccimVerified: true,  qualification: 'BAMS, MS',               experienceYears: 19, languages: ['Malayalam','English','Arabic'],         photoUrl: null, availableDays: ['Mon','Wed','Fri'],              availableForOnline: true,  consultationFee: 900,  profile: 'Infertility, PCOD, menstrual disorders, postnatal care.', bio: 'MS Prasuti Tantra. Renowned for infertility treatment and PCOD management. Female patients only. International patient consultations available.',                                                                contact: '+91-94470-00014', address: 'Tirur, Malappuram' },
  { id: 'seed-doctor-15', name: 'Dr. Ramesh Kartha',         specialization: 'Panchakarma',         district: 'Ernakulam',           ccimVerified: true,  qualification: 'BAMS, MD (Panchakarma)', experienceYears: 21, languages: ['Malayalam','English','Hindi'],          photoUrl: null, availableDays: ['Mon','Tue','Wed','Thu','Fri','Sat'], availableForOnline: false, consultationFee: 1500, profile: 'International patient specialist — Karkidaka Chikitsa, Rasayana.', bio: 'Treats international patients (UK, US, Gulf) at his Ernakulam Panchakarma centre. Specializes in 14-21 day rejuvenation programs.',                                                                              contact: '+91-94470-00015', address: 'Marine Drive, Ernakulam' },
  { id: 'seed-doctor-16', name: 'Dr. Asha Pillai',           specialization: 'Kaumarbhritya',       district: 'Thiruvananthapuram',  ccimVerified: true,  qualification: 'BAMS, MD',               experienceYears: 10, languages: ['Malayalam','English','Tamil'],         photoUrl: null, availableDays: ['Mon','Wed','Sat'],              availableForOnline: true,  consultationFee: 500,  profile: 'Pediatric Ayurveda, autism, learning disorders.', bio: 'Kaumarbhritya specialist with focus on neurodevelopmental disorders, autism spectrum, ADHD using Medhya Rasayana and Yoga.',                                                                                  contact: '+91-94470-00016', address: 'Sasthamangalam, Trivandrum' },
  { id: 'seed-doctor-17', name: 'Dr. Sunil George',          specialization: 'Manasika',            district: 'Kottayam',            ccimVerified: true,  qualification: 'BAMS, MD',               experienceYears: 13, languages: ['Malayalam','English'],                  photoUrl: null, availableDays: ['Tue','Thu','Sat'],              availableForOnline: true,  consultationFee: 800,  profile: 'Insomnia, depression, addiction recovery.', bio: 'MD Manas Roga. Holistic approach combining Shirodhara, Brahmi, counseling and yoga for stress, insomnia, and addiction recovery.',                                                                            contact: '+91-94470-00017', address: 'CMS Road, Kottayam' },
  { id: 'seed-doctor-18', name: 'Dr. Divya Rajan',           specialization: 'Shalakya',            district: 'Thrissur',            ccimVerified: true,  qualification: 'BAMS, MS (Shalakya)',    experienceYears: 7,  languages: ['Malayalam','English'],                  photoUrl: null, availableDays: ['Mon','Wed','Fri'],              availableForOnline: true,  consultationFee: 600,  profile: 'Computer vision syndrome, dry eye, headache.', bio: 'MS Shalakya. Modern lifestyle eye disorders — computer vision syndrome, refractive issues, chronic headache and migraine via Tarpana and Nasya.',                                                                contact: '+91-94470-00018', address: 'Round North, Thrissur' },
  { id: 'seed-doctor-19', name: 'Dr. Krishnakumar V',        specialization: 'Kayachikitsa',        district: 'Ernakulam',           ccimVerified: true,  qualification: 'BAMS, MD',               experienceYears: 16, languages: ['Malayalam','English','Hindi','Arabic'], photoUrl: null, availableDays: ['Mon','Tue','Thu','Fri','Sat'], availableForOnline: true,  consultationFee: 1100, profile: 'Diabetes, cardiovascular, kidney disorders.', bio: 'Senior Kayachikitsa physician specializing in metabolic syndrome, diabetes complications, and chronic kidney disease integrative care.',                                                                       contact: '+91-94470-00019', address: 'Kaloor, Kochi' },
  { id: 'seed-doctor-20', name: 'Dr. Geetha Nair',           specialization: 'Panchakarma',         district: 'Alappuzha',           ccimVerified: true,  qualification: 'BAMS, MD (Panchakarma)', experienceYears: 14, languages: ['Malayalam','English'],                  photoUrl: null, availableDays: ['Mon','Wed','Fri','Sat'],        availableForOnline: true,  consultationFee: 700,  profile: 'Joint pain, arthritis, spondylosis — classical kati basti, janu basti.', bio: 'Specializes in musculoskeletal disorders using Panchakarma, kati basti, janu basti, and pizhichil. 14 years treating arthritis, lumbar issues.',                                                                contact: '+91-94470-00020', address: 'Mullakkal, Alappuzha' },
]

// ─── HOSPITALS — 10 ───────────────────────────────────────────────────────
const HOSPITALS: Array<Prisma.HospitalCreateInput & { id: string }> = [
  { id: 'seed-hospital-1',  name: 'Govt Ayurveda Hospital Thiruvananthapuram', type: 'hospital',    district: 'Thiruvananthapuram', ccimVerified: true,  ayushCertified: true,  panchakarma: true,  nabh: false, establishedYear: 1947, services: ['Panchakarma','Kayachikitsa','Prasuti','Kaumarbhritya','Shalya','Shalakya'],                                          profile: 'Premier government Ayurveda hospital, 250 beds, attached to Govt Ayurveda College.',  contact: '+91-471-2461-094', address: 'PMG Junction, Thiruvananthapuram', latitude: 8.5071, longitude: 76.9486 },
  { id: 'seed-hospital-2',  name: 'Vaidyaratnam P.S. Varier Ayurveda Hospital', type: 'hospital',   district: 'Malappuram',         ccimVerified: true,  ayushCertified: true,  panchakarma: true,  nabh: true,  establishedYear: 1902, services: ['Panchakarma','Kayachikitsa','Rasayana','International Patients','In-patient Care'],                                profile: 'Heritage Kerala Ayurveda institution founded by P.S. Varier — 120+ years of unbroken tradition.', contact: '+91-494-2742-216', address: 'Kottakkal, Malappuram',          latitude: 10.9989, longitude: 76.0035 },
  { id: 'seed-hospital-3',  name: 'Kerala Ayurveda Wellness Centre',           type: 'panchakarma', district: 'Ernakulam',          ccimVerified: true,  ayushCertified: true,  panchakarma: true,  nabh: true,  establishedYear: 1992, services: ['Panchakarma','Rejuvenation','Stress Relief','International Packages','Yoga'],                                       profile: 'NABH-accredited 24-room Panchakarma resort. International clientele.',               contact: '+91-484-2345-678', address: 'Kakkanad, Kochi',               latitude: 10.0289, longitude: 76.3416 },
  { id: 'seed-hospital-4',  name: 'Somatheeram Ayurveda Resort',                type: 'wellness',    district: 'Thiruvananthapuram', ccimVerified: false, ayushCertified: true,  panchakarma: true,  nabh: false, establishedYear: 1985, services: ['Panchakarma','Yoga','Meditation','Beach Resort','International Packages'],                                       profile: 'World\'s first Ayurveda resort — beachfront Panchakarma packages from 7-28 days.',  contact: '+91-471-2266-501', address: 'Chowara Beach, Trivandrum',     latitude: 8.3697, longitude: 76.9755 },
  { id: 'seed-hospital-5',  name: 'Kairali Ayurvedic Centre',                  type: 'panchakarma', district: 'Palakkad',           ccimVerified: false, ayushCertified: true,  panchakarma: true,  nabh: false, establishedYear: 1989, services: ['Panchakarma','Kerala Special Treatments','Yoga','Spa'],                                                            profile: 'Award-winning healing village in Palakkad foothills. AYUSH 5-star certified.',       contact: '+91-491-2522-555', address: 'Olassery, Palakkad',            latitude: 10.7867, longitude: 76.6548 },
  { id: 'seed-hospital-6',  name: 'Govt Ayurveda Hospital Tripunithura',       type: 'hospital',    district: 'Ernakulam',          ccimVerified: true,  ayushCertified: true,  panchakarma: true,  nabh: false, establishedYear: 1957, services: ['Panchakarma','Kayachikitsa','OPD','In-patient Care','Free Treatment'],                                            profile: 'Government hospital with subsidized/free Ayurveda care and 150 beds.',               contact: '+91-484-2778-024', address: 'Tripunithura, Kochi',           latitude: 9.9476, longitude: 76.3496 },
  { id: 'seed-hospital-7',  name: 'Sitaram Ayurveda Hospital',                  type: 'hospital',    district: 'Thrissur',           ccimVerified: true,  ayushCertified: true,  panchakarma: true,  nabh: true,  establishedYear: 1921, services: ['Panchakarma','Kayachikitsa','Manufacturing','Research'],                                                            profile: 'Century-old Thrissur institution — hospital + classical pharmacy combined.',         contact: '+91-487-2389-411', address: 'Kuruppam Road, Thrissur',       latitude: 10.5276, longitude: 76.2144 },
  { id: 'seed-hospital-8',  name: 'Ayurvedagram Heritage Wellness Centre',     type: 'wellness',    district: 'Kottayam',           ccimVerified: false, ayushCertified: true,  panchakarma: true,  nabh: false, establishedYear: 2007, services: ['Heritage Cottages','Panchakarma','Yoga','Cultural Programs'],                                                      profile: 'Boutique heritage village — cottage stays + Panchakarma + cultural immersion.',      contact: '+91-481-2469-009', address: 'Kumarakom, Kottayam',           latitude: 9.6178, longitude: 76.4274 },
  { id: 'seed-hospital-9',  name: 'PNNM Ayurveda Medical College Hospital',     type: 'hospital',    district: 'Pathanamthitta',     ccimVerified: true,  ayushCertified: true,  panchakarma: true,  nabh: false, establishedYear: 1972, services: ['Teaching Hospital','Panchakarma','Kayachikitsa','Prasuti','Kaumarbhritya'],                                       profile: 'Pampady Mandiram — teaching hospital affiliated with Kerala University.',           contact: '+91-468-2222-777', address: 'Cheruthuruthy, Pathanamthitta', latitude: 9.2647, longitude: 76.7867 },
  { id: 'seed-hospital-10', name: 'Athreya Ayurvedic Hospital Wayanad',         type: 'panchakarma', district: 'Wayanad',            ccimVerified: true,  ayushCertified: true,  panchakarma: true,  nabh: false, establishedYear: 2003, services: ['Panchakarma','Tribal Medicine','Spice Plantation Stay','Yoga'],                                                   profile: 'Wayanad highland Ayurveda — tribal herbs, spice plantation immersion.',              contact: '+91-493-6271-555', address: 'Sulthan Bathery, Wayanad',      latitude: 11.6667, longitude: 76.2667 },
]

// ─── HERBS — 50 from classical Ayurveda + Kerala Western Ghats ───────────
type HerbSeed = { id: string; name: string; sanskrit: string; english: string; malayalam: string; rasa: string; guna: string; virya: string; vipaka: string; description: string; uses: string }
const HERBS: HerbSeed[] = [
  { id: 'h-ashwagandha',  name: 'Ashwagandha',  sanskrit: 'अश्वगन्धा',     english: 'Winter Cherry',         malayalam: 'അമുക്കുരം',         rasa: 'tikta, kashaya, madhura', guna: 'laghu, snigdha', virya: 'ushna',  vipaka: 'madhura', description: 'Withania somnifera. Adaptogenic root, classical Rasayana.',                              uses: 'Stress, insomnia, fatigue, infertility, immunity, neurodegeneration.' },
  { id: 'h-brahmi',       name: 'Brahmi',       sanskrit: 'ब्राह्मी',        english: 'Water Hyssop',          malayalam: 'ബ്രാഹ്മി',          rasa: 'tikta, kashaya, madhura', guna: 'laghu, sara',    virya: 'sheeta', vipaka: 'madhura', description: 'Bacopa monnieri. Classical Medhya Rasayana for cognition.',                                uses: 'Memory, anxiety, ADHD, epilepsy, hair growth (oil).' },
  { id: 'h-tulsi',        name: 'Tulsi',        sanskrit: 'तुलसी',          english: 'Holy Basil',            malayalam: 'തുളസി',            rasa: 'tikta, katu',             guna: 'laghu, ruksha',  virya: 'ushna',  vipaka: 'katu',    description: 'Ocimum tenuiflorum. Sacred plant of every Kerala household.',                              uses: 'Cough, cold, fever, immunity, respiratory disorders, mosquito repellent.' },
  { id: 'h-haritaki',     name: 'Haritaki',     sanskrit: 'हरीतकी',         english: 'Chebulic Myrobalan',    malayalam: 'കടുക്ക',           rasa: 'kashaya (predominant) + 5 others', guna: 'laghu, ruksha', virya: 'ushna', vipaka: 'madhura', description: 'Terminalia chebula. The "king of medicines" — one of Triphala constituents.',          uses: 'Constipation, digestive disorders, parasites, eye health, rejuvenation.' },
  { id: 'h-amalaki',      name: 'Amalaki',      sanskrit: 'आमलकी',          english: 'Indian Gooseberry',     malayalam: 'നെല്ലിക്ക',         rasa: '5 rasas (no lavana)',     guna: 'laghu, ruksha',  virya: 'sheeta', vipaka: 'madhura', description: 'Phyllanthus emblica. Highest natural Vitamin C source. Triphala constituent.',          uses: 'Acidity, hair fall, skin glow, diabetes, immunity, anti-aging Rasayana.' },
  { id: 'h-bibhitaki',    name: 'Bibhitaki',    sanskrit: 'विभीतकी',        english: 'Belleric Myrobalan',    malayalam: 'താന്നിക്ക',          rasa: 'kashaya',                  guna: 'laghu, ruksha',  virya: 'ushna',  vipaka: 'madhura', description: 'Terminalia bellirica. Third pillar of Triphala. Specific to Kapha.',                       uses: 'Cough, asthma, hair, voice, eye disorders.' },
  { id: 'h-guggulu',      name: 'Guggulu',      sanskrit: 'गुग्गुलु',         english: 'Indian Bdellium',       malayalam: 'ഗുഗ്ഗുലു',          rasa: 'tikta, katu, kashaya',    guna: 'laghu, ruksha',  virya: 'ushna',  vipaka: 'katu',    description: 'Commiphora wightii. Resin of the desert tree, base for Yoga-raja Guggulu etc.',           uses: 'Arthritis, obesity, lipid disorders, fistula (with Kshara), ulcers.' },
  { id: 'h-shatavari',    name: 'Shatavari',    sanskrit: 'शतावरी',         english: 'Wild Asparagus',         malayalam: 'ശതാവരി',           rasa: 'madhura, tikta',          guna: 'guru, snigdha',  virya: 'sheeta', vipaka: 'madhura', description: 'Asparagus racemosus. The "queen of herbs" for women\'s health.',                          uses: 'Lactation, infertility, menopause, peptic ulcer, pitta disorders.' },
  { id: 'h-yashtimadhu',  name: 'Yashtimadhu',  sanskrit: 'यष्टिमधु',         english: 'Licorice',              malayalam: 'യഷ്ടിമധു',          rasa: 'madhura',                  guna: 'guru, snigdha',  virya: 'sheeta', vipaka: 'madhura', description: 'Glycyrrhiza glabra. Sweet root, classical demulcent.',                                    uses: 'Cough, sore throat, peptic ulcer, eye health, complexion.' },
  { id: 'h-triphala',     name: 'Triphala',     sanskrit: 'त्रिफला',          english: 'Three Fruits',          malayalam: 'ത്രിഫല',           rasa: '5 rasas',                  guna: 'laghu, ruksha',  virya: 'tridosha-balancing', vipaka: 'madhura', description: 'Combination of Haritaki + Amalaki + Bibhitaki. Tridosha rasayana.',                       uses: 'Constipation, digestion, eye health, rejuvenation, weight management.' },
  { id: 'h-neem',         name: 'Neem',         sanskrit: 'निम्ब',           english: 'Margosa',                malayalam: 'വേപ്പ്',            rasa: 'tikta, kashaya',          guna: 'laghu, ruksha',  virya: 'sheeta', vipaka: 'katu',    description: 'Azadirachta indica. Bitter detoxifier of Kerala backyards.',                              uses: 'Skin diseases, diabetes, parasites, fever, dental health.' },
  { id: 'h-shankhpushpi', name: 'Shankhpushpi', sanskrit: 'शङ्खपुष्पी',      english: 'Aloe Weed',              malayalam: 'ശംഖുപുഷ്പം',        rasa: 'tikta, kashaya',          guna: 'snigdha, picchila', virya: 'sheeta', vipaka: 'madhura', description: 'Convolvulus pluricaulis. Classical Medhya Rasayana.',                                      uses: 'Memory, anxiety, sleep, epilepsy, rejuvenation of nervous system.' },
  { id: 'h-mandukaparni', name: 'Mandukaparni', sanskrit: 'मण्डूकपर्णी',    english: 'Indian Pennywort',       malayalam: 'കുടകൻ',            rasa: 'tikta',                    guna: 'laghu, sara',    virya: 'sheeta', vipaka: 'madhura', description: 'Centella asiatica. "Brahmi" of South India, key Medhya plant.',                            uses: 'Memory, skin disorders, wound healing, longevity.' },
  { id: 'h-vacha',        name: 'Vacha',        sanskrit: 'वचा',           english: 'Sweet Flag',             malayalam: 'വയമ്പ്',           rasa: 'katu, tikta',              guna: 'laghu, tikshna', virya: 'ushna',  vipaka: 'katu',    description: 'Acorus calamus. Speech and intellect classical herb.',                                   uses: 'Speech delay, epilepsy, sinusitis, mental clarity.' },
  { id: 'h-jatamansi',    name: 'Jatamansi',    sanskrit: 'जटामांसी',       english: 'Spikenard',              malayalam: 'ജടാമാംസി',          rasa: 'tikta, kashaya, madhura', guna: 'laghu, snigdha', virya: 'sheeta', vipaka: 'katu',    description: 'Nardostachys jatamansi. Aromatic Himalayan root used in Kerala formulations.',           uses: 'Insomnia, anxiety, hysteria, headache, skin disorders.' },
  { id: 'h-arjuna',       name: 'Arjuna',       sanskrit: 'अर्जुन',          english: 'Arjun Tree',             malayalam: 'നീർമരുത്',          rasa: 'kashaya',                  guna: 'laghu, ruksha',  virya: 'sheeta', vipaka: 'katu',    description: 'Terminalia arjuna. Bark — classical cardiac tonic.',                                       uses: 'Heart disease, hypertension, cholesterol, fractures.' },
  { id: 'h-punarnava',    name: 'Punarnava',    sanskrit: 'पुनर्नवा',        english: 'Hogweed',                malayalam: 'തവിഴാമ',            rasa: 'tikta, katu',              guna: 'laghu, ruksha',  virya: 'ushna',  vipaka: 'madhura', description: 'Boerhavia diffusa. "Renewer" — classical diuretic.',                                       uses: 'Edema, kidney disease, anemia, jaundice.' },
  { id: 'h-bhumyamalaki', name: 'Bhumyamalaki', sanskrit: 'भूम्यामलकी',      english: 'Stonebreaker',           malayalam: 'കീഴാർനെല്ലി',        rasa: 'tikta, kashaya',          guna: 'laghu, ruksha',  virya: 'sheeta', vipaka: 'madhura', description: 'Phyllanthus niruri. Liver herb par excellence.',                                          uses: 'Hepatitis, jaundice, liver disorders, kidney stones, diabetes.' },
  { id: 'h-kalmegh',      name: 'Kalmegh',      sanskrit: 'किरातिक्ता',     english: 'King of Bitters',        malayalam: 'നിലവേപ്പ്',          rasa: 'tikta',                    guna: 'laghu, ruksha',  virya: 'sheeta', vipaka: 'katu',    description: 'Andrographis paniculata. Most bitter herb — classical fever remedy.',                      uses: 'Fever, liver disorders, immunity, infections.' },
  { id: 'h-vasaka',       name: 'Vasaka',       sanskrit: 'वासा',           english: 'Malabar Nut',            malayalam: 'ആടലോടകം',          rasa: 'tikta, kashaya',          guna: 'laghu, ruksha',  virya: 'sheeta', vipaka: 'katu',    description: 'Justicia adhatoda. Kerala respiratory herb.',                                              uses: 'Cough, asthma, bronchitis, blood disorders.' },
  { id: 'h-kantakari',    name: 'Kantakari',    sanskrit: 'कण्टकारी',       english: 'Yellow-Berried Nightshade', malayalam: 'കണ്ടകാരി',         rasa: 'tikta, katu',              guna: 'laghu, ruksha',  virya: 'ushna',  vipaka: 'katu',    description: 'Solanum xanthocarpum. Dasamoola constituent.',                                            uses: 'Cough, asthma, throat disorders, fever.' },
  { id: 'h-bilva',        name: 'Bilva',        sanskrit: 'बिल्व',           english: 'Bael',                   malayalam: 'കൂവളം',            rasa: 'kashaya, tikta',          guna: 'laghu, ruksha',  virya: 'ushna',  vipaka: 'katu',    description: 'Aegle marmelos. Sacred tree, Dasamoola constituent.',                                     uses: 'Diarrhea, dysentery, IBS, diabetes.' },
  { id: 'h-gokshura',     name: 'Gokshura',     sanskrit: 'गोक्षुर',         english: 'Caltrops',                malayalam: 'നെരുഞ്ഞിൽ',          rasa: 'madhura',                  guna: 'guru, snigdha',  virya: 'sheeta', vipaka: 'madhura', description: 'Tribulus terrestris. Urinary and reproductive tonic.',                                     uses: 'Urinary disorders, kidney stones, male reproductive health, edema.' },
  { id: 'h-kapikacchu',   name: 'Kapikacchu',   sanskrit: 'कपिकच्छु',        english: 'Velvet Bean',             malayalam: 'നായ്ക്കുരണ',         rasa: 'madhura, tikta',          guna: 'guru, snigdha',  virya: 'ushna',  vipaka: 'madhura', description: 'Mucuna pruriens. Natural source of L-DOPA.',                                                uses: 'Parkinson\'s, infertility, nervous disorders, vitality.' },
  { id: 'h-musta',        name: 'Musta',        sanskrit: 'मुस्ता',           english: 'Nut Grass',               malayalam: 'മുത്തങ്ങ',          rasa: 'tikta, katu, kashaya',    guna: 'laghu, ruksha',  virya: 'sheeta', vipaka: 'katu',    description: 'Cyperus rotundus. Common grass with profound digestive action.',                          uses: 'Diarrhea, fever, lactation, menstrual disorders.' },
  { id: 'h-pippali',      name: 'Pippali',      sanskrit: 'पिप्पली',         english: 'Long Pepper',             malayalam: 'തിപ്പലി',           rasa: 'katu',                     guna: 'laghu, snigdha', virya: 'ushna (anushna)', vipaka: 'madhura', description: 'Piper longum. Trikatu constituent, Yogavahi.',                                         uses: 'Cough, asthma, indigestion, low metabolism, anemia.' },
  { id: 'h-shunthi',      name: 'Shunthi',      sanskrit: 'शुण्ठी',           english: 'Dry Ginger',              malayalam: 'ചുക്ക്',            rasa: 'katu',                     guna: 'laghu, snigdha', virya: 'ushna',  vipaka: 'madhura', description: 'Zingiber officinale (dried). Trikatu constituent, universal medicine.',                  uses: 'Indigestion, nausea, cough, joint pain, motion sickness.' },
  { id: 'h-marich',       name: 'Maricha',      sanskrit: 'मरिच',           english: 'Black Pepper',            malayalam: 'കുരുമുളക്',         rasa: 'katu',                     guna: 'laghu, tikshna', virya: 'ushna',  vipaka: 'katu',    description: 'Piper nigrum. Trikatu constituent, "king of spices".',                                    uses: 'Indigestion, cough, cold, sinusitis, fever.' },
  { id: 'h-haridra',      name: 'Haridra',      sanskrit: 'हरिद्रा',          english: 'Turmeric',                malayalam: 'മഞ്ഞൾ',            rasa: 'katu, tikta',              guna: 'laghu, ruksha',  virya: 'ushna',  vipaka: 'katu',    description: 'Curcuma longa. The golden herb — antiseptic, anti-inflammatory.',                         uses: 'Skin diseases, diabetes, wound healing, allergies, liver health.' },
  { id: 'h-daruharidra',  name: 'Daruharidra',  sanskrit: 'दारुहरिद्रा',     english: 'Indian Berberis',         malayalam: 'മരമഞ്ഞൾ',           rasa: 'tikta, kashaya',          guna: 'laghu, ruksha',  virya: 'ushna',  vipaka: 'katu',    description: 'Berberis aristata. Bark and root — bitter cleanser.',                                     uses: 'Eye disorders, skin diseases, diabetes, jaundice.' },
  { id: 'h-katuka',       name: 'Katuka',       sanskrit: 'कटुकी',          english: 'Picrorhiza',              malayalam: 'കടുകരോഹിണി',         rasa: 'tikta',                    guna: 'laghu, ruksha',  virya: 'sheeta', vipaka: 'katu',    description: 'Picrorhiza kurroa. Himalayan bitter for liver.',                                          uses: 'Liver disorders, jaundice, fever, asthma.' },
  { id: 'h-bhringraj',    name: 'Bhringaraj',   sanskrit: 'भृङ्गराज',        english: 'False Daisy',             malayalam: 'കയ്യോന്നി',          rasa: 'katu, tikta',              guna: 'laghu, ruksha',  virya: 'ushna',  vipaka: 'katu',    description: 'Eclipta alba. The hair herb of Kerala.',                                                  uses: 'Hair fall, premature greying, liver disorders, eye health.' },
  { id: 'h-aragvadha',    name: 'Aragvadha',    sanskrit: 'आरग्वध',         english: 'Golden Shower',           malayalam: 'കണിക്കൊന്ന',          rasa: 'madhura',                  guna: 'guru, snigdha',  virya: 'sheeta', vipaka: 'madhura', description: 'Cassia fistula. The state flower of Kerala, gentle laxative.',                            uses: 'Constipation, skin diseases, fever (children/elderly).' },
  { id: 'h-asanam',       name: 'Asanam',       sanskrit: 'असन',            english: 'Indian Kino Tree',        malayalam: 'വേങ്ങ',             rasa: 'tikta, kashaya',          guna: 'laghu, ruksha',  virya: 'sheeta', vipaka: 'katu',    description: 'Pterocarpus marsupium. "Vijayasara" of Ayurveda.',                                        uses: 'Diabetes, obesity, skin diseases, blood disorders.' },
  { id: 'h-khadira',      name: 'Khadira',      sanskrit: 'खदिर',           english: 'Cutch Tree',              malayalam: 'കരിങ്ങാലി',          rasa: 'tikta, kashaya',          guna: 'laghu, ruksha',  virya: 'sheeta', vipaka: 'katu',    description: 'Acacia catechu. Heartwood used for Khadiradi Vati.',                                       uses: 'Skin diseases, dental, diabetes, throat disorders.' },
  { id: 'h-chandana',     name: 'Chandana',     sanskrit: 'चन्दन',          english: 'White Sandalwood',         malayalam: 'ചന്ദനം',            rasa: 'tikta, madhura',          guna: 'laghu, snigdha', virya: 'sheeta', vipaka: 'katu',    description: 'Santalum album. Cooling, fragrant heartwood.',                                            uses: 'Skin disorders, burning sensations, urinary disorders, fevers.' },
  { id: 'h-vidanga',      name: 'Vidanga',      sanskrit: 'विडङ्ग',          english: 'False Black Pepper',       malayalam: 'വയ്മ്പിലക',          rasa: 'katu, kashaya',          guna: 'laghu, ruksha',  virya: 'ushna',  vipaka: 'katu',    description: 'Embelia ribes. Classical anti-parasitic herb.',                                           uses: 'Intestinal worms, indigestion, obesity.' },
  { id: 'h-shyama-tulasi',name: 'Krishna Tulsi', sanskrit: 'कृष्णतुलसी',     english: 'Black Holy Basil',         malayalam: 'കൃഷ്ണതുളസി',         rasa: 'tikta, katu',              guna: 'laghu, ruksha',  virya: 'ushna',  vipaka: 'katu',    description: 'Ocimum sanctum (purple variety). More potent than green tulsi.',                          uses: 'Stronger respiratory action, immunity, fever.' },
  { id: 'h-amritha',      name: 'Amritha',      sanskrit: 'अमृता',           english: 'Tinospora',                 malayalam: 'അമൃത്',             rasa: 'tikta, kashaya',          guna: 'guru',           virya: 'ushna',  vipaka: 'madhura', description: 'Tinospora cordifolia ("Guduchi"). The "ambrosia" — top Rasayana.',                          uses: 'Fever (esp. chronic/recurrent), immunity, diabetes, liver disorders.' },
  { id: 'h-rasna',        name: 'Rasna',        sanskrit: 'रास्ना',          english: 'Pluchea',                   malayalam: 'അരത്ത',              rasa: 'tikta',                    guna: 'guru',           virya: 'ushna',  vipaka: 'katu',    description: 'Pluchea lanceolata. Vata herb par excellence.',                                            uses: 'Arthritis, neurological disorders, joint pain, indigestion.' },
  { id: 'h-erandam',      name: 'Eranda',       sanskrit: 'एरण्ड',           english: 'Castor',                    malayalam: 'ആവണക്ക്',           rasa: 'madhura, katu, kashaya',  guna: 'guru, snigdha',  virya: 'ushna',  vipaka: 'madhura', description: 'Ricinus communis. Root and oil widely used in Kerala.',                                  uses: 'Constipation, arthritis (oil), Vata disorders.' },
  { id: 'h-trikatu',      name: 'Trikatu',      sanskrit: 'त्रिकटु',          english: 'Three Pungents',            malayalam: 'ത്രികടു',           rasa: 'katu',                     guna: 'laghu, ruksha',  virya: 'ushna',  vipaka: 'katu',    description: 'Pippali + Maricha + Shunthi. Powerful Yogavahi — enhances bioavailability.',              uses: 'Indigestion, low metabolism, cough, obesity, Kapha disorders.' },
  { id: 'h-chyawanprash', name: 'Chyawanprash',  sanskrit: 'च्यवनप्राश',     english: 'Rasayana Avaleha',          malayalam: 'ച്യവനപ്രാശം',        rasa: '5 rasas',                  guna: 'guru, snigdha',  virya: 'ushna',  vipaka: 'madhura', description: 'Classical Rasayana with 50+ herbs in Amla base.',                                          uses: 'Immunity, vitality, respiratory health, anti-aging.' },
  { id: 'h-kumari',       name: 'Kumari',        sanskrit: 'कुमारी',         english: 'Aloe Vera',                  malayalam: 'കറ്റാർവാഴ',          rasa: 'tikta',                    guna: 'guru, snigdha',  virya: 'sheeta', vipaka: 'katu',    description: 'Aloe barbadensis. Kerala backyard plant, Pitta pacifier.',                                uses: 'Liver, skin, menstrual disorders, constipation, burns.' },
  { id: 'h-jirakam',      name: 'Jiraka',        sanskrit: 'जीरक',           english: 'Cumin',                       malayalam: 'ജീരകം',             rasa: 'katu',                     guna: 'laghu, ruksha',  virya: 'ushna',  vipaka: 'katu',    description: 'Cuminum cyminum. Kitchen spice with Ayurvedic depth.',                                    uses: 'Indigestion, lactation, diarrhea, fever.' },
  { id: 'h-dhanyaka',     name: 'Dhanyaka',      sanskrit: 'धान्यक',         english: 'Coriander',                   malayalam: 'കൊത്തമ്പാലരി',       rasa: 'tikta, kashaya, madhura', guna: 'laghu, snigdha', virya: 'ushna (anushna)', vipaka: 'madhura', description: 'Coriandrum sativum. Cooling spice + medicine.',                                       uses: 'Thirst, fever, urinary disorders, indigestion.' },
  { id: 'h-mustadi',      name: 'Methi',         sanskrit: 'मेथिका',         english: 'Fenugreek',                   malayalam: 'ഉലുവ',             rasa: 'tikta',                    guna: 'snigdha',        virya: 'ushna',  vipaka: 'katu',    description: 'Trigonella foenum-graecum. Kitchen-shelf medicine.',                                       uses: 'Diabetes, lactation, joint pain, cholesterol.' },
  { id: 'h-saindhava',    name: 'Saindhava Lavana', sanskrit: 'सैन्धव लवण', english: 'Rock Salt',                  malayalam: 'ഇന്തുപ്പ്',           rasa: 'lavana (mild)',            guna: 'laghu, snigdha', virya: 'sheeta', vipaka: 'madhura', description: 'Himalayan rock salt — only salt allowed daily in Ayurveda.',                              uses: 'Digestion, all dosha-balancing, electrolyte.' },
  { id: 'h-bala',         name: 'Bala',          sanskrit: 'बला',            english: 'Country Mallow',              malayalam: 'കുറുന്തോട്ടി',       rasa: 'madhura',                  guna: 'guru, snigdha',  virya: 'sheeta', vipaka: 'madhura', description: 'Sida cordifolia. Strength-giving herb, Bala Taila base.',                                  uses: 'Vata disorders, debility, paralysis, neurological disorders.' },
  { id: 'h-shilajit',     name: 'Shilajit',      sanskrit: 'शिलाजतु',        english: 'Mineral Pitch',                malayalam: 'ശിലാജിതു',           rasa: 'katu, tikta, kashaya',    guna: 'laghu, ruksha',  virya: 'ushna',  vipaka: 'katu',    description: 'Asphaltum. Himalayan mineral exudate, classical Rasayana.',                                uses: 'Diabetes, urinary, sexual debility, anemia, energy.' },
]

// ─── COLLEGES — 10 ───────────────────────────────────────────────────────
const COLLEGES: Array<Prisma.MedicalCollegeCreateInput & { id: string }> = [
  { id: 'seed-college-1',  name: 'Govt Ayurveda College Thiruvananthapuram',                  district: 'Thiruvananthapuram', type: 'ayurveda',  profile: 'Oldest Ayurveda college in Kerala, est. 1889. PG and PhD courses.',                            contact: '+91-471-2460-190', address: 'PMG Junction, Thiruvananthapuram' },
  { id: 'seed-college-2',  name: 'Govt Ayurveda College Tripunithura',                         district: 'Ernakulam',          type: 'ayurveda',  profile: 'Government BAMS + MD college, attached to Govt Ayurveda Hospital Tripunithura.',              contact: '+91-484-2778-024', address: 'Tripunithura, Kochi' },
  { id: 'seed-college-3',  name: 'Govt Ayurveda College Kannur',                              district: 'Kannur',             type: 'ayurveda',  profile: 'BAMS college serving North Malabar.',                                                          contact: '+91-497-2700-060', address: 'Pariyaram, Kannur' },
  { id: 'seed-college-4',  name: 'Vaidyaratnam P.S. Varier Ayurveda College',                   district: 'Malappuram',         type: 'ayurveda',  profile: 'Heritage Ayurveda college at Kottakkal — BAMS + MD + PhD. Kerala\'s top private Ayurveda college.', contact: '+91-494-2742-620', address: 'Kottakkal, Malappuram' },
  { id: 'seed-college-5',  name: 'Amrita School of Ayurveda',                                  district: 'Kollam',             type: 'ayurveda',  profile: 'BAMS + MD + Integrative Medicine programs. Mata Amritanandamayi Math.',                       contact: '+91-476-2802-400', address: 'Amritapuri, Kollam' },
  { id: 'seed-college-6',  name: 'Vishnu Ayurveda College',                                    district: 'Palakkad',           type: 'ayurveda',  profile: 'Private BAMS college in Palakkad with 60 admissions/year.',                                    contact: '+91-491-2546-655', address: 'Shoranur Road, Palakkad' },
  { id: 'seed-college-7',  name: 'PNNM Ayurveda Medical College',                              district: 'Pathanamthitta',     type: 'ayurveda',  profile: 'Pampady Mandiram — BAMS + PG. Affiliated to Kerala University.',                              contact: '+91-468-2222-777', address: 'Cheruthuruthy' },
  { id: 'seed-college-8',  name: 'KMCT Ayurveda College',                                      district: 'Kozhikode',          type: 'ayurveda',  profile: 'Private BAMS college, modern campus.',                                                         contact: '+91-495-2287-101', address: 'Mukkam, Kozhikode' },
  { id: 'seed-college-9',  name: 'Pankajakasthuri Ayurveda Medical College',                    district: 'Thiruvananthapuram', type: 'ayurveda',  profile: 'Private BAMS + MD college, attached to Pankajakasthuri pharmacy.',                            contact: '+91-471-2412-400', address: 'Killimanoor, Trivandrum' },
  { id: 'seed-college-10', name: 'Govt Medical College Kottayam',                              district: 'Kottayam',           type: 'modern',    profile: 'MBBS + PG + super-specialty. Largest govt medical college in central Kerala.',               contact: '+91-481-2597-471', address: 'Gandhinagar, Kottayam' },
]

// ─── TOURISM PACKAGES — 8 ────────────────────────────────────────────────
const TOURISM: Array<Prisma.MedicalTourismPackageCreateInput & { id: string }> = [
  { id: 'tour-1', title: 'Rejuvenation Panchakarma',         description: '14-day classical Panchakarma at a Kerala wellness centre. Daily Vaidya consultation, Snehapana, Virechana, Basti, Nasya, Shirodhara, dietary guidance, yoga.', duration: 14, price: 85000,  location: 'Ernakulam',         includes: 'Consultation, all Panchakarma procedures, herbal medicines, accommodation (AC), 3 sattvic meals, daily yoga, airport transfer.' },
  { id: 'tour-2', title: 'Stress Relief & Mental Clarity',    description: '7-day Shirodhara-focused program. Aimed at executives, anxiety, insomnia.',                                                                                       duration: 7,  price: 45000,  location: 'Thiruvananthapuram',includes: 'Shirodhara, Abhyanga, Padabhyanga, meditation, yoga, herbal teas, accommodation, meals.' },
  { id: 'tour-3', title: 'Joint & Spine Healing',             description: '21-day deep Panchakarma for arthritis, back pain, spondylosis, sciatica. Kati Basti, Janu Basti, Pizhichil.',                                                      duration: 21, price: 120000, location: 'Alappuzha',         includes: 'Daily local treatments, full body Panchakarma, classical medicines, physiotherapy, accommodation, meals.' },
  { id: 'tour-4', title: 'Skin & Detox Program',              description: '10-day Raktamokshana + Virechana program for psoriasis, eczema, acne. Strict diet.',                                                                              duration: 10, price: 55000,  location: 'Thrissur',          includes: 'Raktamokshana, Virechana, herbal lepa, dietary regimen, accommodation, meals.' },
  { id: 'tour-5', title: 'Karkidaka Chikitsa',                description: 'Monsoon-month rejuvenation (mid-July to mid-August). Most powerful season for Panchakarma per classical texts.',                                                  duration: 14, price: 75000,  location: 'Wayanad',           includes: 'All Karkidaka Kanji (medicated rice gruel) varieties, full Panchakarma, herbal baths, plantation stay, yoga.' },
  { id: 'tour-6', title: 'Weight Management',                 description: '14-day Lekhana Basti and Udvartana program. Target: 4-7kg loss + lifestyle reset.',                                                                              duration: 14, price: 70000,  location: 'Ernakulam',         includes: 'Udvartana (powder massage), Lekhana Basti, dietary plan, yoga, gym access, accommodation, meals.' },
  { id: 'tour-7', title: 'Beauty & Wellness',                 description: '7-day Sundarya Chikitsa — face, hair, skin glow.',                                                                                                                duration: 7,  price: 38000,  location: 'Kottayam',          includes: 'Mukha lepa, hair care, herbal facials, full body massages, dietary advice, accommodation, meals.' },
  { id: 'tour-8', title: 'Postnatal Care (Sutika Paricharya)',description: '40-day classical postnatal program for new mothers. Womb care, lactation support, mother-baby wellness.',                                                          duration: 40, price: 150000, location: 'Malappuram',        includes: 'Daily Abhyanga + steam, mother-baby care, lactation herbs, postnatal diet, sleep care, family room.' },
]

// ─── HEALTH TIPS — 8 (2 per dosha) ────────────────────────────────────────
const HEALTH_TIPS: Array<Prisma.HealthTipCreateInput & { id: string }> = [
  { id: 'tip-vata-1',     title: 'Daily oil massage to ground Vata',          dosha: 'vata',     season: 'sharad',   content: 'Vata types benefit deeply from a daily 10-minute Abhyanga (warm sesame oil self-massage) before bath, especially in autumn when wind and dryness peak. Focus on joints, scalp, soles. Reduces anxiety, improves sleep, strengthens immunity.',     language: 'en' },
  { id: 'tip-vata-2',     title: 'Warm, oily, grounding diet for Vata',        dosha: 'vata',     season: null,       content: 'Eat warm, cooked, slightly oily, well-spiced food. Avoid raw salads, cold drinks, and dry snacks. Favour ghee, sweet potatoes, almonds, dates. Eat at regular times — irregular eating spikes Vata more than wrong food.',                          language: 'en' },
  { id: 'tip-pitta-1',    title: 'Cooling Pitta in Kerala summer',             dosha: 'pitta',    season: 'grishma',  content: 'Summer (March–May) aggravates Pitta. Drink coriander seed water, sip rose-petal milk, eat fresh coconut, cucumber, melon. Avoid sour citrus, fermented foods, hot spices, and direct sun between 11am–3pm.',                                          language: 'en' },
  { id: 'tip-pitta-2',    title: 'Brahmi for Pitta-aggravated mind',           dosha: 'pitta',    season: null,       content: 'For irritability, perfectionism, and migraine — classical Pitta mental signs — Brahmi taken with milk at bedtime cools the mind. Combine with Shankhpushpi for stronger effect. Best under Ayurvedic guidance.',                                          language: 'en' },
  { id: 'tip-kapha-1',    title: 'Lighten Kapha in monsoon (Varsha Ritu)',     dosha: 'kapha',    season: 'varsha',   content: 'Monsoon increases Kapha and weakens Agni. Have ginger tea on waking, prefer light millets over rice, avoid dairy, oily snacks, and afternoon naps. Daily Udvartana (herbal powder massage) keeps the body light.',                                       language: 'en' },
  { id: 'tip-kapha-2',    title: 'Trikatu in winter to wake up metabolism',     dosha: 'kapha',    season: null,       content: 'Trikatu (Pippali + Maricha + Shunthi in equal parts), 1–2g with warm honey before meals, kindles Agni and clears Kapha congestion. Discontinue if heartburn or dryness develops.',                                                                       language: 'en' },
  { id: 'tip-tridosha-1', title: 'Triphala — every household\'s daily ally',    dosha: 'tridosha', season: null,       content: 'Triphala (3–5g) with warm water at bedtime keeps digestion clean, eyes bright, and tissues nourished. Suits all doshas. Skip during pregnancy and acute diarrhea.',                                                                                  language: 'en' },
  { id: 'tip-tridosha-2', title: 'Wake before sunrise for tridosha balance',     dosha: 'tridosha', season: null,       content: 'Brahma Muhurta (~1.5 hr before sunrise) is the most sattvic period of day — best for meditation, study, exercise. Sleeping past sunrise increases Kapha and dulls the mind across all body types.',                                                  language: 'en' },
]

// ─── FORUM POSTS — 20 ────────────────────────────────────────────────────
const FORUM_POSTS: Array<{ id: string; title: string; content: string; category: string; language?: string }> = [
  { id: 'post-1',  title: 'Case: Severe psoriasis remission with 21-day Virechana — full protocol',     content: '38-year-old male with chronic plaque psoriasis (PASI 28) for 12 years. After 21-day Virechana protocol (Snehapana 7d + Virechana day 8 + post-care), PASI dropped to 6 in 90 days. Full protocol + classical formulations in attached comments. Welcoming case discussion.', category: 'doctor-discussion' },
  { id: 'post-2',  title: 'Has anyone tried Ksharasutra for high anal fistula? Recurrence rates?',       content: 'Treating a 45-yr male with type-2 high anal fistula. Modern surgery has 25-30% recurrence in literature. Looking for fellow Shalya practitioners\' experience with Ksharasutra at this complexity. Average sittings, recurrence at 5-yr follow-up?',                                category: 'doctor-discussion' },
  { id: 'post-3',  title: 'Kati Basti vs Lumbar epidural — when do you escalate?',                       content: 'Patient: 52F, L4-L5 disc herniation, no neuro deficit. 6 sittings of Kati Basti + Yoga Basti has given 70% relief. Pain consultant recommends epidural injection. At what point do you suggest patient consider it vs continuing classical line?',                              category: 'doctor-discussion' },
  { id: 'post-4',  title: 'Karkidaka Kanji — how do you decide variant for the patient?',                content: 'Standard 7-variant Kanji (Njavara/Vaidyaratnam style) vs single base + customization. What\'s your protocol when the patient is Kapha-Pitta vs pure Vata? Sharing my decision tree, looking for refinements.',                                                              category: 'doctor-discussion' },
  { id: 'post-5',  title: 'Long-term safety of Brahmi in pediatric ADHD — what\'s your follow-up?',       content: '6-yr-old, mild ADHD, improved markedly on Brahmi Ghrita over 4 months. Family wants to continue. What\'s your view on Brahmi long-term in pediatric use? Any neuro/endocrine signals to monitor?',                                                                            category: 'doctor-discussion' },
  { id: 'post-6',  title: 'Patient asking: Can I do Panchakarma during pregnancy?',                      content: 'Pregnant patient (24 wks) wants stress relief Panchakarma. Classical view is contraindication. But she\'s very anxious. Is there a safer subset (e.g. Shirodhara only)? Have any of you supervised this?',                                                                       category: 'doctor-discussion' },
  { id: 'post-7',  title: 'Hypothyroidism — Ayurveda + thyroxine vs replacement alone?',                   content: 'Hashimoto\'s patient on 100mcg levothyroxine. TPO Ab very high. Tried Kanchanara Guggulu + Triphala for 6 mo, antibodies dropped from 480 to 280 IU/mL. Continuing both. Has anyone had patients eventually wean off levothyroxine? Realistic or wishful?',                  category: 'doctor-discussion' },
  { id: 'post-8',  title: 'New BAMS, want to start lifestyle counseling clinic — which OPD model works?', content: 'Just finished BAMS, planning a lifestyle counseling-only clinic in Kochi. Pure consult, no in-house pharmacy. Which fee model is sustainable — package (₹5000 for 5 sessions) or per-visit? Senior practitioners, your thoughts?',                                            category: 'doctor-discussion' },
  { id: 'post-9',  title: 'Best practical reference for Rasashastra preparations?',                      content: 'Looking beyond Rasaratnasamuchaya for practical Bhasma preparation. Which modern monograph do you trust for Loha Bhasma (iron) safety profile + heavy metal limits?',                                                                                                                  category: 'doctor-discussion' },
  { id: 'post-10', title: 'IBS-D — which Grahi works best for you?',                                       content: 'For IBS-D patients, I\'ve been alternating between Bilva, Kutaja, and Musta. Which combination gives you the best outcome at 3 months?',                                                                                                                                       category: 'doctor-discussion' },
  { id: 'post-11', title: 'Severe acidity — can I take Triphala?',                                         content: 'I have GERD diagnosed by gastroenterologist. Reading conflicting advice — some say Triphala helps, others say Haritaki is too pungent for Pitta. What should I do?',                                                                                                                  category: 'patient-forum' },
  { id: 'post-12', title: 'PCOS — does Ayurveda actually reverse it?',                                     content: '26F, PCOS for 5 years. Cycles 45-90 days. Modern docs say "lifestyle management". Has anyone here actually had PCOS reversed with Ayurveda alone? Realistic or marketing?',                                                                                                            category: 'patient-forum' },
  { id: 'post-13', title: 'Sleeping 4 hours, can\'t function — what to do?',                              content: 'Insomnia for 8 months. Tried melatonin, sleeping pills, no help. Saw an Ayurvedic doc, prescribed Brahmi + Shirodhara course. Is Shirodhara worth it? Anyone with similar story?',                                                                                                  category: 'patient-forum' },
  { id: 'post-14', title: 'Hair fall in 30s — Bhringaraj oil daily, but no improvement',                   content: 'Using Bhringaraj oil for 6 months, hair still falling. Diet decent, sleep okay. What more should I do? Internal medicines?',                                                                                                                                                              category: 'patient-forum' },
  { id: 'post-15', title: 'Best clinic for Panchakarma in Kochi for foreigners?',                          content: 'Coming from UK, want authentic Kerala Panchakarma — not luxury spa. Looking for clinic or hospital recommendations. Budget reasonable but treatment quality is priority.',                                                                                                              category: 'patient-forum' },
  { id: 'post-16', title: 'Migraine 15 days a month — desperate for help',                                 content: 'Chronic migraine since 22, now 35. Triptans not working anymore. Neurologist suggested Botox. Wondering if Ayurveda can help before that step.',                                                                                                                                       category: 'patient-forum' },
  { id: 'post-17', title: 'Anxiety + IBS together — connected?',                                            content: 'Constant gut issues whenever I\'m anxious. Modern doctor calls it "IBS". Ayurvedic friend says it\'s Vata in mind affecting Vata in colon. Which approach is right? Looking for combined treatment.',                                                                                category: 'patient-forum' },
  { id: 'post-18', title: 'Pregnancy nausea — safe Ayurvedic options?',                                    content: 'First trimester, severe nausea. Modern anti-emetics make me drowsy. Are there safe Ayurvedic options? Heard ginger helps but afraid to self-prescribe in pregnancy.',                                                                                                                  category: 'patient-forum' },
  { id: 'post-19', title: 'Diabetic for 12 years — can I reduce metformin with Ayurveda?',                  content: 'HbA1c at 7.2 on 2g metformin. Endocrinologist OK with adding Ayurveda. Looking for honest answers — has anyone successfully reduced/stopped metformin with classical Ayurveda?',                                                                                                       category: 'patient-forum' },
  { id: 'post-20', title: 'Dosha quiz says I\'m Pitta-Vata. What does that mean for diet?',                content: 'Took an online dosha quiz and got Pitta-Vata. So which diet do I follow — Pitta or Vata? They contradict in many places. Help!',                                                                                                                                                          category: 'patient-forum' },
]

// ─── MAIN ────────────────────────────────────────────────────────────────
async function main() {
  console.log('seeding…')

  // Admin user (no Better Auth password — sign up via /sign-in then UPDATE role).
  const admin = await prisma.user.upsert({
    where: { email: 'admin@ayurconnect.com' },
    update: { name: 'AyurConnect Admin', emailVerified: true, role: 'ADMIN' },
    create: { email: 'admin@ayurconnect.com', name: 'AyurConnect Admin', emailVerified: true, role: 'ADMIN' },
  })

  // Demo patient (also no password — same caveat).
  const demoPatient = await prisma.user.upsert({
    where: { email: 'demo@ayurconnect.com' },
    update: { name: 'Demo Patient', role: 'USER' },
    create: { email: 'demo@ayurconnect.com', name: 'Demo Patient', emailVerified: true, role: 'USER' },
  })

  for (const d of DOCTORS) {
    const { id, ...data } = d
    await prisma.doctor.upsert({ where: { id }, update: data, create: { id, ...data } })
  }
  for (const h of HOSPITALS) {
    const { id, ...data } = h
    await prisma.hospital.upsert({ where: { id }, update: data, create: { id, ...data } })
  }
  for (const h of HERBS) {
    await prisma.herb.upsert({ where: { id: h.id }, update: h, create: h })
  }
  for (const c of COLLEGES) {
    const { id, ...data } = c
    await prisma.medicalCollege.upsert({ where: { id }, update: data, create: { id, ...data } })
  }
  for (const t of TOURISM) {
    const { id, ...data } = t
    await prisma.medicalTourismPackage.upsert({ where: { id }, update: data, create: { id, ...data } })
  }
  for (const tip of HEALTH_TIPS) {
    const { id, ...data } = tip
    await prisma.healthTip.upsert({ where: { id }, update: data, create: { id, ...data } })
  }
  for (const post of FORUM_POSTS) {
    await prisma.post.upsert({
      where: { id: post.id },
      update: { title: post.title, content: post.content, category: post.category, language: post.language ?? 'en', userId: admin.id },
      create: { id: post.id, title: post.title, content: post.content, category: post.category, language: post.language ?? 'en', userId: admin.id },
    })
  }

  // Sample reviews to make a few doctors look popular on the homepage.
  const reviewSeeds = [
    { id: 'rev-1', rating: 5, comment: 'Dr. Menon\'s Panchakarma program transformed my chronic back pain. Honest, classical, no shortcuts.', userId: demoPatient.id, doctorId: 'seed-doctor-1'  },
    { id: 'rev-2', rating: 5, comment: 'Very thorough Nadi pariksha. Diagnosed root cause of my migraines other doctors missed.',           userId: demoPatient.id, doctorId: 'seed-doctor-8'  },
    { id: 'rev-3', rating: 4, comment: 'Excellent for diabetic management. Worked alongside my endocrinologist patiently.',                  userId: demoPatient.id, doctorId: 'seed-doctor-2'  },
    { id: 'rev-4', rating: 5, comment: 'Treated my postnatal depression with care and dignity. Highly recommend.',                            userId: demoPatient.id, doctorId: 'seed-doctor-3'  },
    { id: 'rev-5', rating: 5, comment: 'My fistula is healed completely. Ksharasutra was painful but worked. Surgery saved.',                 userId: demoPatient.id, doctorId: 'seed-doctor-4'  },
    { id: 'rev-6', rating: 5, comment: 'My son\'s asthma is completely controlled now. Six months of patient treatment.',                     userId: demoPatient.id, doctorId: 'seed-doctor-5'  },
    { id: 'rev-7', rating: 5, comment: 'Anxiety and insomnia gone after 3 months of combined Shirodhara + medication.',                       userId: demoPatient.id, doctorId: 'seed-doctor-6'  },
    { id: 'rev-8', rating: 4, comment: 'Knowledgeable in rare herbs. Customized formulation worked for my IBS.',                              userId: demoPatient.id, doctorId: 'seed-doctor-7'  },
    { id: 'rev-9', rating: 5, comment: 'Booked 14-day rejuvenation. Worth every rupee. International quality care.',                          userId: demoPatient.id, doctorId: 'seed-doctor-15' },
  ]
  for (const r of reviewSeeds) {
    const { id, ...data } = r
    await prisma.review.upsert({ where: { id }, update: data, create: { id, ...data } })
  }

  // Knowledge article (kept from before).
  await prisma.knowledgeArticle.upsert({
    where: { id: 'seed-article-1' },
    update: {},
    create: {
      id: 'seed-article-1',
      title: 'Dinacharya — The Ayurvedic Daily Routine',
      content: 'Dinacharya prescribes a daily routine aligned with circadian rhythm: rise before sunrise (Brahma Muhurta), oral hygiene (tongue scraping, oil pulling), Abhyanga (oil massage), exercise (half capacity), bathing, breakfast, work, lunch (largest meal of day at solar noon), evening rest, light dinner before sunset, sleep by 10pm. Following this single discipline alone improves energy, digestion, and longevity.',
      category: 'classical-text',
      source: 'Ashtanga Hridayam, Sutrasthana 2',
      language: 'en',
    },
  })

  console.log('✓ seeded:', {
    doctors: DOCTORS.length,
    hospitals: HOSPITALS.length,
    herbs: HERBS.length,
    colleges: COLLEGES.length,
    tourism: TOURISM.length,
    healthTips: HEALTH_TIPS.length,
    forumPosts: FORUM_POSTS.length,
    reviews: reviewSeeds.length,
    users: [admin.email, demoPatient.email],
  })
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(async () => { await prisma.$disconnect() })
