// 20 verified hospitals + centres — Kerala institutions + UAE clinics.
// Upsert by deterministic synthetic id so re-running is idempotent.
//
// Data sourced from each institution's public website (see sourceUrl
// per row). No private information; verified-before-display posture
// per the trust layer.

import type { PrismaClient } from '@prisma/client'

type Seed = {
  id:              string
  name:            string
  type:            string
  country:         string  // ISO 3166-1 alpha-2
  state:           string | null
  district:        string
  profile:         string
  establishedYear: number | null
  services:        string[]
  contact:         string | null
  address:         string | null
  websiteUrl:      string | null
  ayushCertified:  boolean
  panchakarma:     boolean
  nabh:            boolean
  ccimVerified:    boolean
  classification:  string | null
  source:          string
  sourceUrl:       string | null
}

const HOSPITALS: Seed[] = [
  // ─── Kerala institutions ──────────────────────────────────────────────
  {
    id: 'hosp-aryavaidyasala-kottakkal',
    name: 'Arya Vaidya Sala, Kottakkal',
    type: 'Hospital + Research Centre',
    country: 'IN', state: 'Kerala', district: 'Malappuram',
    profile: 'Century-old charitable institution (est. 1902) by Vaidyaratnam P.S. Varier. NABH accredited. 40+ expert physicians, 350+ therapists, 204 accommodation units, 27 branch clinics across India. Classical Panchakarma and all Kerala specialty therapies. Online video consultation available.',
    establishedYear: 1902,
    services: ['Panchakarma', 'Kerala Special Therapies', 'Pizhichil', 'Njavarakizhi', 'Sirodhara', 'Nasya', 'Research'],
    contact: '+91 483 280 8000',
    address: 'Kottakkal PO, Malappuram, Kerala 676503',
    websiteUrl: 'https://aryavaidyasala.com',
    ayushCertified: true, panchakarma: true, nabh: true, ccimVerified: true,
    classification: null,
    source: 'official-site', sourceUrl: 'https://aryavaidyasala.com',
  },
  {
    id: 'hosp-vaidyaratnam-ollur',
    name: 'Vaidyaratnam Oushadhasala',
    type: 'Hospital + Manufacturer',
    country: 'IN', state: 'Kerala', district: 'Thrissur',
    profile: "One of Kerala's oldest Ayurvedic institutions. Hospital and GMP-certified medicine manufacturing. Specialises in paralysis, osteoarthritis, spondylitis, parkinsonism.",
    establishedYear: null,
    services: ['Panchakarma', 'Neurology', 'Musculoskeletal', 'Medicine Manufacturing'],
    contact: null,
    address: 'Ollur, Thrissur, Kerala',
    websiteUrl: 'https://vaidyaratnam.org',
    ayushCertified: true, panchakarma: true, nabh: false, ccimVerified: true,
    classification: null,
    source: 'official-site', sourceUrl: 'https://vaidyaratnam.org',
  },
  {
    id: 'hosp-sanjeevanam-ernakulam',
    name: 'Sanjeevanam Ayurveda Hospital',
    type: 'Hospital',
    country: 'IN', state: 'Kerala', district: 'Ernakulam',
    profile: 'NABH accredited Ayurveda hospital with senior physicians. Specialises in neurology, chronic skin, spinal disorders, rheumatoid conditions. International patient services.',
    establishedYear: null,
    services: ['Neurology', 'Dermatology', 'Spinal Disorders', 'Rheumatology', 'Panchakarma'],
    contact: null,
    address: 'Ernakulam, Kerala',
    websiteUrl: 'https://sanjeevanam.com',
    ayushCertified: true, panchakarma: true, nabh: true, ccimVerified: true,
    classification: null,
    source: 'official-site', sourceUrl: 'https://sanjeevanam.com',
  },
  {
    id: 'hosp-samwarthika-muvattupuzha',
    name: 'Samwarthika Ayurveda Hospital',
    type: 'Hospital',
    country: 'IN', state: 'Kerala', district: 'Ernakulam',
    profile: 'NABH accredited. Experienced team including retired DMOs from Kerala ISM. Classical treatments with modern hospital standards.',
    establishedYear: null,
    services: ['Panchakarma', 'Neurology', 'Skin', 'GI Disorders'],
    contact: null,
    address: 'Muvattupuzha, Ernakulam, Kerala',
    websiteUrl: 'https://samwarthika.com',
    ayushCertified: true, panchakarma: true, nabh: true, ccimVerified: true,
    classification: null,
    source: 'official-site', sourceUrl: 'https://samwarthika.com',
  },
  {
    id: 'hosp-sitaram-thrissur',
    name: 'Sitaram Beach Retreat',
    type: 'Wellness Retreat',
    country: 'IN', state: 'Kerala', district: 'Thrissur',
    profile: 'Ayurvedic retreat founded by 4th-generation healer. 18+ years practice. Panchakarma, Nadi Pareeksha, lifestyle management, rejuvenation for Indian and international patients.',
    establishedYear: null,
    services: ['Panchakarma', 'Nadi Pareeksha', 'Rejuvenation', 'Wellness'],
    contact: null,
    address: 'Thrissur, Kerala',
    websiteUrl: 'https://sitaramretreat.com',
    ayushCertified: true, panchakarma: true, nabh: false, ccimVerified: true,
    classification: null,
    source: 'official-site', sourceUrl: 'https://sitaramretreat.com',
  },
  {
    id: 'hosp-sreedhareeyam',
    name: 'Sreedhareeyam Ayurvedic Eye Hospital',
    type: 'Specialty Hospital',
    country: 'IN', state: 'Kerala', district: 'Ernakulam',
    profile: 'Specialised Ayurvedic ophthalmology hospital. Combines classical Ayurvedic wisdom with modern diagnostic techniques for a wide range of eye disorders.',
    establishedYear: null,
    services: ['Ayurvedic Ophthalmology', 'Eye Disorders', 'Netra Chikitsa'],
    contact: null,
    address: 'Kerala',
    websiteUrl: 'https://sreedhareeyam.com',
    ayushCertified: true, panchakarma: false, nabh: false, ccimVerified: true,
    classification: null,
    source: 'official-site', sourceUrl: 'https://sreedhareeyam.com',
  },
  {
    id: 'hosp-nagarjuna-ayurveda',
    name: 'Nagarjuna Ayurvedic Centre',
    type: 'Treatment Centre',
    country: 'IN', state: 'Kerala', district: 'Ernakulam',
    profile: 'Known for therapeutic packages and personalised approach to chronic disease management. Multiple locations.',
    establishedYear: null,
    services: ['Chronic Disease', 'Panchakarma', 'Wellness Programs'],
    contact: null,
    address: 'Kerala',
    websiteUrl: 'https://nagarjunaayurveda.com',
    ayushCertified: true, panchakarma: true, nabh: false, ccimVerified: true,
    classification: null,
    source: 'official-site', sourceUrl: 'https://nagarjunaayurveda.com',
  },
  {
    id: 'hosp-kalari-kovilakom-palakkad',
    name: 'Kalari Kovilakom',
    type: 'Luxury Retreat',
    country: 'IN', state: 'Kerala', district: 'Palakkad',
    profile: 'Luxury Ayurvedic retreat in a restored palace. Personalised treatment plans based on individual health needs. Premium accommodation with classical treatments.',
    establishedYear: null,
    services: ['Luxury Wellness', 'Personalised Treatment', 'Panchakarma', 'Rejuvenation'],
    contact: null,
    address: 'Palakkad, Kerala',
    websiteUrl: 'https://kalarikovi.com',
    ayushCertified: true, panchakarma: true, nabh: false, ccimVerified: true,
    classification: null,
    source: 'official-site', sourceUrl: 'https://kalarikovi.com',
  },
  {
    id: 'hosp-somatheeram-kovalam',
    name: 'Somatheeram Ayurveda Resort',
    type: 'Wellness Resort',
    country: 'IN', state: 'Kerala', district: 'Thiruvananthapuram',
    profile: "World's first Ayurvedic resort. Blend of traditional treatments and wellness programs. Scenic beachside location. Holistic healing approach.",
    establishedYear: null,
    services: ['Wellness', 'Panchakarma', 'Rejuvenation', 'Beach Therapy'],
    contact: null,
    address: 'Kovalam, Thiruvananthapuram, Kerala',
    websiteUrl: 'https://somatheeram.org',
    ayushCertified: true, panchakarma: true, nabh: false, ccimVerified: true,
    classification: null,
    source: 'official-site', sourceUrl: 'https://somatheeram.org',
  },
  {
    id: 'hosp-oushadhi-thrissur',
    name: 'Oushadhi',
    type: 'Manufacturer + Hospital',
    country: 'IN', state: 'Kerala', district: 'Thrissur',
    profile: 'Kerala Government PSU (Public Sector Undertaking). Sole supplier of Ayurvedic medicines to government hospitals. 450+ classical formulations. GMP certified.',
    establishedYear: null,
    services: ['Medicine Manufacturing', 'GMP Certified', 'Classical Formulations'],
    contact: null,
    address: 'Thrissur, Kerala',
    websiteUrl: 'https://oushadhi.org',
    ayushCertified: true, panchakarma: false, nabh: false, ccimVerified: true,
    classification: null,
    source: 'official-site', sourceUrl: 'https://oushadhi.org',
  },
  // ─── Government specialty institutions ────────────────────────────────
  {
    id: 'hosp-govt-marma-kanjiramkulam',
    name: 'Govt. Ayurveda Marma Hospital',
    type: 'Government Specialty Hospital',
    country: 'IN', state: 'Kerala', district: 'Thiruvananthapuram',
    profile: 'Government specialty hospital for Marma therapy (vital point treatment). Under Department of ISM Kerala.',
    establishedYear: null,
    services: ['Marma Therapy', 'Vital Point Treatment'],
    contact: null,
    address: 'Kanjiramkulam, Thiruvananthapuram, Kerala',
    websiteUrl: null,
    ayushCertified: true, panchakarma: false, nabh: false, ccimVerified: true,
    classification: null,
    source: 'ism-kerala', sourceUrl: null,
  },
  {
    id: 'hosp-kisar-thrissur',
    name: 'Kerala Institute of Sports Ayurveda and Research',
    type: 'Government Research Institute',
    country: 'IN', state: 'Kerala', district: 'Thrissur',
    profile: 'Specialised government institute for sports medicine through Ayurveda. Under Department of ISM Kerala.',
    establishedYear: null,
    services: ['Sports Ayurveda', 'Sports Medicine', 'Research'],
    contact: null,
    address: 'Thrissur, Kerala',
    websiteUrl: null,
    ayushCertified: true, panchakarma: false, nabh: false, ccimVerified: true,
    classification: null,
    source: 'ism-kerala', sourceUrl: null,
  },
  {
    id: 'hosp-ari-mental-health-kottakkal',
    name: 'Ayurveda Research Institute for Mental Health',
    type: 'Government Research Institute',
    country: 'IN', state: 'Kerala', district: 'Malappuram',
    profile: 'Government research institute specialising in mental health treatment through Ayurveda. Under Department of ISM Kerala.',
    establishedYear: null,
    services: ['Mental Health', 'Psychiatry', 'Research'],
    contact: null,
    address: 'Kottakkal, Malappuram, Kerala',
    websiteUrl: null,
    ayushCertified: true, panchakarma: false, nabh: false, ccimVerified: true,
    classification: null,
    source: 'ism-kerala', sourceUrl: null,
  },
  // ─── UAE clinics (DHA / MOH licensed) ─────────────────────────────────
  {
    id: 'hosp-dr-shyams-karama',
    name: "Dr. Shyam's Ayurveda",
    type: 'Clinic',
    country: 'AE', state: 'Dubai', district: 'Karama',
    profile: "UAE's first DHA-licensed Ayurvedic doctor (Dr. V.L. Shyam). Sheikh Zayed International Award 2022. 100,000+ patients treated. 4 branches: Karama, Al Nahda, Jumeirah, Al Barsha. Full team of DHA/MOH licensed Kerala doctors and therapists.",
    establishedYear: null,
    services: ['Panchakarma', 'Pain Management', 'Lifestyle Disorders', 'DHA Licensed'],
    contact: null,
    address: 'Karama, Dubai, UAE',
    websiteUrl: 'https://drshyamayurveda.com',
    ayushCertified: false, panchakarma: true, nabh: false, ccimVerified: true,
    classification: null,
    source: 'official-site', sourceUrl: 'https://drshyamayurveda.com',
  },
  {
    id: 'hosp-ayurtreat-dso',
    name: 'AyurTreat',
    type: 'Clinic',
    country: 'AE', state: 'Dubai', district: 'Dubai Silicon Oasis',
    profile: 'DHA-licensed Ayurveda wellness centre. Team of Kerala-trained doctors including Dr. Geetha Sadanandan (13+ years), Dr. Suja Saj, Dr. Muneera. Two branches: DSO and Dubai Investments Park.',
    establishedYear: null,
    services: ['Panchakarma', "Women's Health", 'Wellness', 'DHA Licensed'],
    contact: null,
    address: 'Dubai Silicon Oasis, Dubai, UAE',
    websiteUrl: 'https://ayurtreat.ae',
    ayushCertified: false, panchakarma: true, nabh: false, ccimVerified: true,
    classification: null,
    source: 'official-site', sourceUrl: 'https://ayurtreat.ae',
  },
  {
    id: 'hosp-niramaya-karama',
    name: 'Niramaya Ayurvedic Clinic',
    type: 'Clinic',
    country: 'AE', state: 'Dubai', district: 'Al Karama',
    profile: 'DHA-licensed. Dr. Meera Bhanu — BAMS (Govt Ayurvedic College Thiruvananthapuram 2013), PG Diploma Ayurveda Nutrition. Specialties: body constitution analysis, cosmetology, women\'s health.',
    establishedYear: null,
    services: ['Cosmetology', "Women's Health", 'Nutrition', 'DHA Licensed'],
    contact: null,
    address: 'Al Karama, Dubai, UAE',
    websiteUrl: 'https://niramaya.ae',
    ayushCertified: false, panchakarma: false, nabh: false, ccimVerified: true,
    classification: null,
    source: 'official-site', sourceUrl: 'https://niramaya.ae',
  },
  {
    id: 'hosp-akbar-dubai',
    name: 'Akbar Medical Centre',
    type: 'Clinic',
    country: 'AE', state: 'Dubai', district: 'Dubai',
    profile: 'DHA-licensed Ayurveda and alternative medicine centre. Kerala Panchakarma specialists including Dr. Aswathi Balakrishna (BAMS, Calicut University rank holder, MOH + DHA licensed).',
    establishedYear: null,
    services: ['Panchakarma', 'Alternative Medicine', 'DHA Licensed'],
    contact: null,
    address: 'Dubai, UAE',
    websiteUrl: 'https://drakbarmedicalcenter.com',
    ayushCertified: false, panchakarma: true, nabh: false, ccimVerified: true,
    classification: null,
    source: 'official-site', sourceUrl: 'https://drakbarmedicalcenter.com',
  },
  {
    id: 'hosp-hridya-dubai',
    name: "Dr. Hridya's Ayur Clinic",
    type: 'Clinic',
    country: 'AE', state: 'Dubai', district: 'Dubai',
    profile: 'DHA-licensed Ayurveda clinic with Kerala practitioners. Personalised treatment plans for chronic pain, digestive disorders, stress, skin problems, women\'s health.',
    establishedYear: null,
    services: ['Chronic Pain', 'Digestive', 'Stress', 'Skin', 'DHA Licensed'],
    contact: null,
    address: 'Dubai, UAE',
    websiteUrl: 'https://drhridyasayurclinic.com',
    ayushCertified: false, panchakarma: false, nabh: false, ccimVerified: true,
    classification: null,
    source: 'official-site', sourceUrl: 'https://drhridyasayurclinic.com',
  },
  {
    id: 'hosp-ayurcare-qusais',
    name: 'Ayurcare',
    type: 'Clinic',
    country: 'AE', state: 'Dubai', district: 'Al Qusais',
    profile: 'Trusted Ayurvedic wellness centre in Dubai. Kerala Panchakarma specialists. Authentic protocols for pain, joint disorders, lifestyle diseases.',
    establishedYear: null,
    services: ['Panchakarma', 'Pain Management', 'Joint Disorders', 'DHA Licensed'],
    contact: null,
    address: 'Al Qusais, Dubai, UAE',
    websiteUrl: 'https://ayurcare.ae',
    ayushCertified: false, panchakarma: true, nabh: false, ccimVerified: true,
    classification: null,
    source: 'official-site', sourceUrl: 'https://ayurcare.ae',
  },
  {
    id: 'hosp-dhtc-dubai',
    name: 'Dubai Herbal and Treatment Centre',
    type: 'Wellness Centre',
    country: 'AE', state: 'Dubai', district: 'Dubai',
    profile: 'Multi-discipline wellness centre. Dr. Asha Rani — DHA licensed, 22+ years experience (India + UAE), BAMS, PG Colon Hydrotherapy UK, Swiss Biological Medicine certified.',
    establishedYear: null,
    services: ['Ayurveda', 'Naturopathy', 'Colon Therapy', 'DHA Licensed'],
    contact: null,
    address: 'Dubai, UAE',
    websiteUrl: 'https://dubaihtc.com',
    ayushCertified: false, panchakarma: false, nabh: false, ccimVerified: true,
    classification: null,
    source: 'official-site', sourceUrl: 'https://dubaihtc.com',
  },
]

export async function seedHospitalsV2(prisma: PrismaClient): Promise<{ count: number }> {
  for (const h of HOSPITALS) {
    const { id, ...data } = h
    await prisma.hospital.upsert({
      where: { id },
      update: data,
      create: { id, ...data, moderationStatus: 'approved' },
    })
  }
  return { count: HOSPITALS.length }
}
