export type Ebook = {
  slug: string
  title: string
  author: string
  category: 'textbook' | 'reference' | 'clinical_guide' | 'research' | 'classical_text' | 'modern'
  language: 'en' | 'ml' | 'sa' | 'hi' | 'en-ml' | 'sa-en'
  pages: number
  fileSize: string
  format: 'pdf'
  description: string
  tags: string[]
}

export const EBOOKS: Ebook[] = [
  { slug: 'charaka-samhita-sutra-sthana', title: 'Charaka Samhita — Volume 1 (Sutra Sthana)', author: 'Charaka · Agnivesha', category: 'classical_text', language: 'sa-en', pages: 500, fileSize: '14 MB', format: 'pdf', description: 'Complete Sutra Sthana with English translation and commentary. Includes Deergha Jeeviteeya, Apamarga Tanduliya, Aragvadhiya, Shadvirechana, Atulya Gotriya — the foundational chapters covering ayus definition, treatment classification, 500 cardinal herbs in dashemani, and all major treatment principles. Annotated with Chakrapani Tika excerpts. Sanskrit-English parallel text format. Indexed for clinical reference.', tags: ['charaka', 'samhita', 'classical', 'sanskrit'] },
  { slug: 'ashtanga-hridayam-english', title: 'Ashtanga Hridayam with English Commentary', author: 'Vagbhata', category: 'classical_text', language: 'sa-en', pages: 800, fileSize: '22 MB', format: 'pdf', description: 'Vagbhata\'s synthetic masterwork — the most concise + practical classical text. Used as the primary teaching text in Kerala tradition. Covers all 8 branches of Ayurveda in 6 sthanas: Sutra, Sharira, Nidana, Chikitsa, Kalpa, Uttara. English translation alongside Sanskrit. Includes Arunadatta commentary excerpts. Practical pharmacology, clinical algorithms, and surgical procedures all present.', tags: ['vagbhata', 'ashtanga-hridayam', 'classical', 'kerala-tradition'] },
  { slug: 'dravyaguna-study-guide', title: 'Dravyaguna Vigyana — Study Guide', author: 'AyurConnect Academic', category: 'textbook', language: 'en', pages: 300, fileSize: '8 MB', format: 'pdf', description: 'BAMS-curriculum-aligned Dravyaguna study guide. Covers rasa panchaka in depth, 50 dashemani with detailed herb profiles, botanical identification, pharmacognosy, modern pharmacology correlations, and clinical use guidelines. Each herb monograph includes Sanskrit synonyms, family, parts used, properties, indications, dose, formulations, contraindications, and recent research. Exam-focused with practice questions per chapter.', tags: ['dravyaguna', 'study-guide', 'BAMS', 'materia-medica'] },
  { slug: 'panchakarma-illustrated-manual', title: 'Panchakarma Illustrated — Practical Manual', author: 'AyurConnect Clinical Faculty', category: 'clinical_guide', language: 'en', pages: 200, fileSize: '18 MB', format: 'pdf', description: 'Hands-on Panchakarma manual with step-by-step illustrated protocols for vamana, virechana, basti, nasya, raktamokshana. Each procedure: indications, contraindications, equipment, snehapana protocol with ascending doses, exact procedural steps, samyak signs, complications + management, sansarjana karma. Plus Kerala-specific therapies: pizhichil, sirodhara, navarakizhi, kati basti, shiro basti. Photographic illustrations from real procedures.', tags: ['panchakarma', 'clinical', 'manual', 'kerala-therapies'] },
  { slug: 'aiapget-preparation-guide-2026', title: 'AIAPGET Preparation Guide 2026', author: 'AyurConnect Academic', category: 'reference', language: 'en', pages: 400, fileSize: '12 MB', format: 'pdf', description: 'Comprehensive AIAPGET prep guide updated for 2026 syllabus. Subject-wise high-yield chapter summaries, 1000+ practice MCQs with detailed explanations, previous 10 years\' AIAPGET pattern analysis, topic-wise weightage, time management strategies, last-month revision schedule, and mock test papers. Specifically designed for the new NCISM-aligned exam pattern.', tags: ['AIAPGET', 'PG-entrance', 'MCQ', 'exam-prep'] },
  { slug: 'sahasrayogam-malayalam', title: 'Sahasrayogam — Malayalam Translation', author: 'Anonymous (~14th century)', category: 'classical_text', language: 'ml', pages: 350, fileSize: '9 MB', format: 'pdf', description: 'The signature Kerala practical formulary. 1000+ classical formulations organized by chikitsa-type. Includes kashayas, vatis, churnam, tailams, ghrita, lehyam, and asavas-arishtas used daily in Kerala practice today. Each formulation: ingredients with quantities, preparation method, indication, dose, anupana. Malayalam original with brief annotations. Indispensable reference for clinical practice in Kerala.', tags: ['sahasrayogam', 'kerala', 'malayalam', 'formulary'] },
  { slug: 'rasashastra-simplified', title: 'Rasashastra Simplified', author: 'AyurConnect Academic', category: 'textbook', language: 'en', pages: 250, fileSize: '7 MB', format: 'pdf', description: 'A practical introduction to Rasashastra (metallic + mineral preparations) for BAMS students. Demystifies parada (mercury) chemistry, 18 samskaras of shodhana + marana, bhasma preparation + quality verification (niruttha, apunarbhava, varitara tests), maharasa + uparasa classification, and clinical use of major rasa-aushadhi. Modern safety + toxicology framework. Regulatory landscape for Hg-containing formulations in India + abroad.', tags: ['rasashastra', 'bhasma', 'parada', 'pharmacology'] },
  { slug: 'ayurvedic-nutrition-cooking', title: 'Ayurvedic Nutrition & Cooking', author: 'AyurConnect Clinical Faculty', category: 'modern', language: 'en', pages: 180, fileSize: '15 MB', format: 'pdf', description: 'Ayurvedic dietetics for the modern practitioner + patient. Covers prakriti-specific diet planning, seasonal eating (ritucharya), agni-aware food choices, ama-reducing recipes, pathya-apathya for major conditions (diabetes, hypertension, IBS, eczema, PCOS), and 75+ Kerala recipes adapted for daily use. Photographic recipes with full nutritional analysis + dosic effect. Bridge between classical ahara principles and modern dietary science.', tags: ['nutrition', 'diet', 'cooking', 'lifestyle'] },
  { slug: 'keraleeya-ayurveda-history', title: 'Keraleeya Ayurveda — History and Practice', author: 'AyurConnect Heritage Team', category: 'reference', language: 'en-ml', pages: 280, fileSize: '11 MB', format: 'pdf', description: 'Comprehensive history of Kerala\'s distinct Ayurveda tradition. Covers Ashtavaidya lineages (Vaidyamadham, Pulamanthole, Thaikkattu, etc.), Sahasrayogam tradition, Kerala-specific Panchakarma development (Pizhichil, Njavarakizhi), Visha chikitsa heritage, integration with Kalaripayattu + marma chikitsa, regulatory evolution (Kerala Ayurveda Council, statutory bodies), and the contemporary Kerala Ayurveda scene. English-Malayalam bilingual presentation.', tags: ['kerala', 'history', 'tradition', 'ashtavaidya'] },
  { slug: 'clinical-ayurveda-50-cases', title: 'Clinical Ayurveda Case Repository — 50 Cases', author: 'AyurConnect Clinical Faculty', category: 'clinical_guide', language: 'en', pages: 320, fileSize: '10 MB', format: 'pdf', description: '50 detailed clinical cases across all 8 specialties — Kayachikitsa (15), Panchakarma (10), Prasuti Tantra (8), Kaumarabhritya (5), Shalya (4), Shalakya (3), Agada (3), Rasayana (2). Each case: presentation, examination, Ayurvedic + modern assessment, treatment protocol with exact doses, follow-up timeline, outcome, and discussion of clinical learning points. Modern co-management integrated where indicated. Real cases with anonymised patient data.', tags: ['clinical', 'case-studies', 'practical', 'BAMS'] },
]

export const EBOOK_SLUGS = EBOOKS.map((e) => e.slug)
