export type InterviewQA = { q: string; a: string; category: string }

export const QUESTIONS: InterviewQA[] = [
  // General Ayurveda (10)
  { category: 'General', q: 'Walk me through your background and why you chose Ayurveda.', a: 'Keep this to 90 seconds. Cover: BAMS college + year, what drew you to Ayurveda specifically (classical interest vs family tradition vs clinical exposure), one defining clinical experience, current specialisation focus, what you\'re looking for next. Be specific, not generic.' },
  { category: 'General', q: 'How do you stay updated in Ayurveda?', a: 'Mention 2-3 concrete sources: classical text re-reading (Charaka, Ashtanga Hridaya), modern Ayurveda research journals (AYU Journal, JREIM), CME programs, AyurConnect resources, peer discussion groups, conferences (CCRAS, NCISM events). Show ongoing learning.' },
  { category: 'General', q: 'What is your understanding of integration between Ayurveda and modern medicine?', a: 'Position: both have strengths. Ayurveda excels in chronic disease, lifestyle disorders, integrative wellness. Modern medicine is essential for acute care, surgery, infectious disease, end-stage organ failure. Best outcomes come from co-management. Cite an example: T2DM management with metformin + Ayurveda lifestyle program, RA on methotrexate with adjunctive amavata protocol.' },
  { category: 'General', q: 'Tell me about a difficult patient case and what you learned.', a: 'STAR method: Situation (brief patient profile + presentation), Task (your clinical challenge), Action (specific Ayurveda assessment + treatment chosen + why), Result (outcome + follow-up), Learning (what you\'d do differently). Pick a case showing clinical reasoning + humility.' },
  { category: 'General', q: 'How do you assess agni in a new patient?', a: 'Multi-dimensional: appetite pattern (regular vs irregular vs absent), bowel pattern (single morning vs multiple vs alternating), tongue coating (clear vs heavy white = ama), post-meal heaviness vs lightness, body weight trend, mental energy after meals. Classify into sama / vishama / tikshna / manda agni — drives treatment decisions.' },
  { category: 'General', q: 'How do you handle a patient who is on multiple modern medications?', a: 'Three-step: 1) Comprehensive drug review + identify potential herb-drug interactions. 2) Coordinate with prescribing physician — never abrupt withdrawal of modern meds. 3) Start gentle Ayurveda; gradually taper modern meds based on objective improvement (HbA1c, BP readings, symptom scores). Document everything.' },
  { category: 'General', q: 'Explain pragnaparadha in your own words.', a: '"Failure of intellect" — knowingly doing what one knows is harmful. Charaka considers this the most important cause of disease — more than time-related or sensory errors. Example: a doctor knowing a patient\'s prakriti and still prescribing aggravating food, or a patient continuing harmful habits despite knowing the consequences. Recognising pragnaparadha in patients shapes the chikitsa-chatushpada role.' },
  { category: 'General', q: 'How do you decide between shamana and shodhana for a chronic condition?', a: 'Assessment criteria: patient bala (strength) — strong bala allows shodhana; weak bala = shamana. Doshic state — sthana-samshraya phase favours shamana; prasara phase favours shodhana. Sadhyata: sukha/krichhsadhya may permit shodhana; yapya often only allows shamana. Ama presence — must remove ama before shodhana. Patient willingness + time available — shodhana requires committed inpatient time.' },
  { category: 'General', q: 'How do you explain Ayurveda treatment to a sceptical patient?', a: 'Don\'t over-claim. Acknowledge their concerns. Frame Ayurveda as systematic — emphasise classical reasoning, individualised treatment, long-term outcomes. Cite modern research where available (e.g., turmeric anti-inflammatory studies). Set realistic timelines (chronic disease takes months, not weeks). Offer co-management with their existing care provider. Build trust through small early wins.' },
  { category: 'General', q: 'What are your salary expectations?', a: 'Research the role + market first. Give a range, not a number: "Based on my experience and current GCC market data, I\'m looking at AED 12,000–16,000 / month range." Add non-cash components: housing allowance, transport, end-of-service, indemnity coverage, CME budget, annual home flights. Be ready to discuss flexibly.' },

  // Clinical scenarios (5)
  { category: 'Clinical', q: 'A 50-year-old male with HbA1c 9.5, BMI 32, diabetic neuropathy. Walk me through your treatment plan.', a: 'Stage: vataja prameha (madhumeha) with complications — yapya, not sukha-sadhya. Plan: 1) Aggressive lifestyle (diet 1200 kcal, daily 45-min walk, sleep regulation). 2) Co-manage with endocrinology — likely add second-line modern agent. 3) Ayurveda: vijayasara kashaya, methika, ashwagandha for insulin sensitivity. 4) Address neuropathy: ksheera-bala + mahanarayana for nerve health, gentle abhyanga. 5) Monthly HbA1c + foot exam. Set expectation: yapya = lifelong management, gradual improvement.' },
  { category: 'Clinical', q: 'A pregnant woman in 3rd trimester with severe constipation. What do you recommend?', a: 'Strict shodhana contraindicated. Conservative measures: 1) Dietary fibre (cooked vegetables, ghee in food, soaked dates + raisins). 2) Adequate fluids — warm water. 3) Castor oil 5ml at night IS contraindicated in late pregnancy (uterine stimulation). 4) Gentle anuvasana basti with bala-taila is permitted in 8-9th month. 5) Triphala in low dose is acceptable. 6) Address position + lifestyle. 7) Refer for obstetric assessment if severe.' },
  { category: 'Clinical', q: 'Patient with chronic RA on methotrexate wants to add Ayurveda. How do you approach?', a: 'Step 1: Never stop methotrexate abruptly. Confirm with rheumatologist. Step 2: Amavata samprapti reading — likely ama + vata. Address ama first: langhana + deepana-pachana for 3 weeks. Step 3: After ama clears, add rasna saptaka kashayam, simhanada guggulu. Step 4: Carefully consider basti only after stable. Step 5: Monthly ESR/CRP monitoring. Step 6: After 3-6 months stable, discuss methotrexate dose reduction with rheumatologist. Long-term: rasayana with ashwagandha + bala.' },
  { category: 'Clinical', q: 'Newly diagnosed type 2 diabetes patient, HbA1c 7.5, BMI 27, no complications. Best approach?', a: 'Sukha-sadhya stage — high reversal potential. Approach: 1) Aggressive lifestyle intervention (800-1200 kcal, brisk walking 45 min daily, sleep 10:30 PM). 2) Strict dietary protocol. 3) Add metformin 500mg bd (don\'t skip — modern standard). 4) Ayurveda: vijayasara kashaya, methika seeds, gymnema. 5) Quarterly HbA1c monitoring. Target: HbA1c <6.5%, metformin dose reduction over 12 months. Honesty: many patients can reverse to pre-diabetes with strict adherence; some need lifelong management.' },
  { category: 'Clinical', q: 'Patient with chronic sciatica, MRI shows L5-S1 disc bulge, no red flags. How would you proceed?', a: 'Gridhrasi with disc origin — sadhya. Plan: 1) Confirm no red flags (cauda equina, progressive deficit). 2) Acute pain control: bed rest, hot fomentation, castor oil internally. 3) Snehapana protocol (5 days). 4) Vati basti — single high-volume basti for severe sciatica. 5) Yoga basti 8-day protocol. 6) Continued kati basti + abhyanga. 7) Address ergonomic/lifestyle factors. 8) Yoga + pranayama. 9) Set timeline: 4-12 weeks for significant improvement. Refer for surgery only if progressive neurological deficit.' },

  // GCC/UAE (5)
  { category: 'GCC', q: 'Are you DHA / DOH / MOH licensed?', a: 'Be specific. If licensed: state the specific license (DHA, DOH, MOHAP) + active status + renewal date. If in process: state where you are (Dataflow PSV submitted, Prometric scheduled, exemption applied). If not yet started: outline your timeline (Dataflow → exam → application). Don\'t bluff.' },
  { category: 'GCC', q: 'How would you handle a patient who refuses pork-based gelatin in our formulations?', a: 'Cultural sensitivity is essential. 1) Acknowledge their concern. 2) Identify the formulation and check if alternatives exist (vegetable-based gelatin substitutes, plant-source preparations). 3) For specific formulations like Mahanarayana taila, classical preparations don\'t contain pork — verify supplier ingredients. 4) Offer alternative dosage form (tablet vs liquid, churnam vs vati). 5) If genuinely no alternative, respect the patient\'s choice and recommend modified protocol. UAE patients\' religious requirements come first.' },
  { category: 'GCC', q: 'What\'s your experience with Ramadan adjustment for chronic patients?', a: 'Ramadan adjustment for: 1) Diabetes patients — meal-timing modifications, lower-intensity medication during fasting, post-iftar full-dose. Glucose monitoring more frequent. 2) Hypertension — similar consideration for medication timing. 3) Chronic herbal regimens — typically maintained but adjusted for iftar/sehri timing. 4) Educate patient: emergency signs to break fast. 5) Coordinate with their existing doctor. Always respect their religious commitment.' },
  { category: 'GCC', q: 'How do you handle Insurance + Ayurveda in Dubai?', a: 'Dubai insurance landscape varies: 1) Some insurers (e.g., Niva Bupa, Star Health) cover Ayurveda consultations at DHA-licensed facilities. 2) Coverage usually for outpatient consultations + diagnostics; not all medications. 3) Maintain documentation: consultation notes, prescription, ICD-coded diagnosis (use Ayurveda + modern correlated codes). 4) Patient is informed about out-of-pocket likely portions before treatment. 5) Cash + insurance reconciliation handled by clinic admin.' },
  { category: 'GCC', q: 'A patient asks about combining Ayurveda with their existing modern medication. What\'s your approach?', a: '1) Acknowledge their existing prescriptions — never dismiss modern medicine. 2) Confirm with their prescribing physician. 3) Review for herb-drug interactions (e.g., turmeric + warfarin = bleeding risk; ashwagandha + thyroid meds = adjustment needed). 4) Start with low-risk Ayurveda (general rasayanas, lifestyle changes). 5) Monitor labs + symptoms. 6) Gradually titrate modern medications down only with objective improvement + specialist consult. 7) Document everything.' },

  // Hospital / Academic (5)
  { category: 'Hospital', q: 'How would you contribute to teaching at our college?', a: 'Specific examples: 1) Update lecture materials with classical + modern integration. 2) Introduce clinical case-based discussions vs pure didactic. 3) Establish a structured BAMS internship rotation with clear competency benchmarks. 4) Initiate a journal club for evidence-based Ayurveda. 5) Mentor MD students through research protocols. 6) Contribute to NCISM curriculum updates. Bring specific topics you\'d teach.' },
  { category: 'Hospital', q: 'Describe your approach to clinical research as an academician.', a: 'Pragmatic: 1) Start with clinical audits (retrospective case series in your specialty). 2) Single-arm prospective cohorts on classical protocols. 3) Eventually RCT for established interventions. 4) Always with institutional ethics committee + protocol publication. 5) Publish in indexed journals (AYU, JREIM). 6) Encourage PG students to do meaningful research, not just degree completion. Show familiarity with CCRAS research protocols + NCISM guidance.' },
  { category: 'Hospital', q: 'Tell me about a time you handled a clinical conflict.', a: 'Pick a real example. Frame: 1) Situation (who, what, where). 2) The conflict (e.g., disagreement on treatment between you + senior, or patient-family conflict). 3) Your specific actions (active listening, consulting evidence, presenting alternative options). 4) Resolution (mutual decision, patient outcome). 5) Reflection (what you\'d do differently, lesson). Show diplomacy + clinical reasoning + ego-management.' },
  { category: 'Hospital', q: 'How would you handle a non-compliant patient?', a: '1) Don\'t scold. Explore root causes (financial, lifestyle, family dynamics, fear, lack of understanding). 2) Reframe treatment to be more accessible — shorter duration, fewer medications, lifestyle as primary. 3) Use family for accountability. 4) Set realistic small goals. 5) Document refusals; don\'t over-document blame. 6) Refer to counselling if mental health barrier. 7) Sometimes acknowledge: not every patient is treatable; respect autonomy.' },
  { category: 'Hospital', q: 'Where do you see yourself in 5 years?', a: 'Be specific + realistic. Examples: "Senior consultant at your hospital, established clinical practice in [specialty], 2-3 publications in indexed journals, mentor to junior doctors, possibly leading a specialty clinic within the hospital." Tie ambitions to their role. Avoid: "I\'ll be running my own hospital" (signals you\'re leaving soon) or "Just doing the same role" (signals lack of ambition).' },

  // Telemedicine (5)
  { category: 'Telemedicine', q: 'How is telemedicine consultation different from in-person practice?', a: 'Differences: 1) Loss of pulse + tongue + palpation — relies more on history + visual assessment + patient self-report. 2) Best for chronic, slow-progressing conditions (Vatic, hormonal, lifestyle); poor for acute or physical-exam-dependent presentations. 3) Documentation must be more detailed since patient may consult others. 4) Prescription must be deliverable + safe without supervision. 5) Follow-up cadence is critical — most patients drop after first consult. 6) Builds longer-term relationships with chronic patients.' },
  { category: 'Telemedicine', q: 'What platforms have you used and which do you prefer?', a: 'Be specific: 2-3 platforms (Practo, Tata 1mg, Apollo 24/7, AyurConnect, own website). Compare on: patient mix, commission structure (15-30%), interface quality, prescription delivery, payment reliability, dispute resolution. State your preference + reasoning. Avoid speaking poorly of platforms — neutral comparison.' },
  { category: 'Telemedicine', q: 'How do you handle a patient where you\'re uncertain about diagnosis remotely?', a: '1) Acknowledge uncertainty to the patient honestly. 2) Recommend in-person consultation with a local doctor for examination. 3) Provide preliminary supportive care (rest, hydration, dietary measures). 4) Identify red flags clearly. 5) Document the uncertainty + referral recommendation. 6) Don\'t prescribe medications when uncertain — this is a key safety boundary. Remote consultation has limits; recognising them shows clinical maturity.' },
  { category: 'Telemedicine', q: 'How do you build a sustainable telemedicine practice?', a: '1) Specialise — generalist telemedicine struggles; specialty (e.g., chronic skin, women\'s health, postpartum) builds reputation. 2) Treatment packages > one-off consults — 3-month protocols with structured follow-up. 3) Focus on chronic conditions with high repeat rate. 4) Strong digital presence: Google Business Profile, social proof, patient testimonials. 5) Cross-platform — combination of aggregator + own website. 6) Hybrid physical + telemedicine model often most stable.' },
  { category: 'Telemedicine', q: 'What\'s your experience with cross-border telemedicine?', a: 'Be honest. Cross-border (Indian doctor → UAE/UK/US patient) has regulatory complexity. Discuss: 1) Many platforms classify these as wellness consultations to avoid medical regulatory issues. 2) Don\'t diagnose or prescribe across borders if license doesn\'t cover. 3) Many doctors position as wellness coach for international patients. 4) UAE specifically has tightening rules. 5) Compliance + clarity prevent regulatory problems later. If you have specific cross-border experience, frame within these constraints.' },
]
