export type AssessmentMcq = { q: string; options: { A: string; B: string; C: string; D: string }; correct: 'A'|'B'|'C'|'D'; explanation: string }

export type Assessment = {
  slug: string
  name: string
  specialization: string
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  durationMin: number
  passingScore: number
  description: string
  rules: string[]
  questions: AssessmentMcq[]
}

export const ASSESSMENTS: Assessment[] = [
  {
    slug: 'panchakarma-fundamentals',
    name: 'Panchakarma Fundamentals',
    specialization: 'Panchakarma',
    difficulty: 'intermediate',
    durationMin: 30,
    passingScore: 70,
    description: 'Assess your understanding of the 5 classical Panchakarma procedures — indications, contraindications, complete protocols, and complication management.',
    rules: ['20 questions in 30 minutes', 'Pass mark: 70%', 'No going back to previous questions', 'Certificate awarded on passing'],
    questions: [
      { q: 'Samyak vamana is characterized by how many vegas?', options: { A: '3-4', B: '4-5', C: '6-8', D: '10-12' }, correct: 'C', explanation: '6-8 vegas = samyak vamana. <6 = ayoga; >8 = atiyoga.' },
      { q: 'Snehapana ascending dose protocol typically lasts:', options: { A: '3 days', B: '5-7 days', C: '14 days', D: '21 days' }, correct: 'B', explanation: 'Snehapana: 5-7 days, starting 30ml, increasing to 100-150ml or until samyak signs.' },
      { q: 'Karma basti = how many bastis?', options: { A: '8', B: '15', C: '30', D: '60' }, correct: 'C', explanation: 'Karma basti = 30 bastis (12 niruha + 16 anuvasana + 2 buffer).' },
      { q: 'Yoga basti consists of:', options: { A: '5 bastis', B: '8 bastis', C: '15 bastis', D: '30 bastis' }, correct: 'B', explanation: '8 bastis (3 niruha + 5 anuvasana).' },
      { q: 'Anuvasana basti volume:', options: { A: '30-50ml', B: '60-180ml', C: '300-600ml', D: '1L+' }, correct: 'B', explanation: '60-180ml retained overnight or 4-6 hours.' },
      { q: 'Sansarjana karma duration:', options: { A: '3 days', B: '5 days', C: '7 days', D: '14 days' }, correct: 'C', explanation: '7-day graduated diet: peya → vilepi → akrita/krita yusha → akrita/krita mansa rasa → normal.' },
      { q: 'Sirobasti is performed on:', options: { A: 'Head with leather cap', B: 'Stomach', C: 'Joints', D: 'Eyes' }, correct: 'A', explanation: 'Leather cap on head with medicated oil retained 30-90 min.' },
      { q: 'Pizhichil is which Kerala therapy?', options: { A: 'Steam', B: 'Continuous oil pouring with massage', C: 'Powder massage', D: 'Compress' }, correct: 'B', explanation: 'Continuous oil pouring over body with simultaneous gentle massage — signature Kerala vatavyadhi therapy.' },
      { q: 'Absolute contraindication to vamana:', options: { A: 'Mild kapha asthma', B: 'Pregnancy + bleeding disorder', C: 'Mild obesity', D: 'Chronic sinusitis' }, correct: 'B', explanation: 'Pregnancy, bleeding disorders, recent MI, severe debility — absolute contraindications.' },
      { q: 'Vati basti is used primarily for:', options: { A: 'Routine maintenance', B: 'Severe sciatica — single high-volume basti', C: 'Daily anti-aging', D: 'Children' }, correct: 'B', explanation: 'Single basti of 600ml with oil + erandamoola + bala + dashamoola — classical for severe sciatica.' },
      { q: 'Virechana is primarily indicated for:', options: { A: 'Vata disorders', B: 'Pitta disorders', C: 'Kapha disorders', D: 'Pure vata-kapha' }, correct: 'B', explanation: 'Virechana = therapeutic purgation. Primary for pittaja roga and pitta-dominated pitta-kapha.' },
      { q: 'Nasya karma is most useful for:', options: { A: 'Lower extremity disorders', B: 'Urdhvajatru (above clavicle) disorders', C: 'Cardiac disease', D: 'Diabetes' }, correct: 'B', explanation: 'Nasya — direct effect on urdhvajatru: sinusitis, headache, migraine, neuropathy, voice disorders.' },
      { q: 'Atiyoga of vamana presents with:', options: { A: 'Severe weakness, hypotension, dehydration', B: 'Constipation', C: 'Fever', D: 'Skin rash' }, correct: 'A', explanation: 'Excess vamana — severe dehydration, hypotension, weakness. Stop, IV fluids, rest.' },
      { q: 'Madhuyashti is used as:', options: { A: 'Vamanopaga (supporting vamana)', B: 'Virechanopaga only', C: 'Pure anti-pitta', D: 'Cardiac tonic only' }, correct: 'A', explanation: 'Madhuyashti is classical vamanopaga — supports vamana via emetic enhancement.' },
      { q: 'Erandamoola taila is best for:', options: { A: 'Anuvasana basti for severe vata', B: 'Vamana', C: 'Nasya', D: 'Eye drops' }, correct: 'A', explanation: 'Erandamoola taila (castor root oil) — classic anuvasana basti taila for severe vatavyadhi + low back pain.' },
      { q: 'Raktamokshana is contraindicated in:', options: { A: 'Pittaja skin disorders', B: 'Severe anemia + pregnancy', C: 'Inflammatory joint disease', D: 'Mild eczema' }, correct: 'B', explanation: 'Anemia, bleeding disorders, pregnancy, severe debility — contraindicated.' },
      { q: 'Pre-procedure assessment for Panchakarma must include:', options: { A: 'Patient bala + agni + sahishnuta + dosha', B: 'Only blood pressure', C: 'Only blood tests', D: 'Just clinical impression' }, correct: 'A', explanation: 'Classical assessment: bala, agni, sahishnuta, dosha, satmya, vyadhi-bala — multidimensional patient evaluation.' },
      { q: 'Snigdha avastha (samyak snigdha) signs include:', options: { A: 'Constipation', B: 'Mridu koshtha + soft skin + light feeling', C: 'Diarrhea + nausea', D: 'Fever' }, correct: 'B', explanation: 'Samyak snigdha: soft bowel (mridu koshtha), soft skin, lightness, mild glow, vatanulomana.' },
      { q: 'Best time of day for vamana karma:', options: { A: 'Late night', B: 'Early morning, empty stomach', C: 'Post-lunch', D: 'Any time' }, correct: 'B', explanation: 'Vamana performed early morning on empty stomach — agni is at appropriate state for kapha mobilisation.' },
      { q: 'Most important factor for safe Panchakarma:', options: { A: 'Use most expensive medicines', B: 'Patient selection + supervision + monitoring', C: 'Always do all 5 procedures', D: 'Maximum dose always' }, correct: 'B', explanation: 'Patient selection (sadhyata), proper supervision, and vital sign monitoring are critical for safety.' },
    ],
  },
  {
    slug: 'kayachikitsa-essentials',
    name: 'Kayachikitsa Essentials',
    specialization: 'Kayachikitsa',
    difficulty: 'intermediate',
    durationMin: 30,
    passingScore: 70,
    description: 'Test your foundational understanding of Ayurvedic internal medicine — major diseases, classical treatment protocols, and modern integration.',
    rules: ['20 questions in 30 minutes', 'Pass mark: 70%', 'Certificate awarded on passing'],
    questions: [
      { q: 'Charaka enumerates how many vatavyadhi?', options: { A: '40', B: '60', C: '80', D: '100' }, correct: 'C', explanation: '80 vatavyadhi including paksha-aghata, ardita, gridhrasi, sandhigatavata.' },
      { q: 'Total subtypes of prameha per Charaka:', options: { A: '10', B: '15', C: '20', D: '25' }, correct: 'C', explanation: '20 subtypes: 10 kaphaja + 6 pittaja + 4 vataja (madhumeha among vataja).' },
      { q: 'Amavata samprapti involves:', options: { A: 'Pitta-rakta', B: 'Vata + ama in sandhis', C: 'Kapha-meda only', D: 'Pure pitta' }, correct: 'B', explanation: 'Manda agni → ama → vyana vayu carries ama to sandhis → ama-vata combination.' },
      { q: 'First-line in amavata is:', options: { A: 'Snehapana', B: 'Langhana + deepana-pachana', C: 'Raktamokshana', D: 'Vamana' }, correct: 'B', explanation: 'Always remove ama first. Snehapana before ama removal worsens disease.' },
      { q: 'Sandhigatavata corresponds to:', options: { A: 'Rheumatoid arthritis', B: 'Osteoarthritis', C: 'Gout', D: 'Septic arthritis' }, correct: 'B', explanation: 'Sandhigatavata = joint pain due to vata involvement = osteoarthritis modern.' },
      { q: 'Madhumeha is which dosha type?', options: { A: 'Kaphaja', B: 'Pittaja', C: 'Vataja (late stage)', D: 'Sannipata' }, correct: 'C', explanation: 'Madhumeha is the 4th vataja prameha — late-stage T2DM with wasting features.' },
      { q: 'Tamak shwasa primary management:', options: { A: 'Vamana + kapha-shamana', B: 'Virechana only', C: 'Basti only', D: 'Raktamokshana' }, correct: 'A', explanation: 'Vamana primary for kaphaja shwasa, followed by pippali + vasa + kantakari.' },
      { q: 'Pandu primary chikitsa principle:', options: { A: 'Iron alone', B: 'Rakta-vardhana + agni correction', C: 'Vamana', D: 'Strict bed rest' }, correct: 'B', explanation: 'Pandu: rakta-vardhana (loha bhasma, mandura) + agni correction (deepana-pachana).' },
      { q: 'Sthaulya (obesity) primary treatment:', options: { A: 'Lekhana + langhana + agni correction', B: 'Excess eating', C: 'Just exercise', D: 'Surgical' }, correct: 'A', explanation: 'Lekhana (scraping) herbs + langhana + agni correction + lifestyle modification.' },
      { q: 'Vyana vayu function:', options: { A: 'Digestion', B: 'Speech', C: 'Circulation throughout body', D: 'Excretion only' }, correct: 'C', explanation: 'Vyana vayu — located in hridaya, circulates rasa-rakta throughout the body.' },
      { q: 'Apana vayu controls:', options: { A: 'Speech', B: 'Excretion (urine, stool, ejaculation, parturition)', C: 'Digestion', D: 'Cardiac activity' }, correct: 'B', explanation: 'Apana — located in pakvashaya, governs downward expulsion functions.' },
      { q: 'Vatavyadhi general treatment includes:', options: { A: 'Snehana + swedana + basti', B: 'Langhana + raktamokshana', C: 'Vamana + virechana', D: 'Cold therapy' }, correct: 'A', explanation: 'Snehana + swedana + basti — the 3 primary treatments. Basti = ardha chikitsa for vata.' },
      { q: 'Hridroga panchaka (5 types) — which is NOT included?', options: { A: 'Vataja', B: 'Pittaja', C: 'Sannipataja', D: 'Aagantuja' }, correct: 'D', explanation: '5 hridroga: vataja, pittaja, kaphaja, sannipataja, krimija. Aagantuja is broader.' },
      { q: 'Pakvashayagata vata typically presents with:', options: { A: 'Only headache', B: 'Constipation + adhmana + shoola', C: 'Joint stiffness', D: 'Cardiac symptoms' }, correct: 'B', explanation: 'Vata in large intestine: constipation, distension, pain, gas formation.' },
      { q: 'Avalambaka kapha located in:', options: { A: 'Amashaya', B: 'Hridaya + urah', C: 'Sandhi', D: 'Tongue' }, correct: 'B', explanation: 'Avalambaka kapha — hridaya, urah (chest). Supports all other kapha.' },
      { q: 'Atrtisara (chronic diarrhoea) most commonly due to:', options: { A: 'Kaphaja agni', B: 'Vishama + manda agni → ama → grahani', C: 'Tikshna agni only', D: 'Pittaja prameha' }, correct: 'B', explanation: 'Chronic diarrhoea: vishama + manda agni → ama → grahani involvement.' },
      { q: 'Madhyama roga marga involves:', options: { A: 'Skin + rakta', B: 'Marma + sandhi + asthi', C: 'Kostha', D: 'Manas' }, correct: 'B', explanation: 'Madhyama marga: marma, sandhi, asthi.' },
      { q: 'Ardita corresponds to:', options: { A: 'Hemiplegia', B: 'Bell\'s palsy / facial palsy', C: 'Migraine', D: 'Tetanus' }, correct: 'B', explanation: 'Ardita = facial palsy. Treatment: nasya, abhyanga, basti.' },
      { q: 'Gridhrasi corresponds to:', options: { A: 'Migraine', B: 'Sciatica', C: 'Facial palsy', D: 'Carpal tunnel' }, correct: 'B', explanation: 'Gridhrasi = sciatica. Treatment: vati basti, erandapaka, masha balatailam.' },
      { q: 'Best initial treatment for newly-diagnosed type 2 diabetes (HbA1c 7.0):', options: { A: 'Vamana immediately', B: 'Lifestyle + Vijayasara + co-management with endo', C: 'Surgical', D: 'No treatment' }, correct: 'B', explanation: 'Early T2DM is sukha-sadhya. Aggressive lifestyle + vijayasara + co-managed metformin.' },
    ],
  },
  {
    slug: 'dravyaguna-knowledge',
    name: 'Dravyaguna Knowledge',
    specialization: 'Dravyaguna',
    difficulty: 'beginner',
    durationMin: 25,
    passingScore: 60,
    description: 'Test your knowledge of Ayurvedic pharmacology fundamentals — rasa panchaka, dashemani, classical herbs and their actions.',
    rules: ['15 questions in 25 minutes', 'Pass mark: 60%'],
    questions: [
      { q: 'How many components in rasa panchaka?', options: { A: '3', B: '4', C: '5', D: '6' }, correct: 'C', explanation: 'Rasa, Guna, Veerya, Vipaka, Prabhava.' },
      { q: 'How many rasas?', options: { A: '5', B: '6', C: '7', D: '8' }, correct: 'B', explanation: '6 rasas: madhura, amla, lavana, katu, tikta, kashaya.' },
      { q: 'Madhura rasa = which mahabhutas?', options: { A: 'Prithvi + Apa', B: 'Apa + Tejas', C: 'Vayu + Tejas', D: 'Akasha + Vayu' }, correct: 'A', explanation: 'Madhura — prithvi + apa.' },
      { q: 'Veerya types classically:', options: { A: '2 (sheeta + ushna)', B: '4', C: '6', D: '8' }, correct: 'A', explanation: 'Binary sheeta-ushna is primary clinically.' },
      { q: 'Triphala = ?', options: { A: 'Haritaki + Amalaki + Vibhitaki', B: 'Pippali + Maricha + Shunthi', C: 'Brahmi + Bala + Vidari', D: 'Lodhra + Tagara + Mocha' }, correct: 'A', explanation: 'Triphala = 3 fruits — haritaki, amalaki, vibhitaki.' },
      { q: 'Charaka enumerates how many dashemani?', options: { A: '20', B: '30', C: '50', D: '100' }, correct: 'C', explanation: '50 dashemani × 10 herbs = 500 cardinal herbs.' },
      { q: 'Rasayana dashemani includes:', options: { A: 'Triphala + ashwagandha + brahmi', B: 'Pippali + maricha + shunthi', C: 'Bala + atibala + nagabala', D: 'Eranda + tila + sarshapa' }, correct: 'A', explanation: 'Rasayana dashemani: triphala + brahmi + mandukaparni + ashwagandha + bala + shilajatu.' },
      { q: 'Danti virechana action through:', options: { A: 'Rasa', B: 'Veerya', C: 'Vipaka', D: 'Prabhava' }, correct: 'D', explanation: 'Danti acts by prabhava — specific unique action.' },
      { q: 'Tikta rasa mahabhuta:', options: { A: 'Vayu + Akasha', B: 'Vayu + Prithvi', C: 'Vayu + Tejas', D: 'Tejas + Akasha' }, correct: 'A', explanation: 'Tikta — vayu + akasha. Pacifies pitta + kapha; aggravates vata.' },
      { q: 'Vijayasara primarily used for:', options: { A: 'Hridroga', B: 'Prameha', C: 'Pandu', D: 'Shvitra' }, correct: 'B', explanation: 'Vijayasara — classical first-line for prameha.' },
      { q: 'Gymnema sylvestre acts on diabetes by:', options: { A: 'Insulin secretion', B: 'Blocking sweet taste + glucose absorption', C: 'Fat absorption', D: 'Thyroid activation' }, correct: 'B', explanation: 'Gudmar — blocks sweet taste, reduces glucose absorption.' },
      { q: 'Bhavaprakasha Nighantu by:', options: { A: 'Charaka', B: 'Sushruta', C: 'Bhavamishra', D: 'Vagbhata' }, correct: 'C', explanation: 'Bhavamishra (~16th C).' },
      { q: 'Madhumeha treatment dravyas:', options: { A: 'Vijayasara, methi, gymnema', B: 'Vamana herbs only', C: 'Brimhana herbs', D: 'Cooling herbs only' }, correct: 'A', explanation: 'Vijayasara + methika + gudmar are evidence-supported.' },
      { q: 'Vipaka of madhura rasa typically:', options: { A: 'Katu', B: 'Amla', C: 'Madhura', D: 'Mixed' }, correct: 'C', explanation: 'Madhura + amla + lavana → madhura vipaka.' },
      { q: 'Maha-tikta ghrita used in:', options: { A: 'Skin disorders, jaundice, chronic toxicity', B: 'Cardiac only', C: 'Fertility', D: 'Insomnia only' }, correct: 'A', explanation: 'Mahatikta ghrita — kushtha, kamla, dushivisha.' },
    ],
  },
  {
    slug: 'ayurveda-clinical-reasoning',
    name: 'Ayurveda Clinical Reasoning',
    specialization: 'Clinical',
    difficulty: 'advanced',
    durationMin: 30,
    passingScore: 75,
    description: 'Advanced clinical case scenarios — diagnosis, treatment selection, and integration with modern medicine. Tests your ability to reason from samprapti.',
    rules: ['15 questions in 30 minutes', 'Pass mark: 75%', 'Case-based reasoning'],
    questions: [
      { q: '45F with morning stiffness >2hr + symmetrical joint pain + ESR 64. First Ayurvedic step:', options: { A: 'Snehapana immediately', B: 'Langhana + deepana-pachana to address ama', C: 'Vamana', D: 'Raktamokshana' }, correct: 'B', explanation: 'Amavata samprapti has ama at root — must remove ama BEFORE snehapana.' },
      { q: 'Newly diagnosed T2DM, HbA1c 7.0, BMI 28, no complications. Best initial approach:', options: { A: 'Vamana', B: 'Lifestyle + Vijayasara + supervised metformin', C: 'Surgical', D: 'No treatment yet' }, correct: 'B', explanation: 'Sukha-sadhya stage. Lifestyle + Ayurveda + standard care = best outcomes.' },
      { q: 'Patient with low back pain radiating to leg + MRI shows L5-S1 disc bulge + positive SLR. Sadhyata:', options: { A: 'Sukha-sadhya', B: 'Kricchsadhya if no neuro deficit', C: 'Yapya only', D: 'Asadhya' }, correct: 'B', explanation: 'Gridhrasi with disc involvement, no progressive neuro deficit — kricchsadhya, sadhya overall.' },
      { q: 'Pregnant woman, 7 months, comes with chronic constipation. Best Ayurvedic approach:', options: { A: 'Strict virechana', B: 'Gentle anuvasana basti + dietary fiber + warm water', C: 'No treatment', D: 'Castor oil orally' }, correct: 'B', explanation: 'Strict shodhana contraindicated; gentle anuvasana basti permitted, plus dietary measures.' },
      { q: 'For amavata patient, snehapana before ama clearance:', options: { A: 'Always indicated', B: 'Worsens disease', C: 'No effect', D: 'Only at low dose' }, correct: 'B', explanation: 'Snehapana with active ama traps ama deeper. Always langhana-deepana-pachana first.' },
      { q: 'Asthma patient on ICS-LABA. You start Ayurveda. Correct action:', options: { A: 'Stop inhaler immediately', B: 'Continue inhaler; add Ayurveda; reduce ICS gradually under pulmonologist consult only after stable improvement', C: 'Double inhaler dose', D: 'Stop everything' }, correct: 'B', explanation: 'Never abruptly stop ICS. Integrate Ayurveda, monitor, then taper modern medication slowly under specialist guidance.' },
      { q: 'Patient with type 2 DM + HbA1c 9.2 + retinopathy + neuropathy:', options: { A: 'Sukha-sadhya', B: 'Yapya — manage, not cure', C: 'Kricchsadhya', D: 'Asadhya' }, correct: 'B', explanation: 'Advanced T2DM with complications = yapya. Manage, control, prevent progression.' },
      { q: 'Pandu patient, vegetarian, heavy menstrual bleeding. First diagnostic step:', options: { A: 'Start Ayurveda directly', B: 'Confirm Hb + ferritin + GI losses + gynae assessment', C: 'Vamana', D: 'Snehapana' }, correct: 'B', explanation: 'Always diagnose the underlying cause: bleeding source, nutritional status, complete workup.' },
      { q: 'Vata-pitta prakriti patient with anxiety + insomnia + dryness. Choose:', options: { A: 'Cooling + grounding + snigdha herbs', B: 'Heating + stimulating', C: 'Cold therapy only', D: 'Astringent only' }, correct: 'A', explanation: 'Vata + pitta pacifying: snigdha-sheeta-laghu herbs, calm environment, regular schedule.' },
      { q: 'A pregnant woman with severe migraine — best approach:', options: { A: 'Strict shirovirechana', B: 'Mild local lepa + dietary measures + close monitoring; modern paracetamol if needed', C: 'Vamana', D: 'Strong analgesics' }, correct: 'B', explanation: 'Mild local Ayurveda + paracetamol (safe in pregnancy) + monitoring. Strict shodhana contraindicated.' },
      { q: 'Diabetic foot infection in advanced T2DM — most important:', options: { A: 'Refer for surgical/medical management; Ayurveda adjunctive', B: 'Ayurveda alone', C: 'Ignore', D: 'Vamana' }, correct: 'A', explanation: 'Active foot infection in DM = surgical/medical emergency. Refer; use Ayurveda for adjunctive wound healing + long-term management.' },
      { q: 'Sukha-sadhya disease characterized by:', options: { A: 'All 3 doshas + complications', B: 'Single dosha + recent onset + healthy patient', C: 'Lifelong control', D: 'Terminal' }, correct: 'B', explanation: 'Sukha-sadhya: single dosha, recent, healthy patient, no complications.' },
      { q: 'Best Ayurvedic approach for chronic psoriasis on modern biologics:', options: { A: 'Stop biologics', B: 'Continue biologics; add classical kushtha protocols (mahatikta ghrita, raktamokshana, kushthadi); slow tapering by dermatology', C: 'Vamana alone', D: 'Strict fast' }, correct: 'B', explanation: 'Integration — continue modern, layer Ayurveda, taper modern slowly under specialist guidance after Ayurveda gains traction.' },
      { q: 'Hypertensive patient on multiple antihypertensives. Starting Ayurveda:', options: { A: 'Stop all meds', B: 'Continue; add Sarpagandha + dietary measures; monitor BP daily; reduce modern meds slowly under cardiology', C: 'Add more modern meds', D: 'No Ayurveda' }, correct: 'B', explanation: 'Sarpagandha + lifestyle, monitor BP, taper modern drugs slowly with cardiology coordination.' },
      { q: 'Most important factor in good clinical Ayurveda outcomes:', options: { A: 'Most expensive medicines', B: 'Diagnosis + samprapti reasoning + sadhyata + patient compliance + lifestyle', C: 'High doses', D: 'Many medications' }, correct: 'B', explanation: 'Good clinical outcomes = correct diagnosis + samprapti understanding + realistic sadhyata + patient cooperation + lifestyle change.' },
    ],
  },
  {
    slug: 'dha-exam-readiness',
    name: 'DHA Exam Readiness Check',
    specialization: 'Licensing',
    difficulty: 'advanced',
    durationMin: 45,
    passingScore: 70,
    description: 'Assess your readiness for the DHA Prometric exam. Covers Ayurveda fundamentals, clinical scenarios, pharmacology, ethics, and Dubai healthcare regulations.',
    rules: ['25 questions in 45 minutes', 'Pass mark: 70% (DHA actual: 60%)', 'Bonus 15-min buffer'],
    questions: [
      { q: 'DHA Prometric exam pass mark:', options: { A: '50%', B: '60%', C: '70%', D: '75%' }, correct: 'B', explanation: 'DHA pass mark is 60%.' },
      { q: 'Number of questions in DHA Prometric:', options: { A: '50', B: '75', C: '100', D: '150' }, correct: 'C', explanation: '100 MCQs in 150 minutes.' },
      { q: 'PSV (Primary Source Verification) is via:', options: { A: 'Local DHA office', B: 'Dataflow', C: 'KSMC', D: 'Indian Embassy' }, correct: 'B', explanation: 'Dataflow conducts PSV for DHA. Takes 4-8 weeks.' },
      { q: 'DHA license is tied to:', options: { A: 'Freelance practice', B: 'A sponsoring facility', C: 'Government only', D: 'No restrictions' }, correct: 'B', explanation: 'DHA license is facility-bound — cannot freelance.' },
      { q: 'Exemption from DHA exam possible for:', options: { A: 'Anyone with BAMS', B: 'MD/MS Ayurveda + 5 years experience', C: 'Anyone with 1 year experience', D: 'No exemptions exist' }, correct: 'B', explanation: 'MD/MS Ayurveda + 5 years experience can apply for exam exemption.' },
      { q: 'Pre-DHA BLS certification must be from:', options: { A: 'Any provider', B: 'AHA / ARC / certain UAE providers', C: 'Indian providers only', D: 'No specific provider' }, correct: 'B', explanation: 'DHA accepts BLS from AHA, ARC, certain UAE-approved providers.' },
      { q: 'How many vatavyadhi per Charaka?', options: { A: '40', B: '60', C: '80', D: '100' }, correct: 'C', explanation: '80 vatavyadhi.' },
      { q: 'Samyak vamana = how many vegas?', options: { A: '3-5', B: '6-8', C: '10-12', D: '15+' }, correct: 'B', explanation: '6-8 vegas optimal.' },
      { q: 'Madhura rasa is composed of:', options: { A: 'Prithvi + Apa', B: 'Apa + Tejas', C: 'Vayu + Tejas', D: 'Akasha + Vayu' }, correct: 'A', explanation: 'Madhura — prithvi + apa.' },
      { q: 'Most important step before prescribing for any patient:', options: { A: 'Prakriti assessment + vikriti + sadhyata + drug-drug interactions', B: 'Quick prescription', C: 'Use trial-and-error', D: 'Follow protocol blindly' }, correct: 'A', explanation: 'Personalised medicine — comprehensive assessment first.' },
      { q: 'Triphala dose for adults:', options: { A: '1-2 g', B: '3-6 g', C: '10-15 g', D: '30 g' }, correct: 'B', explanation: 'Triphala — 3-6g at night for mild laxative + antioxidant effect.' },
      { q: 'Heavy menstrual bleeding (asrigdara) is:', options: { A: 'Vataja', B: 'Pittaja-rakta dushti', C: 'Kaphaja', D: 'Sannipata' }, correct: 'B', explanation: 'Pittaja with rakta dushti predominantly.' },
      { q: 'Garbhini paricharya 8th month — most important:', options: { A: 'Strict virechana', B: 'Anuvasana basti with bala-taila for delivery softening', C: 'Heavy meals', D: 'Intense exercise' }, correct: 'B', explanation: 'Anuvasana basti softens birth canal and prepares for labour.' },
      { q: 'Patient confidentiality in Dubai healthcare:', options: { A: 'Optional', B: 'Legally mandated; breach has penalties', C: 'For VIPs only', D: 'Only at request' }, correct: 'B', explanation: 'Dubai law mandates patient confidentiality.' },
      { q: 'For acute snake bite, primary first step:', options: { A: 'Ayurveda agada first', B: 'Reassure + immobilise + transport to hospital + ASV', C: 'Ignore', D: 'Apply tourniquet always' }, correct: 'B', explanation: 'ASV is first-line per IMA/WHO. Ayurveda agada adjunctive only.' },
      { q: 'Sannipataja jvara — highest:', options: { A: 'Survival rate', B: 'Mortality', C: 'Self-limiting', D: 'Mild course' }, correct: 'B', explanation: 'Sannipata jvara has highest mortality — often severe systemic infection.' },
      { q: 'Triavarjaneeya bhava — most important:', options: { A: 'Time', B: 'Pragnaparadha (intellectual error)', C: 'Senses', D: 'Sleep' }, correct: 'B', explanation: 'Pragnaparadha is the most important cause of disease per Charaka.' },
      { q: 'Stana shyandha (mastitis) primary treatment:', options: { A: 'Vamana', B: 'Local + systemic anti-inflammatory + galactogue', C: 'Raktamokshana', D: 'Basti' }, correct: 'B', explanation: 'Mastitis: combined local + systemic + galactogue (if breastfeeding continues).' },
      { q: 'Pakvashayagata vata symptoms:', options: { A: 'Headache only', B: 'Constipation + adhmana + shoola + gas', C: 'Joint stiffness', D: 'Cardiac' }, correct: 'B', explanation: 'Vata in pakvashaya = constipation, gas, distension, pain.' },
      { q: 'Most important factor for DHA exam success:', options: { A: 'Memorising', B: 'Conceptual understanding + clinical scenarios + practice MCQs', C: 'Last-minute cramming', D: 'Just intuition' }, correct: 'B', explanation: 'Concept + scenarios + practice. Cramming alone insufficient.' },
      { q: 'Patient with ramadan fasting — diabetes management:', options: { A: 'Stop all meds', B: 'Modify diet, schedule meds carefully, glucose monitoring, education', C: 'Ignore religion', D: 'Patient must not fast' }, correct: 'B', explanation: 'Culturally sensitive: medication timing modification + glucose monitoring + diet adjustment.' },
      { q: 'Visha chikitsa first step:', options: { A: 'Identify visha type', B: 'Local management + rapid systemic agada + transport to ER', C: 'Vamana always', D: 'Wait and watch' }, correct: 'B', explanation: 'Local first-aid + systemic + transport to ER/ASV facility.' },
      { q: 'Bhavaprakasha Nighantu author:', options: { A: 'Charaka', B: 'Sushruta', C: 'Bhavamishra', D: 'Vagbhata' }, correct: 'C', explanation: 'Bhavamishra ~16th century.' },
      { q: 'DHA renewal frequency:', options: { A: 'Every year', B: 'Every 2 years', C: 'Every 3 years', D: 'Lifetime' }, correct: 'A', explanation: 'Annual DHA license renewal with CME compliance.' },
      { q: 'Pre-renewal CME credits required:', options: { A: '0', B: '50/year', C: '100/year', D: '200/year' }, correct: 'B', explanation: '50 CME credits annually for DHA renewal.' },
    ],
  },
]

export const ASSESSMENT_SLUGS = ASSESSMENTS.map((a) => a.slug)
