export type Mcq = {
  id: string
  subjectSlug: string
  question: string
  options: { A: string; B: string; C: string; D: string }
  correct: 'A' | 'B' | 'C' | 'D'
  explanation: string
  difficulty: 'easy' | 'medium' | 'hard'
  reference?: string
}

export const MCQS: Mcq[] = [
  // ── Padartha Vigyana (10) ──────────────────────────────
  { id: 'pv1', subjectSlug: 'padartha-vigyana', question: 'How many padartha are described in Vaisheshika philosophy adopted by Charaka?', options: { A: '5', B: '6', C: '7', D: '9' }, correct: 'B', explanation: 'Vaisheshika lists 6 padartha: dravya, guna, karma, samanya, vishesha, samavaya. Charaka adopts this framework.', difficulty: 'easy', reference: 'Charaka Sutra 1' },
  { id: 'pv2', subjectSlug: 'padartha-vigyana', question: 'Dravya is samavayi karana of which padartha?', options: { A: 'Karma only', B: 'Guna only', C: 'Both guna and karma', D: 'Samanya' }, correct: 'C', explanation: 'Dravya is the inherent (samavayi) cause of both guna (qualities) and karma (actions). Without dravya, neither can exist.', difficulty: 'easy' },
  { id: 'pv3', subjectSlug: 'padartha-vigyana', question: 'How many gurvadi gunas are there?', options: { A: '10', B: '15', C: '20', D: '41' }, correct: 'C', explanation: '20 gurvadi gunas arranged as 10 binary pairs (guru-laghu, sheeta-ushna, etc.). 41 is the total of all gunas including sartha, paradi, vaisheshika, adhyatmika.', difficulty: 'easy' },
  { id: 'pv4', subjectSlug: 'padartha-vigyana', question: 'Which mahabhuta is dominant in akasha guna of shabda (sound)?', options: { A: 'Prithvi', B: 'Akasha', C: 'Vayu', D: 'Tejas' }, correct: 'B', explanation: 'Shabda is the sartha guna of akasha (space). Each mahabhuta has its specific sense object: akasha→shabda, vayu→sparsha, tejas→rupa, jala→rasa, prithvi→gandha.', difficulty: 'medium' },
  { id: 'pv5', subjectSlug: 'padartha-vigyana', question: 'Which of the following is NOT a paradi guna?', options: { A: 'Yukti', B: 'Snigdha', C: 'Sankhya', D: 'Samyoga' }, correct: 'B', explanation: 'Snigdha is a gurvadi guna. Paradi gunas (10) include para, apara, yukti, sankhya, samyoga, vibhaga, prithakta, parimana, sanskara, abhyasa.', difficulty: 'medium' },
  { id: 'pv6', subjectSlug: 'padartha-vigyana', question: 'Charaka enumerates how many nava karana dravyas?', options: { A: '5', B: '7', C: '9', D: '12' }, correct: 'C', explanation: '9 nava karana dravyas: 5 pancha mahabhuta + atma + manas + kala + dik.', difficulty: 'medium' },
  { id: 'pv7', subjectSlug: 'padartha-vigyana', question: 'The siddhanta "samanya samanyam vridhi, viparyaya vipariyat" describes:', options: { A: 'Tridosha theory', B: 'Samanya-Vishesha siddhanta', C: 'Sapta dhatu', D: 'Panchamahabhuta' }, correct: 'B', explanation: 'Similar dravyas/qualities increase samana dhatu/dosha; opposite decrease. Foundational treatment principle.', difficulty: 'medium', reference: 'Charaka Sutra 1/44' },
  { id: 'pv8', subjectSlug: 'padartha-vigyana', question: 'Which pramana is considered the most reliable in Ayurvedic diagnosis?', options: { A: 'Pratyaksha (direct)', B: 'Anumana (inference)', C: 'Aptopadesha (testimony)', D: 'Yukti (reasoning)' }, correct: 'A', explanation: 'Pratyaksha — direct perception via the 5 jnanendriya — is the most reliable. The other 3 pramanas supplement when direct perception is not possible.', difficulty: 'medium' },
  { id: 'pv9', subjectSlug: 'padartha-vigyana', question: 'Pragnaparadha — failure of intellect — is classified under:', options: { A: 'Sannikrishta nidana', B: 'Triavarjaneeya bhava', C: 'Vyabhichari nidana', D: 'Asatmyendriyartha' }, correct: 'B', explanation: 'Pragnaparadha (intellectual error) is one of the triavarjaneeya bhava — the 3 root causes of disease per Charaka. Considered most important.', difficulty: 'hard' },
  { id: 'pv10', subjectSlug: 'padartha-vigyana', question: 'Anumana pramana is based on what relationship?', options: { A: 'Cause-effect', B: 'Linga-lingi sambandha', C: 'Direct perception', D: 'Authority' }, correct: 'B', explanation: 'Anumana = inference based on linga-lingi (sign-significate) relationship. Smoke → fire is the classical example.', difficulty: 'hard' },

  // ── Dravyaguna (15) ──────────────────────────────
  { id: 'dg1', subjectSlug: 'dravyaguna-vigyana', question: 'How many components are in rasa panchaka?', options: { A: '3', B: '4', C: '5', D: '6' }, correct: 'C', explanation: 'Rasa Panchaka = 5: Rasa, Guna, Veerya, Vipaka, Prabhava.', difficulty: 'easy' },
  { id: 'dg2', subjectSlug: 'dravyaguna-vigyana', question: 'How many rasas are there in classical Ayurveda?', options: { A: '5', B: '6', C: '7', D: '8' }, correct: 'B', explanation: '6 rasas: madhura, amla, lavana, katu, tikta, kashaya.', difficulty: 'easy' },
  { id: 'dg3', subjectSlug: 'dravyaguna-vigyana', question: 'Madhura rasa is composed of which mahabhutas?', options: { A: 'Prithvi + Apa', B: 'Apa + Tejas', C: 'Vayu + Tejas', D: 'Akasha + Vayu' }, correct: 'A', explanation: 'Madhura rasa is prithvi + apa mahabhuta dominant. Aggravates kapha; pacifies vata + pitta.', difficulty: 'easy' },
  { id: 'dg4', subjectSlug: 'dravyaguna-vigyana', question: 'Veerya is most commonly classified into how many types?', options: { A: '2 (sheeta + ushna)', B: '4', C: '6', D: '8' }, correct: 'A', explanation: 'Classical 2-fold veerya: sheeta and ushna. Some texts expand to 8 but the binary remains clinically primary.', difficulty: 'medium' },
  { id: 'dg5', subjectSlug: 'dravyaguna-vigyana', question: 'Which vipaka does madhura, amla, lavana rasa typically yield?', options: { A: 'Katu', B: 'Amla', C: 'Madhura', D: 'Mixed' }, correct: 'C', explanation: 'Madhura + amla + lavana rasas → madhura vipaka. Katu, tikta, kashaya → katu vipaka. Amla rasa specifically → amla vipaka.', difficulty: 'medium' },
  { id: 'dg6', subjectSlug: 'dravyaguna-vigyana', question: 'Charaka enumerates how many dashemani?', options: { A: '20', B: '30', C: '50', D: '100' }, correct: 'C', explanation: '50 dashemani × 10 herbs each = 500 cardinal herbs. Charaka Sutra Sthana 4.', difficulty: 'medium' },
  { id: 'dg7', subjectSlug: 'dravyaguna-vigyana', question: 'Triphala consists of:', options: { A: 'Haritaki + Amalaki + Vibhitaki', B: 'Haritaki + Bibhitaki + Pippali', C: 'Amalaki + Maricha + Pippali', D: 'Vibhitaki + Shunthi + Pippali' }, correct: 'A', explanation: 'Triphala = Haritaki + Amalaki + Vibhitaki. Classical rasayana, mild laxative, antioxidant.', difficulty: 'easy' },
  { id: 'dg8', subjectSlug: 'dravyaguna-vigyana', question: 'Which dashemani contains amalaki, haritaki, vibhitaki, brahmi, ashwagandha?', options: { A: 'Jivaniya', B: 'Brimhaniya', C: 'Rasayana', D: 'Vajikarana' }, correct: 'C', explanation: 'Rasayana dashemani — 10 rejuvenative herbs including triphala + brahmi + mandukaparni + ashwagandha + bala + shilajatu.', difficulty: 'medium' },
  { id: 'dg9', subjectSlug: 'dravyaguna-vigyana', question: 'Danti shows virechana action through which attribute?', options: { A: 'Rasa', B: 'Veerya', C: 'Vipaka', D: 'Prabhava' }, correct: 'D', explanation: 'Danti\'s virechana action cannot be explained by rasa-guna-veerya-vipaka. It acts by prabhava — specific action.', difficulty: 'hard' },
  { id: 'dg10', subjectSlug: 'dravyaguna-vigyana', question: 'Tikta rasa is composed of:', options: { A: 'Vayu + Akasha', B: 'Vayu + Prithvi', C: 'Vayu + Tejas', D: 'Tejas + Akasha' }, correct: 'A', explanation: 'Tikta rasa: vayu + akasha mahabhuta. Pacifies pitta + kapha; aggravates vata.', difficulty: 'medium' },
  { id: 'dg11', subjectSlug: 'dravyaguna-vigyana', question: 'Vijayasara (Pterocarpus marsupium) is primarily used in:', options: { A: 'Hridroga', B: 'Prameha', C: 'Pandu', D: 'Shvitra' }, correct: 'B', explanation: 'Vijayasara is the classical first-line for prameha (diabetes). Modern trials show 0.5-1% HbA1c reduction with bark kashaya.', difficulty: 'medium' },
  { id: 'dg12', subjectSlug: 'dravyaguna-vigyana', question: 'Gymnema sylvestre (gudmar) acts on prameha by:', options: { A: 'Increasing insulin secretion', B: 'Blocking sweet taste perception + glucose absorption', C: 'Reducing fat absorption', D: 'Increasing thyroid activity' }, correct: 'B', explanation: 'Gudmar literally means "sugar destroyer" — Gymnemic acid blocks sweet taste perception and reduces intestinal glucose absorption.', difficulty: 'medium' },
  { id: 'dg13', subjectSlug: 'dravyaguna-vigyana', question: 'Which herb belongs to BOTH jivaniya and brimhaniya dashemani?', options: { A: 'Kakoli', B: 'Triphala', C: 'Pippali', D: 'Trikatu' }, correct: 'A', explanation: 'Kakoli (and ksheera-kakoli) appear in both jivaniya and brimhaniya dashemani — life-promoting + mass-building.', difficulty: 'hard' },
  { id: 'dg14', subjectSlug: 'dravyaguna-vigyana', question: 'Bhavaprakasha Nighantu was composed by:', options: { A: 'Charaka', B: 'Sushruta', C: 'Bhavamishra', D: 'Vagbhata' }, correct: 'C', explanation: 'Bhavamishra (~16th century) composed Bhavaprakasha — the standard nighantu (materia medica) used in Ayurveda colleges today.', difficulty: 'easy' },
  { id: 'dg15', subjectSlug: 'dravyaguna-vigyana', question: 'Maha-tikta ghrita is used in:', options: { A: 'Skin disorders, jaundice, chronic toxicity', B: 'Cardiac disease', C: 'Fertility', D: 'Insomnia only' }, correct: 'A', explanation: 'Maha-tikta ghrita — multi-herb bitter ghrita. Used in kushtha, kamla (jaundice), dushivisha (chronic toxicity).', difficulty: 'medium' },

  // ── Rasashastra (10) ──────────────────────────────
  { id: 'rs1', subjectSlug: 'rasashastra', question: 'How many doshas does raw parada (mercury) contain?', options: { A: '5', B: '7', C: '8', D: '10' }, correct: 'C', explanation: '8 doshas of parada: naga, vanga, mala, vahni, visha, asahyagni, daya, chapalata. Plus 5 kanchukas.', difficulty: 'medium' },
  { id: 'rs2', subjectSlug: 'rasashastra', question: 'How many samskaras is parada subjected to?', options: { A: '7', B: '12', C: '18', D: '24' }, correct: 'C', explanation: '18 samskaras: 8 shodhana + 5 stages of marana + 5 utility samskaras.', difficulty: 'medium' },
  { id: 'rs3', subjectSlug: 'rasashastra', question: 'Properly prepared rasa-sindura contains chemically:', options: { A: 'Elemental Hg', B: 'HgO', C: 'HgS (cinnabar)', D: 'Hg + Pb mixture' }, correct: 'C', explanation: 'Rasa-sindura = mercuric sulphide (HgS, cinnabar). Biologically inert, non-toxic at therapeutic doses.', difficulty: 'hard' },
  { id: 'rs4', subjectSlug: 'rasashastra', question: 'Swedana is the first step of which process?', options: { A: 'Marana', B: 'Shodhana', C: 'Jarana', D: 'Vedha' }, correct: 'B', explanation: 'Swedana is step 1 of 8-step parada shodhana. Parada tied in cloth and boiled in herbal kashaya for 3 days.', difficulty: 'medium' },
  { id: 'rs5', subjectSlug: 'rasashastra', question: 'Makaradhwaja is primarily used for:', options: { A: 'Jvara', B: 'Vajikarana / ojas restoration', C: 'Atisara', D: 'Pandu' }, correct: 'B', explanation: 'Makaradhwaja — kupipakwa rasayana with parada + suvarna. Primary indication: vajikarana, ojas-vardhana.', difficulty: 'medium' },
  { id: 'rs6', subjectSlug: 'rasashastra', question: 'Sharangadhara Samhita defines pharmaceutical preparations into how many classes?', options: { A: '5', B: '7', C: '12', D: '17' }, correct: 'D', explanation: 'Sharangadhara enumerates 17 kalpana: kashaya, swarasa, kalka, hima, phanta, churnam, vati, gutika, taila, ghrita, asava, arishta, etc.', difficulty: 'hard' },
  { id: 'rs7', subjectSlug: 'rasashastra', question: 'Marana of metal bhasma is verified by:', options: { A: 'Niruttha test only', B: 'Apunarbhava test only', C: 'Both niruttha + apunarbhava + varitara', D: 'Chemical analysis' }, correct: 'C', explanation: 'Classical bhasma verification: niruttha (no metallic luster), apunarbhava (cannot revert), varitara (floats on water), rekhapurana (fills lines of fingers).', difficulty: 'hard' },
  { id: 'rs8', subjectSlug: 'rasashastra', question: 'Which is NOT a maharasa?', options: { A: 'Abhrak', B: 'Vaikranta', C: 'Makshik', D: 'Vimala' }, correct: 'D', explanation: 'Vimala is uparasa, not maharasa. The 8 maharasas: abhrak, vaikranta, makshik, vimala (in some texts), shilajatu, sasyaka, chapala, rasaka. Lists vary slightly.', difficulty: 'hard' },
  { id: 'rs9', subjectSlug: 'rasashastra', question: 'Tribhuvana Kirti Rasa is used in:', options: { A: 'Hridroga', B: 'Vishama jvara, sannipata', C: 'Prameha', D: 'Vatavyadhi' }, correct: 'B', explanation: 'Tribhuvana Kirti Rasa — classical anti-pyretic; vishama jvara, sannipataja jvara.', difficulty: 'medium' },
  { id: 'rs10', subjectSlug: 'rasashastra', question: 'Bhasma dose for adults typically ranges:', options: { A: '5-15 mg', B: '30-125 mg', C: '500 mg - 1g', D: '3-5g' }, correct: 'B', explanation: 'Classical bhasma dose: 30-125 mg with anupana (madhu, ghrita, ksheera). Some specific bhasmas at higher dose but generally low.', difficulty: 'easy' },

  // ── Roga Nidana (10) ──────────────────────────────
  { id: 'rn1', subjectSlug: 'roga-nidana', question: 'Nidana Panchaka consists of:', options: { A: '4 elements', B: '5 elements', C: '6 elements', D: '7 elements' }, correct: 'B', explanation: '5 elements: Nidana, Purvarupa, Rupa, Upashaya, Samprapti.', difficulty: 'easy' },
  { id: 'rn2', subjectSlug: 'roga-nidana', question: 'Upashaya is:', options: { A: 'The complete symptoms', B: 'Diagnostic-therapeutic trial', C: 'Disease pathway', D: 'Causative factor' }, correct: 'B', explanation: 'Upashaya = trial of treatment to confirm diagnosis. If suspected diagnosis improves with appropriate therapy, diagnosis confirmed.', difficulty: 'medium' },
  { id: 'rn3', subjectSlug: 'roga-nidana', question: 'Which is NOT a stage in samprapti?', options: { A: 'Hetu sevana', B: 'Dosha prakopa', C: 'Bheda', D: 'Pramana' }, correct: 'D', explanation: 'Samprapti stages: hetu sevana → prakopa → prasara → sthana samshraya → vyakti → bheda. Pramana is not a samprapti stage.', difficulty: 'medium' },
  { id: 'rn4', subjectSlug: 'roga-nidana', question: 'Amavata\'s primary samprapti involves which dosha disorder?', options: { A: 'Pitta-rakta', B: 'Vata + ama in sandhis', C: 'Kapha-meda', D: 'Sannipata' }, correct: 'B', explanation: 'Amavata: manda agni → ama → vyana vayu carries ama to sandhis → ama-vata combination → joint pain + stiffness.', difficulty: 'medium' },
  { id: 'rn5', subjectSlug: 'roga-nidana', question: 'Madhava Nidana primarily covers how many disease groups?', options: { A: '50', B: '79', C: '100', D: '150' }, correct: 'B', explanation: 'Madhava Nidana covers 79 disease groups using the nidana panchaka framework. Classical roga-nidana reference text.', difficulty: 'medium' },
  { id: 'rn6', subjectSlug: 'roga-nidana', question: 'Pratyatma lakshana is:', options: { A: 'General symptoms', B: 'Pathognomonic symptom — specific to that disease', C: 'Mental symptoms', D: 'Associated symptoms' }, correct: 'B', explanation: 'Pratyatma = specific. Pratyatma lakshana is the symptom that uniquely points to a disease. Anubandha = associated/related.', difficulty: 'hard' },
  { id: 'rn7', subjectSlug: 'roga-nidana', question: 'Vishuchika main pratyatma lakshana is:', options: { A: 'Vomiting + diarrhoea + cramps', B: 'Joint pain', C: 'Fever + chills', D: 'Cough' }, correct: 'A', explanation: 'Vishuchika = acute gastroenteritis. Pratyatma lakshana: simultaneous vomiting + diarrhoea + abdominal cramps.', difficulty: 'easy' },
  { id: 'rn8', subjectSlug: 'roga-nidana', question: 'Which type of jvara has the highest mortality?', options: { A: 'Vataja', B: 'Pittaja', C: 'Kaphaja', D: 'Sannipataja' }, correct: 'D', explanation: 'Sannipataja jvara — all 3 doshas vitiated simultaneously. Highest mortality; often corresponds to severe systemic infections (sepsis).', difficulty: 'medium' },
  { id: 'rn9', subjectSlug: 'roga-nidana', question: 'Pakvashayagata vata typically presents with:', options: { A: 'Headache only', B: 'Constipation + adhmana + shoola', C: 'Joint stiffness', D: 'Cardiac symptoms' }, correct: 'B', explanation: 'Pakvashayagata vata (vata in large intestine): constipation, abdominal distension (adhmana), pain (shoola), gas formation.', difficulty: 'medium' },
  { id: 'rn10', subjectSlug: 'roga-nidana', question: 'Sukha-sadhya disease is characterized by:', options: { A: 'All 3 doshas + complications', B: 'Single dosha + recent onset + healthy patient', C: 'Lifelong control needed', D: 'Terminal' }, correct: 'B', explanation: 'Sukha-sadhya = easily curable. Criteria: single dosha (eka doshaja), recent onset, healthy patient, no complications.', difficulty: 'easy' },

  // ── Kayachikitsa (15) ──────────────────────────────
  { id: 'kc1', subjectSlug: 'kayachikitsa', question: 'How many subtypes of prameha does Charaka enumerate?', options: { A: '10', B: '15', C: '20', D: '25' }, correct: 'C', explanation: '20 prameha subtypes: 10 kaphaja + 6 pittaja + 4 vataja. Madhumeha is the 4th vataja type.', difficulty: 'easy' },
  { id: 'kc2', subjectSlug: 'kayachikitsa', question: 'Vatavyadhi count per Charaka is:', options: { A: '40', B: '60', C: '80', D: '100' }, correct: 'C', explanation: '80 vatavyadhi enumerated by Charaka. Includes paksha-aghata, ardita, gridhrasi, sandhigatavata, etc.', difficulty: 'medium' },
  { id: 'kc3', subjectSlug: 'kayachikitsa', question: 'Sandhigatavata corresponds to:', options: { A: 'Rheumatoid arthritis', B: 'Osteoarthritis', C: 'Gouty arthritis', D: 'Septic arthritis' }, correct: 'B', explanation: 'Sandhigatavata — joint pain due to vata involvement. Most closely corresponds to osteoarthritis.', difficulty: 'medium' },
  { id: 'kc4', subjectSlug: 'kayachikitsa', question: 'First-line treatment in amavata is:', options: { A: 'Snehapana immediately', B: 'Langhana + deepana-pachana', C: 'Raktamokshana', D: 'Vamana' }, correct: 'B', explanation: 'Amavata involves ama, so first remove ama with langhana + deepana-pachana. Snehapana before ama removal worsens disease.', difficulty: 'medium' },
  { id: 'kc5', subjectSlug: 'kayachikitsa', question: 'Pandu (anemia) primary treatment principle is:', options: { A: 'Iron supplementation alone', B: 'Rakta-vardhana + agni correction', C: 'Vamana', D: 'Raktamokshana' }, correct: 'B', explanation: 'Pandu chikitsa: rakta-vardhana herbs (loha bhasma, mandura bhasma) + correct agnimandhya which underlies most pandu cases.', difficulty: 'medium' },
  { id: 'kc6', subjectSlug: 'kayachikitsa', question: 'Pippali rasayana is used in:', options: { A: 'Acute jvara', B: 'Chronic respiratory diseases, kasa, shwasa', C: 'Hridroga', D: 'Prameha' }, correct: 'B', explanation: 'Pippali rasayana — vardhamana pippali. Classical for kasa, shwasa, chronic bronchitis, allergic rhinitis.', difficulty: 'medium' },
  { id: 'kc7', subjectSlug: 'kayachikitsa', question: 'Hridroga panchaka (5 types) include all EXCEPT:', options: { A: 'Vataja', B: 'Pittaja', C: 'Kaphaja', D: 'Aagantuja' }, correct: 'D', explanation: 'Charaka enumerates 5 hridroga: vataja, pittaja, kaphaja, sannipataja, krimija. Aagantuja is broader category, not in the 5.', difficulty: 'hard' },
  { id: 'kc8', subjectSlug: 'kayachikitsa', question: 'Tamak shwasa is treated primarily with:', options: { A: 'Vamana + kapha-shamana', B: 'Virechana', C: 'Basti only', D: 'Raktamokshana' }, correct: 'A', explanation: 'Tamak shwasa = bronchial asthma. Vamana is the primary shodhana; followed by kapha-vata shamana with pippali, vasa, kantakari.', difficulty: 'medium' },
  { id: 'kc9', subjectSlug: 'kayachikitsa', question: 'Vyana vayu primary function is:', options: { A: 'Digestion', B: 'Speech', C: 'Circulation throughout body', D: 'Excretion' }, correct: 'C', explanation: 'Vyana vayu: circulates rasa-rakta throughout body. Located in hridaya, moves all over. Cardio-respiratory work.', difficulty: 'easy' },
  { id: 'kc10', subjectSlug: 'kayachikitsa', question: 'Vatavyadhi general chikitsa includes:', options: { A: 'Snehana + swedana + basti', B: 'Langhana + raktamokshana', C: 'Vamana + virechana', D: 'Cold water therapy' }, correct: 'A', explanation: 'Vatavyadhi: snehana (oleation) + swedana (sudation) + basti are the 3 primary treatments. Basti is called "ardha chikitsa" for vata.', difficulty: 'easy' },
  { id: 'kc11', subjectSlug: 'kayachikitsa', question: 'Gridhrasi corresponds to:', options: { A: 'Migraine', B: 'Sciatica', C: 'Facial palsy', D: 'Carpal tunnel' }, correct: 'B', explanation: 'Gridhrasi = pain along the sciatic nerve distribution. Classical vatavyadhi treated with vati basti + erandapaka + masha balatailam.', difficulty: 'easy' },
  { id: 'kc12', subjectSlug: 'kayachikitsa', question: 'Avalambaka kapha is located in:', options: { A: 'Hridaya, urah', B: 'Amashaya', C: 'Sandhi', D: 'Tongue' }, correct: 'A', explanation: 'Avalambaka kapha — located in hridaya, urah (chest). Supports the head and other kapha types.', difficulty: 'medium' },
  { id: 'kc13', subjectSlug: 'kayachikitsa', question: 'Atrtisara (chronic diarrhoea) most commonly due to:', options: { A: 'Kaphaja agni', B: 'Vishama agni + manda agni → ama', C: 'Tikshna agni alone', D: 'Pittaja prameha' }, correct: 'B', explanation: 'Atrtisara — chronic diarrhoea — typically vishama agni + manda agni leading to ama formation and grahani involvement.', difficulty: 'medium' },
  { id: 'kc14', subjectSlug: 'kayachikitsa', question: 'Madhyama roga marga involves:', options: { A: 'Skin + rakta + mamsa', B: 'Marma + sandhi + asthi', C: 'Kostha (GI tract)', D: 'Manas' }, correct: 'B', explanation: '3 roga marga: bahya (skin, rakta, mamsa) — external; madhyama (marma, sandhi, asthi) — middle; abhyantara (kostha) — internal.', difficulty: 'hard' },
  { id: 'kc15', subjectSlug: 'kayachikitsa', question: 'Ardita corresponds to:', options: { A: 'Hemiplegia', B: 'Bell\'s palsy / facial palsy', C: 'Migraine', D: 'Tetanus' }, correct: 'B', explanation: 'Ardita = facial palsy (Bell\'s palsy). Vata-vyadhi. Treatment: nasya, abhyanga, basti, internal vata-pacifying medicines.', difficulty: 'medium' },

  // ── Shalya Tantra (10) ──────────────────────────────
  { id: 'st1', subjectSlug: 'shalya-tantra', question: 'Total instruments described by Sushruta:', options: { A: '101 yantras + 20 shastras', B: '50 yantras + 25 shastras', C: '121 yantras + 20 shastras', D: '101 yantras + 18 shastras' }, correct: 'A', explanation: '101 yantras (blunt instruments in 6 categories) + 20 shastras (sharp instruments). Total 121.', difficulty: 'easy' },
  { id: 'st2', subjectSlug: 'shalya-tantra', question: 'Surgical procedures (ashta vidha shastra karma) include all EXCEPT:', options: { A: 'Chedya', B: 'Bhedya', C: 'Lekhya', D: 'Bhojya' }, correct: 'D', explanation: '8 surgical karma: chedya, bhedya, lekhya, vedhya, eshya, ahrya, visravya, seevya. Bhojya is not surgical.', difficulty: 'medium' },
  { id: 'st3', subjectSlug: 'shalya-tantra', question: 'Sushruta\'s rhinoplasty technique uses:', options: { A: 'Forehead flap', B: 'Cheek flap only', C: 'Skin grafting only', D: 'Synthetic implant' }, correct: 'A', explanation: 'Sushruta describes forehead flap (paramedian) for rhinoplasty — historical basis for modern Indian forehead-flap rhinoplasty.', difficulty: 'medium' },
  { id: 'st4', subjectSlug: 'shalya-tantra', question: 'Arsha (haemorrhoids) classification by Sushruta is based on:', options: { A: 'Location only', B: 'Doshic involvement + location', C: 'Bleeding pattern only', D: 'Size only' }, correct: 'B', explanation: 'Sushruta classifies arsha by doshic dominance (vataja, pittaja, kaphaja, sannipataja, sahaja) and location.', difficulty: 'medium' },
  { id: 'st5', subjectSlug: 'shalya-tantra', question: 'Ksharasutra is used in:', options: { A: 'Fistula in ano (bhagandara)', B: 'Cataract surgery', C: 'Hernia repair', D: 'Spine surgery' }, correct: 'A', explanation: 'Ksharasutra — medicated thread soaked in alkaline preparations + snuhi latex + haridra. Standard treatment for fistula in ano.', difficulty: 'easy' },
  { id: 'st6', subjectSlug: 'shalya-tantra', question: 'Sushruta\'s pre-operative sterilisation method included:', options: { A: 'Boiling instruments only', B: 'Flame + kashaya wash + sun drying', C: 'Alcohol only', D: 'Chemical antiseptic' }, correct: 'B', explanation: 'Multi-step: heating in flame, washing in haridra-lodhra-neem kashaya, sun drying. Predates Lister by 2500 years.', difficulty: 'medium' },
  { id: 'st7', subjectSlug: 'shalya-tantra', question: 'How many sandhana karma (fracture reduction techniques) does Sushruta describe?', options: { A: '6', B: '8', C: '12', D: '20' }, correct: 'C', explanation: '12 sandhana karma. 6 for long-bone fractures, 6 for joint dislocations.', difficulty: 'medium' },
  { id: 'st8', subjectSlug: 'shalya-tantra', question: 'Vrana (wound) shotha is classified into:', options: { A: '2 types', B: '5 types', C: '7 types', D: '10 types' }, correct: 'C', explanation: '7 types of vrana shotha by Sushruta. Classification by doshic dominance + chronicity.', difficulty: 'hard' },
  { id: 'st9', subjectSlug: 'shalya-tantra', question: 'Yantras are how many in number?', options: { A: '50', B: '76', C: '101', D: '121' }, correct: 'C', explanation: '101 yantras: 24 swastika + 2 sandansha + 2 tala + 20 nadi + 28 shalaka + 25 upayantra.', difficulty: 'easy' },
  { id: 'st10', subjectSlug: 'shalya-tantra', question: 'Modern speculum is closest to which yantra?', options: { A: 'Swastika yantra', B: 'Nadi yantra', C: 'Shalaka yantra', D: 'Tala yantra' }, correct: 'B', explanation: 'Nadi yantra — tubular/hollow instrument. Modern speculum (Cusco, Sims), proctoscope are direct descendants.', difficulty: 'easy' },

  // ── Panchakarma (10) ──────────────────────────────
  { id: 'pk1', subjectSlug: 'panchakarma', question: 'Panchakarma includes all EXCEPT:', options: { A: 'Vamana', B: 'Virechana', C: 'Basti', D: 'Snana' }, correct: 'D', explanation: 'Panchakarma = 5 procedures: vamana, virechana, basti, nasya, raktamokshana. Snana is daily routine, not panchakarma.', difficulty: 'easy' },
  { id: 'pk2', subjectSlug: 'panchakarma', question: 'Samyak vamana is characterized by how many vegas?', options: { A: '3-4', B: '4-5', C: '6-8', D: '10-12' }, correct: 'C', explanation: '6-8 vegas = samyak vamana. <6 = ayoga (incomplete); >8 = atiyoga (excess, risk of complications).', difficulty: 'medium' },
  { id: 'pk3', subjectSlug: 'panchakarma', question: 'Snehapana ascending dose protocol typically lasts:', options: { A: '3 days', B: '5-7 days', C: '14 days', D: '21 days' }, correct: 'B', explanation: 'Snehapana protocol: 5-7 days. Starts 30ml, increases to 100-150ml or until samyak snigdha signs appear.', difficulty: 'medium' },
  { id: 'pk4', subjectSlug: 'panchakarma', question: 'Karma basti protocol consists of how many bastis?', options: { A: '8', B: '15', C: '30', D: '60' }, correct: 'C', explanation: 'Karma basti = 30 bastis: 12 niruha + 16 anuvasana + 2 buffer. Intensive protocol for severe chronic vata-vyadhi.', difficulty: 'medium' },
  { id: 'pk5', subjectSlug: 'panchakarma', question: 'Yoga basti consists of:', options: { A: '5 bastis', B: '8 bastis', C: '15 bastis', D: '30 bastis' }, correct: 'B', explanation: 'Yoga basti = 8 bastis (3 niruha + 5 anuvasana). For mild vata-vyadhi or maintenance.', difficulty: 'medium' },
  { id: 'pk6', subjectSlug: 'panchakarma', question: 'Anuvasana basti volume is typically:', options: { A: '30-50ml', B: '60-180ml', C: '300-600ml', D: '1L+' }, correct: 'B', explanation: 'Anuvasana basti (oil basti) volume: 60-180ml. Retained overnight or 4-6 hours.', difficulty: 'medium' },
  { id: 'pk7', subjectSlug: 'panchakarma', question: 'Sansarjana karma duration is:', options: { A: '3 days', B: '5 days', C: '7 days', D: '14 days' }, correct: 'C', explanation: 'Sansarjana karma = 7-day graduated diet after vamana/virechana. Peya → vilepi → akrita yusha → krita yusha → akrita mansa rasa → krita mansa rasa → normal diet.', difficulty: 'medium' },
  { id: 'pk8', subjectSlug: 'panchakarma', question: 'Sirobasti is a procedure performed on:', options: { A: 'Head — leather cap holds medicated oil', B: 'Stomach', C: 'Joints', D: 'Eyes' }, correct: 'A', explanation: 'Sirobasti — leather cap fitted on head, medicated oil retained for 30-90 minutes. Indications: neurological vata-vyadhi.', difficulty: 'medium' },
  { id: 'pk9', subjectSlug: 'panchakarma', question: 'Pizhichil is which Kerala therapy?', options: { A: 'Steam therapy', B: 'Oil pouring full-body massage', C: 'Powder massage', D: 'Compress therapy' }, correct: 'B', explanation: 'Pizhichil — continuous oil pouring over body with simultaneous gentle massage. Kerala signature therapy for vatavyadhi.', difficulty: 'easy' },
  { id: 'pk10', subjectSlug: 'panchakarma', question: 'Strict contraindication to vamana:', options: { A: 'Mild kapha asthma', B: 'Pregnancy + bleeding disorder', C: 'Mild obesity', D: 'Chronic sinusitis' }, correct: 'B', explanation: 'Absolute contraindications: pregnancy, bleeding disorders, recent MI, severe debility, active peptic ulcer, severe malnutrition.', difficulty: 'easy' },

  // ── Prasuti Tantra (10) ──────────────────────────────
  { id: 'pt1', subjectSlug: 'prasuti-tantra', question: 'Total artava vyapad classified by Charaka:', options: { A: '12', B: '15', C: '20', D: '25' }, correct: 'C', explanation: '20 yoni vyapad / artava vyapad by Charaka. Cover menstrual + ovulatory + pelvic disorders.', difficulty: 'medium' },
  { id: 'pt2', subjectSlug: 'prasuti-tantra', question: 'Garbhini paricharya begins from:', options: { A: '3rd month', B: '5th month', C: '1st month', D: 'Confirmation' }, correct: 'C', explanation: 'Garbhini paricharya — month-by-month from 1st masa onwards. 1st month focus: stabilising (sthapana).', difficulty: 'easy' },
  { id: 'pt3', subjectSlug: 'prasuti-tantra', question: 'Strict shodhana during pregnancy is:', options: { A: 'Always indicated', B: 'Generally contraindicated', C: 'Only in 1st trimester', D: 'Only in 9th month' }, correct: 'B', explanation: 'Strict shodhana (vamana, virechana, niruha basti) generally contraindicated. Exception: gentle anuvasana basti in 8-9th month for delivery.', difficulty: 'medium' },
  { id: 'pt4', subjectSlug: 'prasuti-tantra', question: 'Garbha-srava (miscarriage) classical first action:', options: { A: 'Bed rest + ksheera-pradhana diet', B: 'Aggressive medication', C: 'Vamana', D: 'Heated abdominal compress' }, correct: 'A', explanation: 'For threatened abortion: absolute bed rest + light ksheera-pradhana diet + brimhana drugs to support garbha stability.', difficulty: 'medium' },
  { id: 'pt5', subjectSlug: 'prasuti-tantra', question: 'Pumsavana karma is performed at:', options: { A: '1st month', B: '2nd-3rd month before cerebral differentiation', C: '6th month', D: '9th month' }, correct: 'B', explanation: 'Pumsavana karma — classical "male offspring" procedure, performed around 2-3rd month before garbha cerebral differentiation. (Note: gender selection is now illegal in India per PCPNDT Act.)', difficulty: 'hard' },
  { id: 'pt6', subjectSlug: 'prasuti-tantra', question: 'Sutika paricharya (post-partum) classical duration:', options: { A: '21 days', B: '45 days', C: '90 days', D: 'Lifetime' }, correct: 'B', explanation: 'Sutika paricharya — 45 days. Kerala extends to 90 days. Includes daily abhyanga, specific diet, mother-baby seclusion.', difficulty: 'easy' },
  { id: 'pt7', subjectSlug: 'prasuti-tantra', question: 'Stanya-vardhana (galactogue) herb:', options: { A: 'Shatavari', B: 'Triphala', C: 'Trikatu', D: 'Guggulu' }, correct: 'A', explanation: 'Shatavari (Asparagus racemosus) — classical stanya-vardhana. Also pippali, methika.', difficulty: 'easy' },
  { id: 'pt8', subjectSlug: 'prasuti-tantra', question: 'Asrigdara corresponds to:', options: { A: 'Amenorrhoea', B: 'Menorrhagia + metrorrhagia', C: 'Dysmenorrhoea', D: 'PCOS' }, correct: 'B', explanation: 'Asrigdara — excessive menstrual bleeding. Classical pittaja-rakta vikara.', difficulty: 'medium' },
  { id: 'pt9', subjectSlug: 'prasuti-tantra', question: 'Kshira-bala taila is used in:', options: { A: 'Sutika abhyanga', B: 'Shirodhara only', C: 'Bowel cleansing', D: 'Eye therapy' }, correct: 'A', explanation: 'Kshira-bala taila — classical for sutika paricharya post-partum abhyanga. Also used for vata-vyadhi (especially neurological).', difficulty: 'medium' },
  { id: 'pt10', subjectSlug: 'prasuti-tantra', question: 'Stana-shyandha (mastitis) primary chikitsa:', options: { A: 'Vamana', B: 'Local lepa + sthanika upachara + systemic shamana', C: 'Raktamokshana', D: 'Niruha basti' }, correct: 'B', explanation: 'Mastitis: local treatment (lepa, hot fomentation) + systemic anti-inflammatory + galactogue support if breastfeeding to continue.', difficulty: 'medium' },

  // ── Kriya Sharira (10) ──────────────────────────────
  { id: 'ks1', subjectSlug: 'kriya-sharira', question: 'Total number of agnis in classical Ayurveda:', options: { A: '7', B: '12', C: '13', D: '15' }, correct: 'C', explanation: '13 agnis: 1 jatharagni + 5 bhutagnis + 7 dhatvagnis.', difficulty: 'easy' },
  { id: 'ks2', subjectSlug: 'kriya-sharira', question: 'Jatharagni is located in:', options: { A: 'Hridaya', B: 'Grahani (duodenum/jejunum)', C: 'Yakrit (liver)', D: 'Pakvashaya' }, correct: 'B', explanation: 'Jatharagni located in grahani — duodenum + jejunum area. Master fire controlling all other agnis.', difficulty: 'easy' },
  { id: 'ks3', subjectSlug: 'kriya-sharira', question: 'Bhutagnis are located in:', options: { A: 'Mouth', B: 'Yakrit (liver)', C: 'Grahani', D: 'Skin' }, correct: 'B', explanation: 'Bhutagnis (5 mahabhuta-specific fires) located in yakrit. Process food into bhautika components after jatharagni-amashaya breakdown.', difficulty: 'medium' },
  { id: 'ks4', subjectSlug: 'kriya-sharira', question: 'Vishama agni is associated with which dosha dominance?', options: { A: 'Vata', B: 'Pitta', C: 'Kapha', D: 'Sannipata' }, correct: 'A', explanation: 'Vishama agni (irregular, unstable) → vata-dominant. Tikshna agni → pitta; manda → kapha; sama → balanced.', difficulty: 'medium' },
  { id: 'ks5', subjectSlug: 'kriya-sharira', question: 'Ama is best defined as:', options: { A: 'Excess kapha', B: 'Undigested rasa with toxic properties', C: 'Pitta deficiency', D: 'Excess vata' }, correct: 'B', explanation: 'Ama = undigested rasa due to manda agni. Has toxic properties. Mula (root) of most chronic disease per Charaka.', difficulty: 'medium' },
  { id: 'ks6', subjectSlug: 'kriya-sharira', question: 'Dhatu formation cycle (per sthayi dhatu):', options: { A: '24 hours', B: '5 days', C: '7 days', D: '30 days' }, correct: 'B', explanation: 'Sapta dhatu cycle: 5 days for each dhatu transformation. Rasa → rakta over 5 days, etc. Total: 35 days for shukra/artava formation.', difficulty: 'hard' },
  { id: 'ks7', subjectSlug: 'kriya-sharira', question: 'Para ojas quantity is:', options: { A: '8 drops in hridaya', B: '½ anjali in body', C: '1 anjali in hridaya', D: '5 drops in head' }, correct: 'A', explanation: 'Para ojas: 8 drops (ashta-bindu) located in hridaya. Apara ojas: ½ anjali pramana, distributed throughout.', difficulty: 'medium' },
  { id: 'ks8', subjectSlug: 'kriya-sharira', question: 'Apana vayu primary function:', options: { A: 'Digestion', B: 'Excretion (urine, faeces, menstruation, ejaculation)', C: 'Speech', D: 'Cardiac activity' }, correct: 'B', explanation: 'Apana vayu — located in pakvashaya. Function: downward expulsion — mootra, purisha, artava, shukra, garbha.', difficulty: 'easy' },
  { id: 'ks9', subjectSlug: 'kriya-sharira', question: 'Sapta dhatu in order are:', options: { A: 'Rasa, rakta, mamsa, meda, asthi, majja, shukra', B: 'Rakta, rasa, mamsa, meda, majja, asthi, shukra', C: 'Rasa, mamsa, rakta, asthi, meda, majja, shukra', D: 'Rasa, rakta, asthi, mamsa, meda, majja, shukra' }, correct: 'A', explanation: 'Sequential order: rasa → rakta → mamsa → meda → asthi → majja → shukra. Each previous dhatu nourishes next.', difficulty: 'easy' },
  { id: 'ks10', subjectSlug: 'kriya-sharira', question: 'Rasa dhatu function includes:', options: { A: 'Strength only', B: 'Preenana (nourishment) + prithak srotas function', C: 'Movement', D: 'Reproduction' }, correct: 'B', explanation: 'Rasa dhatu main function: preenana (general nourishment). Carrying nutrients to all dhatus. Also forms body fluid.', difficulty: 'medium' },
]

export const MCQ_SLUGS = MCQS.map((m) => m.id)
